"""Preserve market evidence and the proposed stock responsibility, without catalog creation."""
from scripts.apply_supplier_return_U387 import ROOT, save, append


def main():
    assert not (ROOT/'modeles/backlog/consignment-inventory-review.yaml').exists()
    sources=[
        dict(id='CI-S1',vendor='Microsoft',product='Dynamics 365 business process guidance',title='Overview of inventory to deliver business process',url='https://learn.microsoft.com/en-us/dynamics365/guidance/business-processes/inventory-to-deliver-overview',edition='Page évolutive ; avertissement de mise à jour des titres au catalogue July 2026 et de diagrammes parfois antérieurs',locator='Inventory to deliver business process flow : Track supplier managed inventory and consignment inventory',nature='Cartographie de processus',access='Page primaire ouverte',finding='La consignation figure dans le parcours Inventory to deliver relié à Source to pay et Record to report.',limit='Sous-processus dans une cartographie de flux, pas capacité entreprise de niveau identique à FLOW ; rang exact du catalogue de juillet non déduit du diagramme.'),
        dict(id='CI-S2',vendor='Microsoft',product='Dynamics 365 SCM',title='Set up consignment',url='https://learn.microsoft.com/en-us/dynamics365/supply-chain/inventory/consignment',edition='Documentation évolutive',locator='Overview of the consignment process ; Consignment replenishment orders ; Inventory ownership change journal',nature='Processus et fonctions produit',access='Texte primaire consulté',finding='Stock détenu physiquement mais appartenant au fournisseur ; changements de propriété, suivi partagé, lien achats/facturation.',limit='Exemple de consommation en production ; ne démontre pas l’ensemble des responsabilités assurantielles ou de fin de saison retail.'),
        dict(id='CI-S3',vendor='SAP',product='S/4HANA Cloud Retail and Fashion and Vertical Business',title='Inventory Management: Special Stocks',url='https://help.sap.com/docs/SAP_S4HANA_CLOUD/64609d0ecac54654b0837cba34555b82/389bc7536e8e2a4be10000000a174cb4.html',edition='2608 affichée dans le passage indexé',locator='Externally-Owned Special Stocks : supplier Consignment ; Own Special Stocks',nature='Catégories de stock et responsabilité fonctionnelle',access='Passage primaire indexé lu ; portail ouvert sans texte exploitable',finding='Distingue stock propre détenu ailleurs et stock appartenant à un tiers détenu chez soi ; consignation fournisseur dans Inventory Management.',limit='Pas un export de la cartographie SAP RBA ; détention et propriété ne fixent pas à elles seules assurance et devenir.'),
        dict(id='CI-S4',vendor='SAP',product='Enterprise Architecture Knowledge Base',title='Application Choices and Decisions for Procure to Receipt Process',url='https://community.sap.com/t5/enterprise-architecture-knowledge-base/application-choices-and-decisions-for-procure-to-receipt-process/tac-p/14083502/highlight/true',edition='Article 2025, publication affichée 21 avril ; pas une version formelle du RBA',locator='Applicable SAP Best Practices ; Characterization of the Solution Options ; Critical Process Variant 8',nature='Guide d’architecture applicative et correspondances de capacités',access='Texte primaire indexé consulté ; ouverture directe en erreur, figures non inspectées',finding='Supplier Consignment (2LG) et Direct Physical Products Consignment sont traités dans Procure to Receipt ; distingue business capabilities, solution capabilities et variantes de processus.',limit='Confirme un point de vue achats dans la cartographie ; ne prouve pas que la consignation soit une unique capacité Purchase Order. Les feuilles des figures non lues ne sont pas revendiquées.'),
        dict(id='CI-S5',vendor='Oracle',product='Fusion Cloud SCM',title='Consigned Inventory',url='https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/25d/faims/consigned-inventory.html',edition='25D',locator='Consignment Agreement ; Ship and Receive Items ; Consumption Advice',nature='Cycle de gestion fonctionnel',access='Page primaire ouverte',finding='Accord de consignation, stock détenu pour le fournisseur, avis de consommation et interface vers le règlement.',limit='Processus transverse et exemple de règlement, pas règle universelle de transfert de propriété ou preuve d’une capacité couvrant l’assurance.'),
        dict(id='CI-S6',vendor='Oracle',product='NetSuite',title='Consigned Inventory Management',url='https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/article_94502112.html',edition='Documentation évolutive, version non affichée',locator='Introduction et liste des fonctions',nature='Fonctionnalité produit explicitement nommée',access='Page primaire ouverte',finding='Gestion des quantités et coûts, stock consigné et non consigné, mouvements, retours, comptages et suivi des demandes/réapprovisionnements.',limit='Appui lexical précis pour le nom proposé ; fonctionnalité NetSuite, pas équivalence automatique de capacité ni couverture globale du périmètre FLOW.'),
        dict(id='CI-S7',vendor='Oracle',product='Fusion Cloud SCM',title='Redwood: Manage Consigned Inventory Using a Redwood Page',url='https://docs.oracle.com/en/cloud/saas/readiness/scm/25a/inv25a/25A-inventory-wn-f35543.htm',edition='25A',locator='Introduction et onglet Consigned',nature='Fonctionnalité Inventory Management',access='Page primaire ouverte',finding='Âge du stock et transferts de propriété traités dans Inventory Management.',limit='Ne décrit pas les issues soldeur, seconde main ou destruction de fin de saison ; ne pas les déduire de la seule échéance.'),
    ]
    for s in sources:s['consulted_on']='2026-09-18'
    candidate=dict(name='Consigned Inventory Management',parent_id='D01',status='proposed',nature='management',definition='Gérer le stock détenu sous accord de consignation avec un fournisseur : appliquer les droits, obligations et échéances utiles, suivre les changements de propriété et déclencher les suites autorisées en coordination avec les capacités responsables.',rationale='Responsabilité durable de gestion d’un régime de stock et de ses engagements, distincte du suivi des quantités et des seuls mouvements. Le lien avec les achats est un effet possible, pas son périmètre directeur.',naming='Libellé exact documenté dans Oracle NetSuite ; proposition FLOW, pas intitulé universel des cartographies.',benefit='Distinguer présence physique, propriété, droit d’usage et suites contractuelles ; ne pas perdre les obligations lors d’une vente, d’un incident ou d’une fin de saison.',scope_limit='Cible initiale fournisseur propriétaire / FLOW détenteur. Le besoin de Laurent peut déborder la consignation : un droit de reprise sur stock déjà acheté n’est pas assimilé à ce régime. Ne pas généraliser sans arbitrage.',offer='L’offre proposée au fournisseur assemble un service de gestion de stock, ses conditions et ses suites ; l’offre n’est pas à elle seule une capacité. Les projections Catalog/Agreement/Party peuvent fournir les références utiles sans administration des maîtres ni négociation ajoutée.',decomposition_status='Aucun comportement créé. Les axes ci-dessous précisent le périmètre et ne sont pas une liste d’opérations à transformer automatiquement en comportements.')
    comparison=dict(comparison_ref='CMP147',status='proposed',similarities='Gestion de stock tiers, propriété distincte de la détention, accords et liens avec l’achat et le règlement attestés ; nom Consigned Inventory Management attesté chez NetSuite.',differences='Microsoft montre un sous-processus, SAP des stocks spéciaux et une variante de Procure to Receipt, Oracle un cycle/fonctionnalité. Aucune capacité standard unique couvrant aussi assurance et devenirs de fin de saison n’a été établie.',flow_position='Retrait du candidat achat acquis U391 ; proposer une capacité de gestion du stock dans D01 et relier les autres responsabilités. Nom, définition et découpage nouveaux restent à valider.',source_ids=[s['id'] for s in sources])
    save('modeles/backlog/consignment-inventory-review.yaml',dict(id='CONSIGNED-INVENTORY-REVIEW-U391',as_of='2026-09-18',status='proposed_after_user_reframing',source_refs=['U391','C102','ELM236','CMP147'],user_scope=['Détention du stock et régime de propriété.','Impacts valorisation comptable et facturation.','Responsabilités assurantielles.','Conditions et devenir après saison : soldeur, seconde main, renvoi fournisseur, destruction.','Offre de gestion proposée au fournisseur.'],candidate=candidate,distinctions=['Détenteur physique, propriétaire, droits d’usage et responsabilités sont des dimensions distinctes.','Pas de responsabilité assurantielle ou droit de destruction déduit automatiquement de la propriété ; conditions et autorisations à référencer.','Consignation et pilotage du réassort par le fournisseur (VMI) sont distincts ; ne pas inférer ce dernier.','Les issues de fin de saison sont un besoin FLOW exprimé par Laurent ; couverture complète de ce besoin non établie par les sources consultées.'],responsibility_boundaries=[dict(responsibility='États et mouvements',position='D01.f Inventory Tracking et D01.g Record Inventory Movements conservent quantités, détenteur/propriétaire, mouvements et changements de propriété ; ne pas les recopier dans la capacité candidate.'),dict(responsibility='Accords et droits',position='La capacité consomme les conditions référencées d’Agreement et les applique au stock ; maîtres et négociation restent ailleurs.'),dict(responsibility='Comptabilité, facturation, assurance',position='Fournir faits, références et responsabilités applicables aux fonctions compétentes ; ne pas absorber la valorisation comptable, émission de facture, souscription ou gestion des sinistres.'),dict(responsibility='Choix du devenir après saison',position='Distinguer issues autorisées par l’accord, décision du devenir et exécution. Articulation avec D05 à instruire ; Return Disposition Decision ne couvre pas automatiquement tous les excédents.'),dict(responsibility='Mise en action',position='Mobiliser D04 pour les commandes applicables (vente, retour fournisseur, transfert, achat éventuel), D06 pour les prestations et D01 pour le stock. Un renvoi de stock non acquis ne crée pas automatiquement un avoir.'),dict(responsibility='Offre fournisseur',position='Assemblage commercial de services et conditions ; ne pas imposer l’offre dans D14, dont le rôle courant est l’offre de services exécutants consommés par FLOW.')],market_comparisons=[comparison],sources=sources,catalog_changed=False))
    append('marche/elements.md','''### ELM236

U391 — 18 septembre 2026. Consignation et positionnement du marché. Sources primaires CI-S1–7 dans modeles/backlog/consignment-inventory-review.yaml : Microsoft Inventory to deliver (cartographie de processus, mise à jour July 2026 partielle) et Set up consignment ; SAP Special Stocks (2608, passage indexé) et guide Enterprise Architecture Procure to Receipt (2025, texte indexé, figures non inspectées) ; Oracle Fusion 25D Consigned Inventory, fonctionnalité Redwood 25A et NetSuite Consigned Inventory Management (documentation évolutive).

Localisateurs, URL, constats et limites conservés dans l’annexe. Les formes de preuve diffèrent : sous-processus, variante de parcours, type de stock, cycle fonctionnel et fonctionnalité produit. Aucune feuille de RBA non lue revendiquée, aucune responsabilité juridique ou assurantielle uniforme déduite ; pas de preuve de réalisation Beaumanoir.''')
    append('marche/comparaisons.md','''### CMP147

U391 — Codex, 18 septembre 2026, proposition pour D01 Inventory Management au backlog. ELM236 : rapprochement partiel et appui lexical à Consigned Inventory Management. Microsoft rattache le suivi à un parcours Inventory to deliver relié aux achats ; SAP gère les stocks spéciaux dans Inventory Management mais expose aussi une variante de Procure to Receipt. Oracle Fusion traite le cycle accord/stock/consommation/règlement et NetSuite nomme explicitement Consigned Inventory Management.

Recommandation FLOW : une responsabilité de gestion du régime de stock, proposée sous D01 ; les capacités existantes conservent états, mouvements et visibilité. Le retrait de Consignment Procurement des comportements Purchase Order suit U391/C102. L’acte d’achat/transfert de propriété peut intervenir dans le cycle sans en devenir l’unique finalité.

Le besoin de Laurent porte aussi conditions de responsabilité et devenirs après saison. Les conserver comme exigence FLOW, sans prétendre qu’un unique intitulé de marché les couvre. Finance, assurance, négociation, décisions et exécution restent liées, non absorbées. L’offre au fournisseur assemble plusieurs aptitudes ; pas d’équivalence offre=capacité. Nom et définition candidats à valider ; aucune nouvelle capacité créée.''')
    append('JOURNAL.md','''## 2026-09-18 — U391 : Purchase Order adopté et consignation recadrée

Trois comportements Purchase Order intégrés BHV058–060, preuves et accords préservés. C102 retire la consignation des candidats achat ; analyse Microsoft/SAP/Oracle ELM236/CMP147 et proposition Consigned Inventory Management sous D01, avec frontières stock/accord/finance/assurance/décision/exécution. Aucune création de cette capacité ni publication implicite.''')
    print('Consignment study saved; proposed capability remains outside catalog.')


if __name__=='__main__':
    main()
