"""Record the single Lifecycle alternative, keeping the adopted model intact."""
from hashlib import sha256
from scripts.apply_supplier_return_U387 import ROOT, save, append
from scripts.structured_io import read


def main():
    assert '## U423\n' not in (ROOT/'connaissance/01-contributions-utilisateur.md').read_text(encoding='utf-8')
    digest=sha256((ROOT/'modeles/backlog/model.yaml').read_bytes()).hexdigest()
    append('connaissance/01-contributions-utilisateur.md', '## U423\n\n**id**\n\nU423\n\n**date**\n\n2026-09-19\n\n**titre**\n\nExaminer un Lifecycle décomposé par dimensions d’état\n\n**texte**\n\nOn peut avoir un lifecycle mais avec plusieurs comportements qui représentent les dimensions de l’état ?\n\n**contexte et portée**\n\nQuestion orientant le réexamen vers une capacité Lifecycle unique avec des comportements gouvernant des dimensions métier distinctes. Ne vaut pas adoption de noms, regroupements, liste de statuts ou nouvelles définitions. L’option de scission U422 est conservée comme alternative de travail non adoptée. Le catalogue courant U420 reste intact.')
    review=read(ROOT/'modeles/backlog/order-backlog-review.yaml')
    review['lifecycle_redesign_U422']['status']='alternative_not_preferred_after_U423'
    dims=[
        dict(dimension='Maturité et révision de la demande',responsibility='Gouverner la préparation et la prise d’effet des versions et modifications du besoin.',existing_behaviors=['BHV038','BHV041'],note='Drafting et changement de date du besoin ; révision contrôlée à préciser sans créer une machine d’état universelle.'),
        dict(dimension='Engagement',responsibility='Transformer une intention planifiée en ordre ferme selon le type d’Order.',existing_behaviors=['BHV036']),
        dict(dimension='Protection contre la réoptimisation',responsibility='Définir et appliquer les éléments gelés et les conditions de leur révision.',existing_behaviors=['BHV037']),
        dict(dimension='Autorisation de prise en charge',responsibility='Autoriser le traitement d’une part de demande, individuellement ou collectivement.',existing_behaviors=['BHV039']),
        dict(dimension='Suspension de la progression',responsibility='Suspendre et réautoriser une progression désignée avec son motif et sa portée.',existing_behaviors=['BHV040']),
        dict(dimension='Fin de la demande opérationnelle',responsibility='Distinguer retrait du besoin et clôture, en préservant faits et engagements acquis.',existing_behaviors=['BHV042','BHV043'],note='Regroupement descriptif à arbitrer ; aucune fusion implicite de Cancellation et Closure.')]
    review['lifecycle_dimensions_U423']=dict(status='proposed',source_refs=['U421','U422','U423','ELM250','CMP161'],preferred_direction='Conserver une capacité Order Lifecycle Management ; revoir ses comportements par dimension métier plutôt que déplacer la capacité entière ou créer un comportement pour chaque état.',definition_proposed='Gouverner les évolutions autorisées des Orders selon leurs dimensions de maturité, d’engagement, de protection et de prise en charge, en préservant la cohérence entre contenu applicable, modifications en préparation et réalisations acquises.',dimension_examples=dims,benefit='Rendre possible une commande engagée et partiellement libérée dont une modification se prépare, sans confondre autorisation, suspension, protection et réalisation.',boundaries=['Le domaine courant de Lifecycle reste D04. Une capacité et ses comportements gardent un parent unique ; ils ne sont pas distribués artificiellement entre D03 et D04.', 'D03 mobilise les comportements de Lifecycle pour mettre en action le scénario retenu. Ce lien de responsabilité ne présume pas un composant logiciel mutualisé.', 'Les politiques, décisions et calculs de D03 restent distincts des transitions appliquées par Lifecycle.', 'D06 orchestre les services et fournit les faits de réalisation ; une autorisation ne prouve pas un démarrage.', 'Order Archiving et Order Structuring restent distincts en D03, conformément aux choix acquis.', 'Un tableau de dimensions ne vaut pas liste de comportements adoptée ; aucune sous-décomposition, duplication ni fusion implicite.', 'Les contraintes entre dimensions s’apprécient par type, version, ligne et quantité. Une révision ne permet pas de réécrire les réalisations acquises.'],market_comparisons=[dict(vendor='Microsoft',product='Dynamics 365 Supply Chain Management',title='Purchase order overview',url='https://learn.microsoft.com/en-us/dynamics365/supply-chain/procurement/purchase-order-overview',version='2026-09-08',locator='Purchase order statuses',consulted_on='2026-09-19',finding='Purchase order status, Document status et Approval status coexistent sur une commande.',relationship='Appui méthodologique',limits='Données et processus produit : ne prouvent pas une capacité Microsoft découpée selon nos dimensions.'),dict(vendor='Microsoft',product='Dynamics 365 Intelligent Order Management',title='State framework architecture',url='https://learn.microsoft.com/en-us/dynamics365/intelligent-order-management/state-framework',version='2026-01-30',locator='Entity State and State Reason columns ; State Transition table',consulted_on='2026-09-19',finding='États, motifs et transitions sont explicités ; la possibilité de modification est représentée par ReadOnly.',relationship='Appui méthodologique',limits='Documentation avec réserve de préversion ; framework de réalisation et non cartographie business. Aucune indépendance absolue des dimensions démontrée.')],catalogue_unchanged=True,catalogue_sha256=digest)
    review['source_refs']=list(dict.fromkeys(review['source_refs']+['U423','ELM250','CMP161']))
    review['status']='lifecycle_dimensions_proposed_U423'
    review['next_arbitration']='Préciser la décomposition par dimensions sous Lifecycle unique ; aucune scission ni liste de nouveaux comportements validée.'
    save('modeles/backlog/order-backlog-review.yaml',review)
    ann=read(ROOT/'modeles/backlog/order-lifecycle-behaviors.yaml')
    ann['review_U423']=dict(status='proposed',source_refs=['U423'],proposal_ref='modeles/backlog/order-backlog-review.yaml#lifecycle_dimensions_U423',note='Piste préférée : Lifecycle unique et comportements gouvernant les dimensions métier. Option de scission U422 non adoptée ; U420 reste le catalogue courant.')
    save('modeles/backlog/order-lifecycle-behaviors.yaml',ann)
    agents=ROOT/'AGENTS.md';text=agents.read_text(encoding='utf-8')
    text=text.replace('U422 demande le réexamen ciblé de Lifecycle ; noms et répartition proposés dans `order-backlog-review.yaml`, `lifecycle_redesign_U422`, non adoptés.', 'U422 demande le réexamen ciblé de Lifecycle ; U423 explore une capacité unique avec des comportements par dimension métier. Piste courante proposée : `order-backlog-review.yaml`, `lifecycle_dimensions_U423` ; la scission U422 est une alternative non adoptée. Aucun nom ni regroupement de comportements validé par ces échanges.')
    agents.write_text(text,encoding='utf-8')
    append('marche/elements.md','### ELM250\n\nMicrosoft — Purchase order overview (Dynamics 365 SCM, 8 septembre 2026, Purchase order statuses) et State framework architecture (Intelligent Order Management, 30 janvier 2026, colonnes d’état et transitions, réserve de préversion). Pages primaires consultées le 19 septembre 2026. URL et limites dans modeles/backlog/order-backlog-review.yaml, lifecycle_dimensions_U423.market_comparisons. Plusieurs dimensions sur un Order et gouvernance des transitions ; éléments de données/framework, pas capacités d’entreprise.')
    append('marche/comparaisons.md','### CMP161\n\nU423 — Une capacité Lifecycle unique peut gouverner plusieurs dimensions métier par ses comportements. Appui méthodologique Microsoft ELM250 ; aucune taxonomie équivalente revendiquée. Préserver le parent D04 dans cette piste et rendre explicite la mobilisation par D03 ; D06 conserve les réalisations. Le tableau des dimensions est exploratoire, sans fusion ni création de comportement. La scission CMP160 reste une alternative non adoptée. Proposition Codex, non validée.')
    assert digest==sha256((ROOT/'modeles/backlog/model.yaml').read_bytes()).hexdigest()
    print('U423 alternative recorded; catalogue unchanged.')


if __name__=='__main__':main()
