import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require('C:/Users/laure/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
page.setDefaultTimeout(15000);
const base = 'http://127.0.0.1:8765';
const checks = [], errors = [];
page.on('pageerror', e => errors.push(e.message));
const goto = async hash => { await page.goto(base + '/#' + hash); await page.locator('#page-title').waitFor(); };
const shot = name => page.screenshot({ path: fileURLToPath(new URL(name + '.png', import.meta.url)), fullPage: false });
try {
  const model = await (await page.request.get(base + '/api/model')).json();
  const expected = model.relations.filter(r => r.type === 'contains' && r.source_id === 'D04.j')
    .map(r => model.nodes.find(n => n.id === r.target_id)).filter(n => n.kind === 'behavior').map(n => n.fields.name);
  await goto('node=universe-supply&view=map');
  const capacity = page.locator('.capacity-link[href*="node=D04.j"]');
  await capacity.waitFor(); await capacity.hover();
  const tip = page.getByRole('tooltip');
  await tip.waitFor();
  assert.deepEqual(await tip.locator('.tooltip-behaviors li').allTextContents(), expected);
  assert.ok((await tip.innerText()).includes(model.nodes.find(n => n.id === 'D04.j').fields.definition));
  assert.ok(await tip.evaluate(el => { const r = el.getBoundingClientRect(); return r.top >= 0 && r.bottom <= innerHeight + 1; }));
  await shot('universe-tooltip');
  assert.equal(await tip.count(), 1);
  await page.keyboard.press('Escape');
  assert.equal(await tip.count(), 0);
  await capacity.focus(); await tip.waitFor();
  assert.deepEqual(await tip.locator('li').allTextContents(), expected);
  await page.keyboard.press('Escape');
  const leaf = page.locator('.capacity-link[href*="node=D04.q"]');
  await leaf.hover(); await tip.waitFor();
  assert.equal(await tip.locator('.tooltip-behaviors').count(), 0);
  checks.push('Vue univers : définition et comportements explicites à puces, survol et focus clavier, Échap et capacité sans comportement.');
  await goto('node=D04.j&view=sheet');
  await page.getByRole('button', { name: 'Marché', exact: true }).click();
  assert.equal(await page.evaluate(() => document.activeElement.id), 'field-D04.j-market_comparisons');
  const section = page.locator('#field-D04\\.j-market_comparisons');
  assert.equal(await section.locator('.market-card').count(), model.nodes.find(n => n.id === 'D04.j').fields.market_comparisons.length);
  const card = section.locator('.market-card').first();
  await card.locator(':scope > summary').click();
  assert.ok((await card.innerText()).includes('Choix du modèle FLOW'));
  await card.locator('.market-evidence > summary').click();
  assert.ok((await card.locator('a[target="_blank"]').getAttribute('href')).startsWith('https://'));
  assert.doesNotMatch(await section.innerText(), /\bU\d+\b|\bCMP\d+\b|\bELM\d+\b/);
  assert.equal(await page.locator('.market-status,.source-link,.lifecycle-badge').count(), 0);
  await section.evaluate(el => el.scrollIntoView({ block: 'start', behavior: 'instant' }));
  await shot('market-position');
  checks.push('Repères marché : positionnement, choix FLOW, écarts et source externe ; aucun statut de revue ni lien backlog affiché.');
  await goto('node=D08&view=sheet');
  assert.ok((await page.locator('.market-comparisons').innerText()).includes('Positionnement non documenté'));
  await goto('view=glossary&term=TER070&section=short-description');
  await page.locator('#term-TER070-definition').waitFor();
  assert.equal(await page.getByRole('heading', { name: 'En quelques mots', exact: true }).count(), 0);
  await page.waitForFunction(() => document.activeElement.id === 'term-TER070-definition');
  const comparedTerm = model.glossary.terms.find(t => t.market_comparisons?.length);
  await goto('view=glossary&term=' + comparedTerm.id);
  await page.locator('#term-' + comparedTerm.id).waitFor();
  assert.equal(await page.locator('.market-card').count(), comparedTerm.market_comparisons.length);
  const search = page.getByRole('textbox', { name: 'Rechercher dans le modèle publié' });
  await search.fill('RELEX');
  await page.locator('[data-search-result]').first().waitFor();
  checks.push('Glossaire sans doublon, ancien lien vers la définition, comparaisons du terme et recherche par référence marché.');
  await page.setViewportSize({ width: 390, height: 844 });
  await goto('node=D04.j&view=sheet');
  await page.locator('.market-comparisons').waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.locator('.market-card > summary').first().click();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await shot('mobile-market');
  checks.push('390 px : sommaire et comparaisons dépliables sans débordement horizontal.');
  assert.deepEqual(errors, []);
  const report = { version: model.version, checks, errors, behaviors: expected };
  await writeFile(new URL('browser-verification.json', import.meta.url), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} catch (error) { await shot('failure'); console.error(JSON.stringify({url:page.url(),errors})); throw error; }
finally { await browser.close(); }
