import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
const require = createRequire(import.meta.url);
const { chromium } = require('C:/Users/laure/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base = 'http://127.0.0.1:8765';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const result = { checks: [], errors: [], measurements: {} };
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
page.setDefaultTimeout(12000);
page.on('pageerror', e => result.errors.push(e.message));
const screenshot = name => page.screenshot({ path: fileURLToPath(new URL(name + '.png', import.meta.url)), fullPage: true });
const goto = async hash => { await page.goto(base + '/#' + hash); await page.locator('#page-title').waitFor(); };
try {
  const model = await (await page.request.get(base + '/api/model')).json();
  result.version = model.version;
  await goto('node=D04.j&view=sheet');
  await page.locator('.business-sheet').waitFor();
  result.measurements.purchase = await page.locator('.business-sheet').evaluate(el => ({ height: el.scrollHeight, scopeTop: document.getElementById('field-D04.j-scope').getBoundingClientRect().top, parentTop: el.querySelector('.sheet-parent').getBoundingClientRect().top }));
  assert.equal(await page.locator('.market-comparisons, .source-link, .lifecycle-badge').count(), 0);
  assert.equal(await page.locator('.behavior-summary[open]').count(), 0);
  await screenshot('purchase-sheet');
  await page.getByRole('button', { name: 'Périmètre', exact: true }).click();
  assert.equal(await page.evaluate(() => document.activeElement.id), 'field-D04.j-scope');
  await page.locator('.sheet-disclosure summary').click();
  assert.ok((await page.locator('.sheet-disclosure .business-copy').innerText()).length > 750);
  result.checks.push('Périmètre complet accessible, raccourci avec focus et comportements repliés.');
  const search = page.getByRole('textbox', { name: 'Rechercher dans le modèle publié' });
  await search.fill('Purchase Order');
  await page.locator('[data-search-result]').first().waitFor();
  assert.equal(await page.locator('[data-search-result]').first().getAttribute('data-search-result'), 'D04.j');
  result.measurements.exactSearchCount = await page.locator('[data-search-result]').count();
  await search.press('ArrowDown');
  assert.equal(await page.evaluate(() => document.activeElement.dataset.searchResult), 'D04.j');
  await search.fill('bon de commande');
  await page.waitForFunction(() => document.querySelector('.search-results')?.textContent.includes('0 résultat'));
  result.measurements.missingPublishedTerm = 'Bon de commande absent de v010 : ajout lexical préparé dans le backlog, aucun repli.';
  await search.fill('commande d’achat');
  await page.waitForFunction(() => document.querySelector('.search-results')?.textContent.includes('Terme du glossaire'));
  assert.equal(await page.locator('[data-search-result]').first().getAttribute('data-search-result'), 'TER070');
  result.measurements.frenchSearch = await page.locator('.search-results').innerText();
  await screenshot('french-search');
  await page.locator('[data-search-result="TER070"]').click();
  await page.locator('.glossary-term').waitFor();
  assert.ok(page.url().includes('view=glossary'));
  assert.ok(page.url().includes('version=' + model.version));
  assert.equal(await page.locator('.market-comparisons').count(), 0);
  result.checks.push('Purchase Order en premier, résultat français du glossaire, clavier et version conservée.');
  await goto('node=D04.j&view=relations');
  await page.locator('.dependency-summary').waitFor();
  result.measurements.directRelations = await page.locator('.dependency-summary').innerText();
  await page.locator('.dependency-options > summary').click();
  await page.getByRole('combobox', { name: 'Liens entre voisins' }).selectOption('all');
  await page.waitForURL(/neighbors=all/);
  result.measurements.extendedRelations = await page.locator('.dependency-summary').innerText();
  await page.goBack();
  await page.waitForFunction(() => !location.hash.includes('neighbors=all'));
  assert.equal(await page.getByRole('combobox', { name: 'Liens entre voisins' }).inputValue(), 'direct');
  await page.locator('.dependency-options > summary').click();
  await screenshot('direct-relations');
  result.checks.push('Liens directs par défaut, liens entre voisins explicites, retour navigateur conservé.');
  await goto('view=relations');
  await page.locator('.dependency-summary').waitFor();
  assert.equal(await page.getByRole('combobox', { name: 'Niveau de lecture' }).inputValue(), 'domain');
  await goto('view=principles');
  await page.locator('.guide-lesson').waitFor();
  assert.equal(await page.locator('.guide-realization-controls, .guide-realization-output').count(), 0);
  result.checks.push('Guide de la publication conservé ; simulateur de réalisations logicielles retiré.');
  await goto('view=glossary&glossary=meta&term=MOD006');
  await page.locator('#term-MOD006').waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await screenshot('mobile-glossary');
  await goto('node=D04.j&view=sheet');
  await page.locator('.business-sheet').waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await screenshot('mobile-sheet');
  await page.setViewportSize({ width: 720, height: 450 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await screenshot('reflow-sheet');
  result.checks.push('Absence de débordement horizontal à 390 px et repli à 720 × 450 ; glossaire mobile accessible.');
  // Isolated future-publication fixture: never served to users or substituted into the live snapshot.
  const draft = JSON.parse(execFileSync('python', ['-c', "import json;from pathlib import Path;from scripts.structured_io import read;print(json.dumps({'guide':read(Path('modeles/backlog/modeling-guide-U458.yaml')),'term':next(t for t in read(Path('modeles/backlog/glossary.yaml'))['terms'] if t['id']=='TER086')},ensure_ascii=True))"], { cwd: fileURLToPath(new URL('../../', import.meta.url)), windowsHide: true, encoding: 'utf8' }));
  const fixture = structuredClone(model);
  fixture.glossary.terms.push(draft.term);
  await page.route('**/api/model?*', route => route.fulfill({ json: fixture }));
  await page.route('**/api/model', route => route.fulfill({ json: fixture }));
  await page.route('**/api/modeling-guide?*', route => route.fulfill({ json: { schema_version: '1.0.0', status: 'available', publication_version: model.version, message: 'Fixture du brouillon futur.', guide: draft.guide } }));
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.reload();
  await search.fill('bon de commande');
  await page.locator('[data-search-result="TER086"]').waitFor();
  await page.locator('[data-search-result="TER086"]').click();
  await page.locator('#term-TER086').waitFor();
  assert.equal(await page.locator('#term-TER086 a[href*="node=D04.j"]').count(), 1);
  await page.locator('#term-TER086 a[href*="node=D04.j"]').click();
  await page.locator('.business-sheet').waitFor();
  assert.ok(page.url().includes('node=D04.j'));
  await goto('view=principles');
  await page.getByRole('heading', { name: 'Des responsabilités métier qui coopèrent' }).waitFor();
  assert.equal(await page.locator('.guide-topics > button').count(), 6);
  await screenshot('guide-draft-fixture');
  result.checks.push('Fixture isolée du futur contenu : bon de commande → document → Purchase Order ; six repères du nouveau guide. Aucune publication effectuée.');
  assert.deepEqual(result.errors, []);
  await writeFile(new URL('browser-verification.json', import.meta.url), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result, null, 2));
} catch (error) {
  await screenshot('failure');
  console.error(JSON.stringify({ ...result, url: page.url(), text: (await page.locator('body').innerText()).slice(-1200) }));
  throw error;
} finally { await browser.close(); }
