import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require=createRequire(import.meta.url);
const {chromium}=require(process.env.ATLAS_PLAYWRIGHT_PATH || 'C:/Users/laure/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.env.ATLAS_URL || 'http://127.0.0.1:8765';
const output=path.join(path.dirname(fileURLToPath(import.meta.url)),'.runtime','qa-json');
await mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
  const context=await browser.newContext({viewport:{width:1360,height:1100}});
  const page=await context.newPage(); const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);
  await page.getByRole('heading',{name:'Socle transactionnel',exact:true}).waitFor();
  assert.equal(await page.locator('#fa-space').inputValue(),'backlog');
  assert.match(page.url(),/space=backlog/);
  assert.equal(await page.locator('.fa-nav[data-journey="start"]:visible').count(),1);
  await page.screenshot({path:path.join(output,'backlog-initial.png'),fullPage:true});
  await page.goto(base+'/#space=release&node=transactional');
  await page.getByRole('heading',{name:'Socle transactionnel',exact:true}).waitFor();
  assert.equal(await page.locator('#fa-space').inputValue(),'release');
  assert.equal(await page.locator('.fa-grid .fa-tile').count(),7);
  assert.equal(await page.locator('.fa-ref-chips button').count(),5);
  assert.equal(await page.locator('[data-journey="start"]:visible').count(),0);
  await page.screenshot({path:path.join(output,'release.png'),fullPage:true});
  await page.locator('.fa-grid [data-go="D01"]').click();
  assert.match(await page.locator('.fa-inspector').innerText(),/Champs proposés, à valider/);
  assert.equal(await page.locator('.fa-grid .fa-tile').count(),6);
  await page.locator('.fa-grid [data-go="D02.c"]').click();
  assert.match(await page.locator('.fa-inspector').innerText(),/rattachement retenu U75, réexaminé U78/i);
  await page.locator('.fa-nav[data-go="transactional"]').click();
  await page.locator('.fa-ref-chips [data-go="D08"]').click();
  assert.equal(await page.locator('h1').innerText(),'Product Reference');
  assert.match(await page.locator('.fa-inspector').innerText(),/Champs proposés, à valider/);
  await page.locator('.fa-nav[data-go="transactional"]').click();
  await page.locator('.fa-grid [data-go="D03"]').click();
  assert.equal(await page.locator('.fa-grid .fa-tile').count(),9);
  await page.locator('.fa-grid [data-go="D03.b"]').click();
  await page.locator('.fa-source button').filter({hasText:/^U95$/}).click();
  await page.locator('#fa-source-dialog').getByRole('heading',{name:'U95',exact:true}).waitFor();
  await page.locator('#fa-close-source').click();
  const releaseURL=page.url();
  await page.locator('#fa-space').selectOption('backlog');
  await page.getByRole('heading',{name:'Socle transactionnel',exact:true}).waitFor();
  assert.equal(await page.locator('.fa-grid .fa-tile').count(),7);
  assert.match(page.url(),/space=backlog/);
  await page.locator('#fa-search').fill('affectation');
  await page.locator('.fa-result[data-go="D02.e"]').waitFor();
  await page.locator('.fa-result[data-go="D02.e"]').click();
  assert.match(await page.locator('#fa-breadcrumb').innerText(),/Order Promising/);
  await page.locator('.fa-nav[data-journey="start"]').click();
  assert.equal(await page.locator('.fa-related').count(),3);
  await page.locator('.fa-related[data-go="ILL-DOC-01"]').click();
  await page.reload();
  await page.getByRole('heading',{name:'Confirmation de promesse',exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'backlog-relations.png'),fullPage:true});
  await page.locator('#fa-space').selectOption('panorama-as-is');
  await page.getByRole('heading',{name:'Panorama As Is',exact:true}).waitFor();
  assert.equal(await page.locator('.fa-grid .fa-tile').count(),4);
  await page.locator('.fa-grid [data-go="sarenza-si"]').click();
  assert.match(await page.locator('#fa-content').innerText(),/non traité/i);
  assert.equal(await page.locator('.fa-grid .fa-tile').count(),0);
  await page.screenshot({path:path.join(output,'sarenza-non-traite.png'),fullPage:true});
  await page.locator('.fa-nav[data-go="panorama"]').click();
  await page.locator('.fa-grid [data-go="beaumanoir-historique-si"]').click();
  await page.locator('.fa-grid [data-go="beaumanoir-historique-si:objects"]').click();
  await page.locator('.fa-grid [data-go="APP-STR"]').click();
  assert.match(await page.locator('.fa-inspector').innerText(),/Déclaré/);
  assert.match(await page.locator('.fa-inspector').innerText(),/Storeland|Stock magasin/);
  await page.goto(releaseURL);
  await page.getByRole('heading',{name:'Promise Confirmation',exact:true}).first().waitFor();
  assert.equal(await page.locator('#fa-space').inputValue(),'release');
  await page.locator('#fa-space').selectOption('backlog');
  await page.getByRole('heading',{name:'Socle transactionnel',exact:true}).waitFor();
  await page.goBack();
  await page.getByRole('heading',{name:'Promise Confirmation',exact:true}).first().waitFor();
  assert.equal(await page.locator('#fa-space').inputValue(),'release');
  for (const width of [1360,768,375]) {
    await page.setViewportSize({width,height:1000});
    await page.screenshot({path:path.join(output,`release-${width}.png`),fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  }
  // A link without a space follows the exploration default even from Release.
  await page.goto(base+'/#node=D03.b');
  await page.getByRole('heading',{name:'Promise Confirmation',exact:true}).first().waitFor();
  assert.equal(await page.locator('#fa-space').inputValue(),'backlog');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({checks:'default-backlog/explicit-release/backlog/panorama/source/history/search/relations/mobile',errors,screenshots:output}));
} finally { await browser.close(); }
