// Isolated candidate preview only: no server mutation, publication or visible browser.
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {loadPublication} from '../../scripts/load-publication.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/laure/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=fileURLToPath(new URL('../../',import.meta.url)),dist=resolve(root,'app/dist');
const output=resolve(root,'audits/2026-09-19-informations-atlas-U468/browser',new Date().toISOString().replace(/[:.]/g,'-'));
await mkdir(output,{recursive:true});
const fixture=JSON.parse(execFileSync('python',['-X','utf8','-c',"import json;from scripts.prepare_release import build_candidate;b=build_candidate(version='2099-09-19.1',source_refs=['U468']);assert not b['report']['validation_errors'];print(json.dumps(b['candidate'],ensure_ascii=True))"],{cwd:root,encoding:'utf8',windowsHide:true,maxBuffer:24*1024*1024}));
const old=(await loadPublication({version:'2026-09-19.4'})).raw;
const browser=await chromium.launch({channel:'msedge',headless:true}),checks=[],errors=[];
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
const noOverflow=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
const shot=name=>page.screenshot({path:resolve(output,name+'.png'),fullPage:false});
const visit=async(params={})=>{await page.goto('http://atlas.test/#'+new URLSearchParams({version:fixture.version,view:'information',...params}));await page.locator('#page-title').waitFor();};
const current=async id=>{await page.locator(`[data-information-id="${id}"]`).waitFor();};
try {
  await page.route('**/*',async route=>{
    const url=new URL(route.request().url());
    if(url.origin!=='http://atlas.test')return route.abort();
    if(url.pathname==='/api/releases')return route.fulfill({json:{current_version:fixture.version,versions:[{version:fixture.version},{version:old.version}]}});
    if(url.pathname==='/api/model')return route.fulfill({json:url.searchParams.get('version')===old.version?old:fixture});
    if(url.pathname==='/api/modeling-guide')return route.fulfill({json:{schema_version:'1.0.0',publication_version:url.searchParams.get('version'),status:'unavailable',message:'Fixture isolée.'}});
    const path=resolve(dist,'.'+(url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname)));
    if(!path.startsWith(dist+sep))return route.abort();
    try{return route.fulfill({body:await readFile(path),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'})[extname(path)]||'application/octet-stream'});}
    catch{return route.fulfill({status:404,body:'Not found'});}
  });
  await visit({view:'map'});
  await page.getByRole('button',{name:'Informations métier',exact:true}).click();
  await current('PINFO-001');assert.equal(await page.locator('.information-index li').count(),14);
  assert.equal(await page.locator('.information-detail .example-card').count(),1);await noOverflow();
  await shot('catalogue-desktop');checks.push('Navigation directe, 14 informations et exemple en première lecture.');
  const detail=page.locator('.information-detail'),index=page.locator('.information-index');
  await detail.evaluate(el=>el.scrollTop=500);const top=await detail.evaluate(el=>el.scrollTop);
  await index.evaluate(el=>el.scrollTop=400);assert.equal(await detail.evaluate(el=>el.scrollTop),top);
  await page.locator('.information-index a').filter({hasText:'Supplier Response'}).click();await current('PINFO-002');
  assert.equal(await detail.evaluate(el=>el.scrollTop),0);checks.push('Défilements indépendants ; une sélection ouvre la fiche depuis son début.');
  await page.getByRole('tab',{name:'Fiche',exact:true}).focus();await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('tab',{name:'Marché & choix',exact:true}).getAttribute('aria-selected'),'true');
  assert.ok(await page.locator('.market-source a').first().isVisible());await shot('marche-desktop');
  await page.keyboard.press('Home');assert.equal(await page.getByRole('tab',{name:'Fiche',exact:true}).getAttribute('aria-selected'),'true');
  checks.push('Onglets accessibles au clavier et sources marché directement visibles.');
  await visit({view:'sheet',node:'D04.j'});
  const purchaseCount=fixture.information_catalog.items.filter(i=>i.capability_roles.some(r=>r.capability_ref==='D04.j')).length;
  assert.equal(await page.locator('.sheet-information-list a').count(),purchaseCount);
  await page.locator('.sheet-information-list a').filter({hasText:'Supplier Commitment'}).click();await current('PINFO-003');
  assert.equal(await page.locator('.information-index li').count(),purchaseCount);
  assert.match(page.url(),/node=D04.j/);assert.match(page.url(),/version=2099-09-19.1/);
  await page.locator('.information-roles a').filter({hasText:'Purchase Order'}).click();
  assert.match(page.url(),/view=sheet/);assert.match(page.url(),/version=2099-09-19.1/);
  checks.push(`Purchase Order : ${purchaseCount} informations utilisées, filtre de périmètre, aller-retour fixé à la version.`);
  await visit({information:'PINFO-011'});await current('PINFO-011');
  await page.locator('.information-links a').filter({hasText:'Fulfillment Commitment'}).first().click();await current('PINFO-012');
  await page.locator('.information-links summary').first().click();
  assert.match(await page.locator('.information-links details[open]').innerText(),/Condition.*Effet métier/s);
  checks.push('Lien proposition → engagement et qualifications consultables.');
  await page.getByRole('textbox',{name:'Rechercher dans le modèle publié'}).fill('Supplier Response');
  await page.locator('[data-search-result="PINFO-002"]').click();await current('PINFO-002');
  await page.getByRole('combobox',{name:'Type d’élément'}).selectOption('information');
  assert.equal(await page.locator('[data-search-result]').count(),14);
  await page.getByRole('button',{name:'Effacer la recherche et les filtres'}).click();
  checks.push('Recherche globale et filtre Information : identité distincte de celle des capacités.');
  for(const item of fixture.information_catalog.items){
    await visit({information:item.id});await current(item.id);
    await page.locator('.information-detail details').evaluateAll(list=>list.forEach(el=>el.open=true));
    assert.doesNotMatch(await detail.innerText(),/\bU\d{3}\b|\bCMP\d+\b|\bELM\d+\b|V0-P|modeles\/backlog|state: proposed/);
    await page.getByRole('tab',{name:'Marché & choix',exact:true}).click();
    await page.locator('.market-detail').evaluateAll(list=>list.forEach(el=>el.open=true));
    assert.doesNotMatch(await detail.innerText(),/\bU\d{3}\b|\bCMP\d+\b|\bELM\d+\b|V0-P|modeles\/backlog/);
    assert.equal(await page.locator('.market-source a').count(),item.market_comparisons.length);
  }
  checks.push('14 fiches et 16 références : contenus, liens sources et absence de références internes affichées.');
  await page.setViewportSize({width:390,height:844});await visit({information:'PINFO-011'});await current('PINFO-011');await noOverflow();
  await detail.scrollIntoViewIfNeeded();await shot('catalogue-mobile');
  await page.getByRole('tab',{name:'Marché & choix',exact:true}).click();await noOverflow();
  checks.push('390 px : liste et fiche empilées, aucun débordement horizontal.');
  await page.setViewportSize({width:720,height:500});await visit({information:'PINFO-012'});await current('PINFO-012');await noOverflow();
  checks.push('720 px, surface réduite équivalente à un zoom 200 % : contenu accessible.');
  await page.setViewportSize({width:1440,height:1000});await visit({information:'ABSENT'});
  await page.getByRole('heading',{name:'Information absente de cette publication',exact:true}).waitFor();
  await visit({version:old.version,information:'PINFO-012'});
  await page.getByRole('heading',{name:'Informations non publiées dans cette version',exact:true}).waitFor();
  assert.equal(await page.locator('.information-detail').count(),0);
  checks.push('Information inconnue et v011 sans catalogue : absence explicite, aucun repli backlog.');
  assert.deepEqual(errors,[]);
  await writeFile(resolve(output,'checks.json'),JSON.stringify({fixture:fixture.version,notPublished:true,checks,errors},null,2));
  console.log(JSON.stringify({output,checks,errors},null,2));
} finally {await browser.close();}
