"""One-shot, reviewable U470/U471 editorial migration; never edits a publication."""
from pathlib import Path
import json, sys
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from scripts.structured_io import read, dumps, write_text_if_changed

HERE = Path(__file__).parent
sources = {}
def source(key, vendor, product, title, url, version, locator, mkt, nature='Fonction produit documentée'):
    sources[key] = dict(id=f'ELM{292 + len(sources)}', vendor=vendor, product=product,
        source_title=title, source_url=url, source_version=version, source_locator=locator,
        market_ref=mkt, element_type=nature, consulted_on='2026-09-19')

MS='Microsoft'; OR='Oracle'; SCM='Dynamics 365 Supply Chain Management'
EV='Documentation évolutive ; état consulté le 19 septembre 2026'
source('cscmp','CSCMP','Définitions professionnelles','SCM Definitions and Glossary of Terms','https://cscmp.org/CSCMP/Educate/SCM_Definitions_and_Glossary_of_Terms.aspx','Page sans édition affichée','Definition of Supply Chain Management ; Boundaries and Relationships','MKT41','Définition professionnelle')
source('scm',MS,SCM,'Welcome to Dynamics 365 Supply Chain Management','https://learn.microsoft.com/en-us/dynamics365/supply-chain/supply-chain-management-welcome','Page mise à jour le 10 septembre 2025','Core concepts and tasks','MKT14','Périmètre de produit')
source('orchestration',OR,'Fusion Cloud Supply Chain Orchestration','Overview of Supply Chain Orchestration','https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/26b/fauco/overview-of-supply-orchestration.html','26B','Introduction ; receive requests, create supply orders, manage changes ; drop shipment','MKT20')
source('batch',OR,'Fusion Cloud Product Hub','Overview of Item Batches','https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/26a/fapim/overview-of-item-batches.html','26A','Introduction et options des lots d’import','MKT20')
source('journals',MS,SCM,'Inventory journals','https://learn.microsoft.com/en-us/dynamics365/supply-chain/inventory/inventory-journals','Page mise à jour le 29 août 2025','Types of inventory journals : Transfer, Item arrival, Counting','MKT14')
source('supplydemand',OR,'Fusion Cloud Inventory Management','How You Review Item Supply and Demand','https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/25d/famml/how-you-review-item-supply-and-demand.html','25D','Supply and demand ; quantities and dates ; ATP/nettable filters','MKT20')
source('pal','SAP','S/4HANA aATP','Explaining aATP Product Allocation (PAL)','https://learning.sap.com/courses/exploring-fashion-functions-and-business-processes-in-sap-s-4hana-for-fashion-and-vertical-business/explaining-aatp-product-allocation-pal-_dd30c229-d63f-4aba-a950-a174280c4a58','Cours évolutif sans édition affichée','aATP: PAL Concept ; scénario ; restrictions par groupes de demande','MKT13')
source('reservation',OR,'Fusion Cloud Inventory Management','Reservations','https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/25c/famml/reservations.html','25C','Introduction ; supply and demand documents ; restriction des prélèvements concurrents','MKT20')
source('ps',OR,'PeopleSoft Inventory','Promising and Reserving Inventory','https://docs.oracle.com/cd/E13228_01/fscm9pbr0/eng/psbooks/sinv/htm/sinv18.htm','PeopleSoft FSCM 9.0, édition historique','Reservation lead days ; ATP ; inventory priority rules ; shortage workbench','MKT20')
source('ptp',OR,'Fusion Cloud Global Order Promising','Database Promising','https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/25c/fascp/overview-of-database-centric-order-promising.html','25C','Profitable to Promise','MKT20')
source('schedules',MS,SCM,'Delivery schedules','https://learn.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/delivery-schedules',EV,'Create delivery schedules ; Manage delivery lines','MKT14')
source('plans',MS,SCM,'Master plans overview','https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/master-plans',EV,'Master plans ; Firming time fence ; Action message time fence','MKT14')
source('workload',MS,SCM,'Schedule workload capacity','https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/schedule-workload-capacity',EV,'Warehouse workload capacity ; volume, weight, inbound/outbound workload','MKT14')
source('tmf','TM Forum','Service Ordering','TMF641 Service Ordering API REST Specification R18.5.1','https://www.tmforum.org/resources/specification/tmf641-service-ordering-api-rest-specification-r18-5-0/','R18.5.1 ; document 4.0.1, 2019 ; version archivée','Présentation publique : create, update, retrieve ; service order items','MKT19','Concept documenté par un contrat sectoriel')
source('carrier',MS,'Dynamics AX Transportation Management','Transportation scenario – Manual rating','https://www.microsoft.com/en-us/dynamics-365/blog/business-leader/2016/02/16/transportation-charges-scenario-manual-rating-2/','Publication officielle du 16 février 2016 ; exemple historique','Load planning workbench : Shipping carrier et Carrier service ; Manual rating','MKT14')
source('spot',OR,'E-Business Suite Warehouse Management','Oracle Warehouse Management User’s Guide','https://docs.oracle.com/cd/E26401_01/doc.122/e48830/T211976T430466.htm','EBS 12.2','Opportunistic Cycle Counting','MKT20')
source('pegging',MS,SCM,'Keep supply for confirmed demand in Planning Optimization','https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/keep-supply-for-confirmed-demand','SCM 10.0.48 build 10.0.2645.33+ selon la page','What data is preserved ; Control how on-hand inventory is pegged to confirmed demand','MKT14')
source('repair',MS,'Dynamics GP Returns Management','Returns Management','https://learn.microsoft.com/en-us/dynamics-gp/distribution/returnsmanagement','Guide Dynamics GP ; édition produit non précisée dans le passage','RTV types : Repair and Return ; Enter a repair and return RTV ; Receive an RTV','MKT14')
source('po',OR,'E-Business Suite Purchasing','Oracle Purchasing User’s Guide','https://docs.oracle.com/cd/E26401_01/doc.122/e48931/T446883T443953.htm','EBS 12.2','Standard Purchase Orders ; quantités et échéances de livraison','MKT20')
source('ubl','OASIS','Universal Business Language','Universal Business Language Version 2.4','https://docs.oasis-open.org/ubl/UBL-2.4.html','OASIS Standard 2.4, 2024','§2.3.3.5 VMI ; §2.3.5.1 Fulfilment ; §2.3.5.4 Freight Status Reporting','MKT54','Scénarios métier illustrant un standard documentaire')
source('aging',OR,'E-Business Suite Consigned Inventory','Consuming Material','https://docs.oracle.com/cd/E26401_01/doc.122/e48822/T260819T260824.htm','EBS 12.2','Aging Based Ownership Transfer','MKT20')
source('storefulfillment',MS,'Dynamics 365 Commerce','Store order fulfillment','https://learn.microsoft.com/en-us/dynamics365/commerce/order-fulfillment-overview','Page mise à jour le 28 janvier 2026','Pick up ; Shipping ; Line quantity tracking','MKT14')
source('intercompany',MS,SCM,'Intercompany orders and return orders','https://learn.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/intercompany-orders-and-return-orders',EV,'Introduction : création correspondante des commandes intersociétés','MKT14')
source('backtoback',OR,'Fusion Cloud Supply Chain Orchestration','Use Supply Chain Orchestration in Your Back-to-Back Flows','https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/26b/fauco/how-orchestration-processes-back-to-back-flows.html','26B','Back-to-back flows ; buy, make, transfer ; demand and supply link','MKT20')
source('gop',OR,'Fusion Cloud Global Order Promising','Overview of Global Order Promising','https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/25c/fascp/overview-of-global-order-promising.html','25C','Supply chain search ; capable-to-promise','MKT20')
source('ifo',MS,'Dynamics 365 Intelligent Order Management','Intelligent fulfillment optimization architecture','https://learn.microsoft.com/en-us/dynamics365/intelligent-order-management/ifo-arch',EV,'Fulfillment strategies ; source priority ; distance ; partial orders','MKT14')
source('warehouse',MS,SCM,'Outbound workload visualization','https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/outbound-workload-visualization',EV,'Introduction : suivi du travail en cours et restant','MKT14')
source('store',MS,'Dynamics 365 Commerce','Store inventory management','https://learn.microsoft.com/en-us/dynamics365/commerce/work-with-store-inventory',EV,'Store inventory management operations ; inventory dimensions','MKT14')
source('replenishment',MS,SCM,'Replenishment methods and quantity modification','https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/planning-optimization/replenishment-methods-quantity-modification','Page mise à jour le 1er juillet 2026','Coverage codes : Requirement, Min./Max.','MKT14')
source('gs1','GS1','Global Traceability Standard','GS1 Global Traceability Standard','https://www.gs1.org/standards/gs1-global-traceability-standard/current-standard','Version en ligne ; édition non figée par cette consultation','Identification : Class-level, Batch/Lot-level, Instance-level','MKT42','Standard d’identification et de traçabilité')

def comparison(key, similar, diff, choice, definition=None, locator=None, cmp='CMP186'):
    s=sources[key]
    return dict(vendor=s['vendor'],product=s['product'],element_name=s['source_title'],element_type=s['element_type'],
        relationship='Recouvrement partiel',similarities=similar,differences=diff,flow_position=choice,
        term_choice=choice,definition_choice=definition or diff,
        **{k:v for k,v in s.items() if k.startswith('source_')},
        consulted_on=s['consulted_on'],status='proposed',source_refs=['U470','U471',s['id'],cmp],
        evidence_limits='Passage primaire consulté ; rapprochement limité au périmètre décrit, sans équivalence de catalogue, choix de solution ni réalisation Beaumanoir déduite.',
        **({} if locator is None else {})) | ({'source_locator':locator} if locator else {})

added={}
def add(id,key,similar,diff,choice,definition=None,locator=None):
    assert id not in added
    added[id]=comparison(key,similar,diff,choice,definition,locator)

add('D08','batch','Import de références produit depuis plusieurs sources.','Le Product Hub peut gouverner les maîtres ; le référentiel FLOW reste leur projection.','Product Reference exprime la référence utilisable par la Supply, indépendante du catalogue.','La réception est incluse ; créer, modifier ou supprimer les maîtres dans leurs applications reste externe.')
add('D01.f','journals','Mouvements et comptages actualisent les quantités suivies.','Les journaux Microsoft regroupent aussi des effets comptables et des actions opératoires.','Inventory Tracking désigne la tenue de la situation de stock.','FLOW établit les quantités à partir des faits reconnus ; la visibilité restitue cette situation et la logistique réalise les mouvements.')
add('D01.c','supplydemand','Lecture datée du disponible, des approvisionnements et des besoins.','La page décrit une consultation produit, pas une responsabilité transverse avec exigence de fraîcheur.','Inventory Visibility conserve le sens établi de visibilité du stock.','FLOW explicite provenance, fraîcheur et absence de double compte ; la consultation ne crée ni stock ni réservation.')
add('D02.b','pal','Des limites par groupes préservent des ressources pour d’autres demandes.','PAL traite des confirmations par groupe ; Supply Protection couvre aussi d’autres politiques de protection.','Supply Protection est plus large que Product Allocation dans ce sens SAP.','La capacité maintient les règles applicables ; leur calcul spécialisé relève notamment de Group Protection Decision.')
add('D02.c','reservation','Une quantité liée à une demande est protégée contre les prélèvements concurrents.','Les objets et modalités Oracle ne sont pas repris dans FLOW.','Reservation est retenu pour son effet d’opposabilité.','Seule la réservation bloque les usages concurrents ; affectation et engagement ne la créent pas implicitement (choix FLOW).')
add('D03.i','ps','L’ATP établit une disponibilité datée à partir des ressources et besoins.','PeopleSoft mêle promesse, réservation et traitement des pénuries dans le même chapitre.','Available-to-Promise conserve le terme établi, à une maille métier distincte.','FLOW calcule les possibilités de la situation de référence ; confirmer un engagement et réserver restent séparés.',locator='Available-to-Promise ; ATP lead days')
add('D03.k','ptp','La promesse peut intégrer les coûts des ressources effectivement mobilisées.','Cet appui et la première référence sont deux documents Oracle ; ils ne démontrent pas un consensus interéditeurs.','Profitable-to-Promise est un terme documenté notamment par Oracle.','FLOW compare les conséquences économiques des scénarios ; il ne présuppose ni marge unique ni pondération de tous les critères.',locator='Profitable to Promise')
add('D03.l','schedules','Un échéancier associe des quantités à plusieurs dates de livraison.','La page décrit l’échéancier et son traitement, sans isoler l’arbitrage qui le choisit.','Delivery Schedule nomme un résultat établi ; Decision précise la responsabilité FLOW.','FLOW distingue le choix d’un échéancier réalisable de son enregistrement dans la commande.')
add('D03.m','ps','Des règles ordonnent les demandes avant de leur attribuer les ressources.','L’exemple applique ces priorités dans la réservation ; FLOW isole leur détermination.','Order Prioritization explicite un arbitrage entre commandes.','Une priorité ne change à elle seule ni affectation, ni engagement, ni réservation.',locator='Inventory priority rules ; tri des demandes')
add('D05.d','pal','Les plafonds de consommation protègent les groupes de demande.','La configuration PAL ne constitue pas une méthode universelle de calcul des bonnes quantités.','Group Protection Decision indique ce qui est décidé, sans ambiguïté avec l’affectation.','FLOW choisit les quantités ou limites ; Supply Protection en maintient les règles applicables.')
add('D05.f','plans','Plusieurs plans permettent d’étudier des stratégies et de simuler leurs effets.','Master Planning englobe des calculs et traitements regroupés autrement dans FLOW.','Inventory Planning conserve la pratique de planification centrée sur le stock.','La capacité construit et adapte les scénarios ; elle mobilise les décisions spécialisées et leurs capacités d’application.')
add('D06.b','workload','Charge et capacité d’entrepôt peuvent être projetées par période.','Exemple limité à l’entrepôt, pas preuve d’une capacité communiquée par tout exécutant.','Service Capacity Visibility étend ce besoin de lecture aux services admissibles.','FLOW utilise une capacité contextualisée reçue des exécutants ; il ne reprend pas l’administration de leurs moyens.')
add('D07.b','tmf','Une commande de service peut être créée, modifiée et suivie.','TMF641 est un contrat sectoriel télécom ; le texte public ne démontre pas tous les états de FLOW.','Service Order Management dispose d’un appui lexical hors ERP.','FLOW garde le cycle métier des prestations demandées aux exécutants, sans importer API, états télécom ou catalogue technique.')
add('D08.d','batch','Des références et leurs éléments associés sont importés depuis des sources produit.','Le lot d’import est un mécanisme produit ; FLOW ne prescrit ni lot ni gouvernance de maître.','Product Reference Ingestion nomme la responsabilité de réception.','L’ingestion rend les références externes utilisables ; elle ne devient pas leur administration.')
add('D06.e','carrier','Le choix porte explicitement sur un transporteur et son service.','Cas transport et choix manuel dans un produit historique ; toutes les prestations ne sont pas documentées.','Service Selection Decision désigne le choix de l’exécutant et du service.','FLOW conserve les contraintes d’admissibilité ; le produit illustre ce résultat sans imposer l’outil ou la méthode.')
add('BHV006','plans','Les plans servent aussi à simuler des stratégies alternatives.','La documentation porte sur la planification ; tous les usages analytiques FLOW ne sont pas couverts.','Simulation & Analysis décrit une pratique de comparaison de scénarios.','Ce comportement éclaire une décision ou un plan, sans devenir un domaine autonome.')
add('BHV031','spot','Un comptage ponctuel peut être déclenché pendant une opération ciblée.','Oracle illustre un déclenchement par seuil au prélèvement, plus étroit que tous les motifs FLOW.','Spot Counting conserve le sens de vérification ponctuelle.','Le comportement ne se limite pas à une campagne périodique ni à un seuil logiciel imposé.')
add('BHV033','ps','Une fenêtre temporelle détermine quand commencer la réservation.','Le paramètre PeopleSoft est une réalisation possible, pas une règle générale de durée.','Time-Fenced Reservation Policy explicite l’horizon de protection.','FLOW conserve une politique métier conditionnelle ; aucun nombre de jours ni blocage anticipé implicite.',locator='Reservation lead days')
add('BHV036','plans','Un horizon de firming transforme des ordres planifiés en ordres fermes.','L’automatisme et l’horizon Microsoft ne sont pas obligatoires dans FLOW.','Order Firming reprend un terme établi de planification.','Le changement d’engagement est distingué du calcul préalable et de l’exécution physique.')
add('BHV044','schedules','Une ligne est répartie entre livraisons distinctes rattachées à son origine.','Cet exemple porte sur des lignes de livraison ; il ne couvre pas toutes les scissions de commandes.','Order Splitting décrit la scission ; Order Structuring inclut aussi les regroupements.','La filiation et les quantités doivent rester cohérentes ; les regroupements ne sont pas déduits de cette source.')
add('BHV047','pegging','Le stock reçu peut être réaffecté à des demandes antérieures selon les règles.','Microsoft combine protection de promesses et maintien du pegging ; FLOW sépare ces responsabilités.','Supply Reassignment désigne la révision des liens ressources–commandes.','Réaffecter reste soumis aux engagements modifiables ; une affectation seule ne réserve pas.')
add('BHV057','repair','Le fournisseur répare le bien et restitue le même exemplaire.','Le guide historique inclut des traitements financiers qui restent hors du comportement FLOW.','Return for Repair distingue réparation, remplacement et retour définitif.','L’attendu de restitution et l’identité du bien sont conservés, sans imposer le parcours logiciel.')
add('BHV058','po','Les commandes d’achat portent quantités et échéances d’approvisionnement.','Un Purchase Order peut aussi couvrir d’autres destinations que le stock.','Stock Procurement précise la destination du parcours d’achat.','FLOW suit ce qui reste à recevoir pour le réseau ; il ne reprend ni comptabilité ni structure d’écran ERP.')
add('BHV059','orchestration','Le drop shipment permet une livraison du fournisseur au client.','Le produit orchestre plusieurs types d’approvisionnement dans un même module.','Direct Delivery explicite le trajet métier, également appelé drop shipment.','Côté achat, FLOW coordonne les attendus fournisseur avec ceux de la vente ; le transport reste distinct.')
add('BHV061','ubl','Le stock de départ précède les réapprovisionnements de l’activité.','Les scénarios VMI/CRP ne sont pas tous consignés ; VMI et consignation ne sont pas synonymes.','Initial Stocking est un terme établi pour l’apport de départ.','FLOW l’applique ici au stock consigné et à son échéance de lancement.',locator='§2.3.3.5.2.2 ; §2.3.3.5.3.1 et §2.3.3.5.3.3')
add('BHV062','ubl','Les réapprovisionnements suivent l’activité et les mouvements de stock.','UBL décrit des échanges ; il ne prescrit ni propriété ni responsabilité unique du calcul.','Continuous Replenishment distingue les apports récurrents du démarrage.','FLOW porte les apports consignés successifs, sans imposer rythme ou algorithme.',locator='§2.3.3.5.2.4 ; §2.3.3.5.3.4')
add('BHV064','aging','Une durée contractuelle peut déclencher l’acquisition du stock consigné.','Deux générations Oracle documentent ce comportement ; cela ne prouve pas son universalité.','Aging-Based Ownership Transfer décrit cet effet contractuel précis.','Aucun délai fixe ni règle automatique ne sont ajoutés au contrat métier FLOW.')
add('BHV065','ubl','Le producteur peut demander le retour de marchandises.','L’exemple étaye la reprise, pas les autres sorties ni leurs autorisations contractuelles.','Consignment Exit reste un regroupement FLOW de sorties autorisées.','Reprise, soldeur, seconde main ou destruction restent conditionnés par les accords ; aucune décision de sortie nouvelle.',locator='§2.3.3.5.2.6 Returns Initiated by the Producer')
add('BHV066','storefulfillment','Le magasin peut expédier une commande au client.','L’exemple traite le magasin ; FLOW couvre aussi les autres lieux du réseau.','Ship to Customer est un parcours orienté destinataire.','Le comportement porte la commande à livrer ; préparer et transporter relèvent des exécutants.',locator='Shipping ; Line quantity tracking')
add('BHV067','storefulfillment','Le retrait client dispose d’une action distincte de la préparation.','Les états produit associent aussi facturation et retrait ; FLOW ne reprend pas cette assimilation.','Customer Pickup nomme le mode de remise au client.','Une commande prête ne prouve pas que le client l’a retirée.',locator='Pick ; Pick up')
add('BHV068','orchestration','Le fournisseur peut livrer directement le client.','Le module Oracle est une réalisation ; il ne fixe pas les frontières entre nos Orders.','Direct Delivery est conservé côté vente comme côté achat.','Côté vente, FLOW suit l’attendu client et sa coordination avec l’achat, sans détour physique imposé par le réseau.')
add('BHV069','intercompany','Les commandes de vente et d’achat intersociétés se correspondent.','La création automatique décrite par Microsoft n’est pas imposée par FLOW.','Intercompany Sales reprend le vocabulaire établi de vente entre entités juridiques.','La cohérence des engagements est attendue ; le mécanisme de synchronisation reste hors de la cartographie.')
add('BHV070','ubl','Un stock de base est constitué au début d’une saison.','UBL décrit une relation fournisseur–distributeur, pas un transfert interne : appui sémantique uniquement.','Initial Stocking précise le but du transfert, distinct du réassort courant.','FLOW applique ce motif au Transfer Order ; aucun achat ou transfert de propriété n’en est déduit.',locator='§2.3.3.5.3.3 Initial Stocking of the Area by Retailer')
added['BHV070']['relationship']='Appui sémantique'
add('BHV074','backtoback','Un transfert peut alimenter une commande identifiée avec un lien suivi.','Le flux Oracle peut maintenir un lien ferme ; cette règle produit ne vaut pas réservation implicite FLOW.','Order-Driven Transfer exprime le motif du transfert.','Le lien et l’échéance sont conservés ; la protection contre les demandes concurrentes reste du ressort de Reservation.')
add('BHV075','gop','Le CTP examine une fourniture à obtenir, notamment par fabrication.','Oracle distingue ses modes et règles ATP/CTP ; FLOW conserve sa propre situation de référence.','Additional Supply Feasibility explicite la possibilité de ressources supplémentaires.','Le comportement évalue les quantités, dates et conditions possibles ; il ne crée pas lui-même un ordre ferme.')
add('BHV076','ifo','Des stratégies évaluent différentes sources sous contraintes de satisfaction.','IFO réalise aussi l’optimisation ; ce comportement FLOW est limité à la faisabilité des alternatives.','Fulfillment Alternative Feasibility rend explicite l’objet de l’étude.','Changer de lieu ou de modalité crée une possibilité à examiner, pas un engagement automatique.')
add('BHV077','ps','La gestion des pénuries permet de revoir la couverture des demandes prioritaires.','Le workbench applique des changements ; FLOW distingue leur étude et leur application.','Commitment Rebalancing Feasibility nomme l’évaluation des engagements révisables.','Les conséquences sur les commandes restent explicites ; aucune promesse intangible n’est retirée automatiquement.',locator='Shortage Workbench ; unfulfill et priorités')
add('BHV079','warehouse','Le travail d’entrepôt en cours et restant peut être suivi.','Cette page illustre les sorties ; elle ne documente pas à elle seule les réceptions.','Warehouse Visibility indique le périmètre de visibilité.','FLOW reçoit les faits d’avancement ; afficher le travail ne signifie pas l’exécuter.')
add('BHV080','ubl','Les partenaires se transmettent les états d’acheminement.','Le scénario ne garantit ni temps réel ni calcul prédictif d’arrivée.','Transportation Visibility est éclairé par ces échanges de progression.','FLOW rend visibles les faits et estimations disponibles, sans réaliser le transport.',locator='§2.3.5.4 Freight Status Reporting')
add('BHV081','store','Des opérations et états de stock magasin sont suivis.','La page ne documente pas toute la mise en rayon et ses remontées.','Store Visibility délimite le contexte magasin.','FLOW conserve une lecture des faits reçus ; il ne reprend pas l’exécution des tâches magasin.')
add('BHV083','replenishment','La méthode Requirement calcule un approvisionnement par besoin.','FLOW ne prescrit pas un ordre distinct par besoin : le regroupement reste possible.','Requirement-based Replenishment désigne le raisonnement à partir des besoins.','Les ressources utilisables et apports attendus sont pris en compte ; la forme de la commande reste distincte.',locator='Coverage codes : Requirement')
add('BHV084','replenishment','Min./Max. réapprovisionne vers une cible après franchissement d’un seuil.','Cette méthode illustre le comportement sans épuiser les politiques de cible.','Target-based Replenishment couvre ce raisonnement par niveau de stock.','Les seuils et cibles sont explicites ; aucune commande client individuelle n’est requise pour chaque apport.',locator='Coverage codes : Min./Max. ; examples')
add('BHV085','plans','Des messages proposent d’avancer, retarder ou ajuster des ordres existants.','Les propositions Microsoft ne définissent pas toutes les limites de modification FLOW.','Replenishment Adjustment désigne la révision des apports prévus.','La décision respecte les engagements et reste distincte de sa mise en application.',locator='Action message time fence')
add('TER036','ubl','Un avis de réception rapporte les biens effectivement reçus.','Cet exemple documentaire ne démontre pas que tout événement possède un document.','Fait de gestion reste le sens métier adopté dans FLOW.','Le lien obligatoire fait–document est notre convention ; le document peut être un enregistrement structuré.',locator='§2.3.5.1.3 Receipt Advice Business Rules')
added['TER036']['relationship']='Appui sémantique'
add('TER059','gs1','L’identification à l’instance distingue les exemplaires physiques.','GS1 illustre GTIN et numéro de série ; FLOW ne rend pas ce marquage universel.','Product Unit désigne l’exemplaire, distinct de Product et Product Variant.','L’identité physique ne se confond ni avec une référence commerciale ni avec son support de lecture.')
added['TER059']['relationship']='Appui sémantique'
add('TER081','schedules','Une ligne peut être scindée en livraisons rattachées à son origine.','Une scission de livraison est un cas particulier, pas toutes les formes de Split.','Split conserve le sens de scission.','La filiation distingue la scission d’une redistribution des ressources ou d’une fusion.')
added['TER081']['relationship']='Appui sémantique'
add('TER082','pegging','Le pegging relie les ressources disponibles à des demandes.','Microsoft n’emploie pas ici Spread ; l’appui porte sur le mécanisme, pas sur un terme universel.','Spread reste le terme local du raisonnement ARun discuté.','La répartition ressource–commande ne change pas l’identité des commandes et ne vaut pas réservation FLOW.')
added['TER082']['relationship']='Appui sémantique'

m=read(ROOT/'modeles/backlog/model.yaml');g=read(ROOT/'modeles/backlog/glossary.yaml')
baseline=json.loads((HERE/'single-references.json').read_text(encoding='utf-8'))
assert set(added)=={x['id'] for x in baseline} and len(added)==47
for item in m['nodes']+g['terms']:
    if item['id'] not in added: continue
    fields=item.get('fields',item)
    before=next(x for x in baseline if x['id']==item['id'])
    assert fields.get('market_comparisons')==before['entries'], item['id']+' already changed'
    assert fields['definition']==before['definition']
    fields['market_comparisons'].append(added[item['id']])
    item['source_refs']=list(dict.fromkeys(item.get('source_refs',[])+added[item['id']]['source_refs']))

u=next(n for n in m['nodes'] if n['id']=='universe-supply'); f=u['fields']
f['finality']='Organiser l’approvisionnement, la répartition et la livraison des produits pour tenir les quantités et les dates promises.'
f['definition']='Décider quels produits fournir, en quelle quantité, depuis quel lieu et à quelle date, puis coordonner les prestations nécessaires jusqu’à leur réalisation. La [Supply Chain](glossary:TER084), ou chaîne d’approvisionnement, relie les fournisseurs, les entrepôts, les transporteurs, les magasins et les clients. Cet univers en assure l’[orchestration](glossary:TER031) : il suit les [commandes](glossary:TER012) et les [stocks](glossary:TER005), établit les engagements et adapte les choix lorsque la situation change.'
f['scope']='Les applications externes restent les sources de vérité des référentiels : c’est là que leurs données sont créées, modifiées ou supprimées. La Supply en reçoit des projections, c’est-à-dire les références utiles à ses opérations, par [Reference Ingestion](glossary:TER050). Elle ne les administre pas à leur place.\n\nLe périmètre se concentre ainsi sur l’orchestration : commandes, stocks, promesses, optimisation et coordination des services. Les exécutants préparent, transportent et remettent les produits ; la Supply reçoit leurs faits de réalisation pour suivre les engagements et traiter les écarts.'
f['examples']=[
 dict(title='Livrer 100 tee-shirts à un magasin vendredi',situation='Le magasin attend 100 tee-shirts pour vendredi. Un entrepôt en détient 60 et un fournisseur doit en livrer 40 jeudi.',outcome='La Supply vérifie si les 100 peuvent être livrés à temps, établit la quantité et la date promises, puis coordonne préparation et transport. Si les 40 sont retardés, elle examine les alternatives et les conséquences sur la commande.',lesson='La Supply organise et suit la satisfaction de la demande ; les exécutants réalisent les opérations physiques. La promesse ne réserve pas implicitement le stock.',source_refs=['U470','U436']),
 dict(title='Recevoir une nouvelle référence produit',situation='Une nouvelle variante de tee-shirt, bleu taille M, est créée dans l’application qui fait autorité sur les produits.',outcome='Son identifiant et ses caractéristiques utiles sont reçus dans [Product Reference](glossary:TER052). La Supply peut alors utiliser cette référence dans ses commandes et ses stocks.',lesson='La projection sert aux opérations Supply. La création et les corrections de la référence restent dans la source de vérité externe.',source_refs=['U470','U97','U460'])]
f['market_comparisons']=[
comparison('cscmp','Le SCM inclut coordination des partenaires, approvisionnement, transformation et logistique.','Ce périmètre professionnel est plus large que l’univers FLOW ; SCM ne désigne pas seulement son noyau d’orchestration.','Supply Chain Orchestration précise la responsabilité retenue dans FLOW, au sein d’une chaîne plus large.','Le choix répond au périmètre client : référentiels maîtres externes et réalisation physique confiée aux exécutants. Ce découpage est local, pas imposé par CSCMP.',cmp='CMP185'),
comparison('scm','La suite couvre notamment produits, stocks, planification, achats, production et entrepôts.','FLOW ne reprend pas le périmètre complet d’une suite SCM : administration des maîtres et opérations physiques restent à l’extérieur.','Le nom Orchestration rend cette frontière plus explicite que Supply Chain Management seul.','Les référentiels Supply sont des projections reçues par ingestion ; ce choix concentre l’univers sur la coordination sans nier ses responsabilités de commandes et de stocks.',cmp='CMP185'),
comparison('orchestration','Le produit reçoit des demandes et coordonne leur approvisionnement et leurs changements.','Le module Oracle coopère avec Promising, Inventory et Order Management ; l’univers FLOW regroupe aussi des responsabilités que ces produits portent séparément.','Supply Chain Orchestration est un terme existant du marché, avec un périmètre FLOW propre.','Le nom met l’accent sur la coordination des engagements et des moyens de les satisfaire ; il ne signifie ni adoption du module Oracle ni équivalence de catalogue.',cmp='CMP185')]
u['source_refs']=list(dict.fromkeys(u['source_refs']+['U470','CMP185']+[sources[k]['id'] for k in ['cscmp','scm','orchestration']]))
u['review']['note']+=' U470 : entrée concrète, périmètre des projections, exemples et comparaisons au niveau de l’univers ; reformulations éditoriales proposées, nom adopté inchangé.'
term=next(t for t in g['terms'] if t['id']=='TER084')
term['definition']='Chaîne d’approvisionnement : ensemble des acteurs et des activités qui permettent d’amener un produit depuis ses fournisseurs jusqu’à ses destinataires. Elle comprend notamment approvisionnement, transformation éventuelle, stockage, transport et distribution, ainsi que les retours.'
term['context']='Exemple : un fournisseur livre des tee-shirts à un entrepôt, qui les répartit entre magasins ; un transporteur les achemine, puis les magasins les remettent aux clients. Supply Chain désigne cette chaîne ; Supply Chain Management sa gestion et sa coordination.'
term['source_refs']=list(dict.fromkeys(term['source_refs']+['U470']))
term=next(t for t in g['terms'] if t['id']=='TER031')
term['definition']='Coordonner les activités nécessaires pour obtenir un résultat : déterminer ce qui doit se passer, solliciter les intervenants, suivre leur avancement et adapter la suite en cas d’écart.'
term['context']='Exemple Supply : demander la préparation de 100 tee-shirts, coordonner leur transport puis suivre leur remise au magasin. L’orchestration s’appuie sur les faits transmis par les exécutants ; elle ne réalise pas elle-même la préparation ou le transport.'
term['market_comparisons']=[comparison('orchestration','Des demandes et leurs changements sont coordonnés entre intervenants.','Le module Oracle est une réalisation particulière ; ce terme décrit ici une responsabilité métier.','Orchestration conserve le sens de coordination.','Aucune technologie, couche ou hiérarchie entre univers n’est prescrite.',cmp='CMP185'),comparison('cscmp','La coordination entre partenaires contribue à la gestion de la chaîne.','CSCMP définit le SCM, pas une capacité universelle nommée Orchestration.','Le terme met l’accent sur la conduite coordonnée des activités.','FLOW délimite cette responsabilité selon son périmètre ; réaliser physiquement reste distinct.',cmp='CMP185')]
term['source_refs']=list(dict.fromkeys(term['source_refs']+['U470','CMP185',sources['orchestration']['id'],sources['cscmp']['id']]))
term=next(t for t in g['terms'] if t['id']=='TER050')
term['context']='Exemple : recevoir une variante de produit créée dans le référentiel maître, avec son identifiant, sa taille et sa couleur. Une correction est reçue depuis cette même autorité ; la Supply ne modifie pas le maître à sa place.'
term['source_refs']=list(dict.fromkeys(term['source_refs']+['U470']))
m['market_reference_policy']='two_primary_sources'
write_text_if_changed(ROOT/'modeles/backlog/model.yaml',dumps(m))
write_text_if_changed(ROOT/'modeles/backlog/glossary.yaml',dumps(g))
write_text_if_changed(HERE/'sources.yaml',dumps({'consulted_on':'2026-09-19','scope':'U470/U471, passages primaires sélectifs, aucune reproduction intégrale','sources':list(sources.values())}))
write_text_if_changed(HERE/'additions.yaml',dumps({'market_comparisons':added}))

# Append new identified records so previous source captures stay byte-identical.
with (ROOT/'marche/elements.md').open('a',encoding='utf-8',newline='') as out:
    for key,s in sources.items():
        ids=[id for id,c in added.items() if s['id'] in c['source_refs']]
        if key in ['cscmp','scm','orchestration']: ids+=['universe-supply']
        if key in ['cscmp','orchestration']:ids+=['TER031']
        out.write(f"\n\n### {s['id']}\n\nU470/U471 — {s['market_ref']}, {s['vendor']}, {s['product']}. [{s['source_title']}]({s['source_url']}). {s['source_version']}. Nature : {s['element_type']}. Passage consulté le 19 septembre 2026 : {s['source_locator']}. Libellé natif : titre indiqué ; aucun identifiant natif de capacité déduit. Appuis pour {', '.join(ids)} ; reformulations, différences et limites dans leurs comparaisons et dans [le relevé U471](../audits/2026-09-19-base-U470/additions.yaml). Synthèse sélective et liens, sans reprise intégrale ni réalisation installée déduite.\n")
with (ROOT/'marche/comparaisons.md').open('a',encoding='utf-8',newline='') as out:
    out.write('\n\n### CMP185\n\nU470 — Codex, 19 septembre 2026, rapprochements proposés : CSCMP, Microsoft SCM et Oracle Supply Chain Orchestration → universe-supply ; CSCMP et Oracle → TER031. Backlog courant capturé avant correction dans l’audit U470. Comparaison du nom et du périmètre de l’univers, pas synthèse des capacités. Le SCM large sert de contraste de périmètre ; le nom Oracle atteste un usage sans équivalence de maille. Le choix FLOW concentre l’orchestration, garde les maîtres externes et leurs projections ingérées, et distingue les exécutants. Bénéfice : expliquer la frontière au lecteur novice. U373 conserve son nom adopté ; aucun nouveau valideur des rédactions ou correspondances. Sources, passages et limites dans les fiches et sources.yaml de l’audit.\n')
    out.write('\n### CMP186\n\nU471 — Codex, 19 septembre 2026, rapprochements proposés sur les 47 fiches identifiées dans single-references.json de l’audit U470. Une seconde source primaire pertinente est ajoutée à chacune ; les comparaisons préexistantes et les définitions sont préservées. [Correspondances détaillées](../audits/2026-09-19-base-U470/additions.yaml) : élément externe, cible, relation, points communs, différences, choix du terme et de définition, édition, passage, date et limites. État comparé : backlog du 19 septembre avant ces ajouts, conservé dans before/. Les sources d’un même éditeur sont signalées comme telles ; deux documents ne prouvent pas un consensus. Les recouvrements partiels restent partiels, notamment comportements plus larges que leurs exemples. Bénéfice : permettre une revue argumentée sans importer les frontières des produits. Aucun valideur des rapprochements, changement de responsabilité, réouverture de U431 ou publication implicite.\n')
with (ROOT/'marche/catalogue.md').open('a',encoding='utf-8',newline='') as out:
    out.write('\n\n## MKT54\n\nOASIS — Universal Business Language 2.4, OASIS Standard 2024. [Source officielle](https://docs.oasis-open.org/ubl/UBL-2.4.html), consultée le 19 septembre 2026. Nature : standard documentaire et scénarios métier ; distinct du modèle SOA MKT09. Passages : VMI/CRP, Fulfilment/Receipt Advice, Freight Status Reporting. Rôle : éclairer les différences entre mise en stock initiale, réapprovisionnement, retours et faits documentés. Limites : ni taxonomie de capacités ni modèle de propriété imposé ; synthèses originales, pas de schéma ou texte intégral importé.\n\n## Compléments U470/U471 — références existantes\n\nLe [registre des 30 documents consultés](../audits/2026-09-19-base-U470/sources.yaml) précise éditions, titres et passages primaires : MKT13 SAP, MKT14 Microsoft (SCM, Commerce, IOM et exemples historiques Dynamics AX/GP), MKT19 TM Forum (présentation publique TMF641 archivée), MKT20 Oracle (Fusion et exemples historiques EBS/PeopleSoft, produits distincts), MKT41 CSCMP et MKT42 GS1 (Global Traceability Standard, distinct d’EPCIS). Comparaisons sélectives, aucune édition historique présentée comme actuelle ; aucun catalogue propriétaire ni contrat technique adopté.\n')
print('47 fiches complétées ; univers et 3 termes clarifiés ; 30 documents enregistrés.')
