import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require('C:/Users/laure/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const base = 'http://127.0.0.1:8765';
const version = '2026-09-19.4';
const errors = [], checks = [];
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  page.setDefaultTimeout(12000);
  page.on('pageerror', error => errors.push(error.message));
  const goto = async hash => {
    await page.goto(base + '/#version=' + version + '&' + hash);
    await page.locator('#page-title').waitFor();
  };
  await goto('view=glossary&glossary=meta&term=MOD012');
  const information = page.locator('#term-MOD012');
  await information.waitFor();
  assert.match(await information.innerText(), /Ensemble minimal/);
  assert.match(await information.innerText(), /ne constitue pas un modèle de données implémentable/);
  assert.match(await information.innerText(), /deux informations métier reliées/);
  await page.screenshot({ path: fileURLToPath(new URL('v011-information.png', import.meta.url)), fullPage: true });
  checks.push('Information et son exemple proposition/engagement sont visibles dans le glossaire du méta modèle.');
  await goto('view=principles');
  await page.locator('.guide-lesson').waitFor();
  assert.equal(await page.locator('h1').innerText(), 'Comprendre le méta modèle');
  assert.equal(await page.locator('.guide-topics > button').count(), 6);
  assert.equal(await page.locator('.guide-realizations').count(), 0);
  checks.push('Guide actuel : six repères, sans simulateur de réalisations logicielles.');
  await goto('view=glossary&glossary=model&term=TER086');
  await page.locator('[data-glossary="model"] #term-TER086').waitFor();
  assert.match(await page.locator('#term-TER086').innerText(), /Purchase Order Document|Bon de commande/i);
  assert.equal(await page.getByText('En quelques mots', { exact: true }).count(), 0);
  checks.push('Glossaire métier publié séparément, avec le document d’achat et sans résumé redondant.');
  await goto('view=sheet&node=universe-supply');
  await page.locator('.business-sheet').waitFor();
  assert.match(await page.locator('.business-sheet').innerText(), /Coordonner la satisfaction des demandes Supply/);
  checks.push('Définition métier actualisée de la Supply.');
  await goto('view=sheet&node=D03.n');
  await page.locator('.business-sheet').waitFor();
  assert.match(await page.locator('.business-sheet').innerText(), /Exemples concrets/);
  await page.getByRole('tab', { name: 'Marché & choix', exact: true }).click();
  await page.locator('.market-comparisons').waitFor();
  assert.ok(await page.locator('.market-comparisons a[href^="https://"]').count() > 0);
  checks.push('Fulfillment Commitment : exemple et références primaires de marché accessibles.');
  assert.equal(await page.locator('.status-badge, .lifecycle-badge, .detail-reservations, .source-link').count(), 0);
  await page.goto(base + '/#version=2026-09-19.3&view=glossary&glossary=meta');
  await page.locator('[data-glossary="meta"]').waitFor();
  await page.getByRole('textbox', { name: 'Rechercher dans le glossaire' }).fill('Information');
  assert.equal(await page.locator('.glossary-index a[href*="MOD012"]').count(), 0);
  checks.push('v010 conserve son ancien guide sans récupérer Information depuis la nouvelle version.');
  assert.deepEqual(errors, []);
  const result = { version, checks, errors };
  await writeFile(new URL('browser-verification.json', import.meta.url), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result, null, 2));
} finally { await browser.close(); }
