import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.ATLAS_PLAYWRIGHT_PATH || 'C:/Users/laure/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base = 'http://127.0.0.1:8765';
const version = '2026-09-19.3';
const browser = await chromium.launch({ channel:'msedge', headless:true });
const checks=[], errors=[];
try {
  const page = await browser.newPage({ viewport:{ width:1500, height:1050 }, reducedMotion:'reduce' });
  page.setDefaultTimeout(15000);
  page.on('pageerror', error => errors.push(error.message));
  const model = await (await page.request.get(base + '/api/model')).json();
  assert.equal(model.version, version);
  const capabilities=model.nodes.filter(n=>n.kind==='capability'), behaviors=model.nodes.filter(n=>n.kind==='behavior');
  assert.equal(capabilities.length,47); assert.equal(behaviors.length,76);
  assert.ok([...capabilities,...behaviors].every(n=>n.fields.nature));
  await page.goto(base+'/#view=sheet&node=D01.g');
  await page.locator('.business-sheet').waitFor();
  assert.match(await page.locator('#fa-version').innerText(), /v010.*2026-09-19\.3/);
  assert.equal(await page.locator('#fa-version .live-dot.fixed').count(),0);
  checks.push('v010 affichée en suivi de la publication courante ; 47 capacités et 76 comportements typés dans le snapshot réel.');
  const icons={policy_strategy:'sliders-horizontal',process_variant:'route',intervention_mechanism:'settings-2',business_scope:'scan-line',decision_dimension:'compass',business_effect:'arrow-left-right',planning_practice:'calendar-check'};
  for(const [type, icon] of Object.entries(icons)){
    const node=behaviors.find(n=>n.fields.nature===type);
    assert.ok(node,type);
    await page.goto(base+'/#view=sheet&node='+node.id);
    await page.locator('.business-sheet').waitFor();
    const svg=page.locator(`[data-behavior-type="${type}"] svg`).first();
    assert.ok((await svg.getAttribute('class')).includes('lucide-'+icon));
    assert.equal(await page.locator(`#field-${node.id}-nature h2`).innerText(),'Type de comportement');
  }
  checks.push('Sept formes de comportements et sept icônes vérifiées sur la publication réelle, sans fixture.');
  await page.goto(base+'/#view=sheet&node=D03.i');
  await page.locator('.behavior-summary').first().waitFor();
  assert.equal(await page.locator('.behavior-summary [data-behavior-type="decision_dimension"]').count(),4);
  await page.screenshot({path:fileURLToPath(new URL('v010-atp.png',import.meta.url)),fullPage:true});
  await page.goto(base+'/#view=sheet&node=D06');
  await page.locator('.business-sheet').waitFor();
  assert.equal(await page.locator('.detail-children-list > .decision-divider').count(),1);
  const natureOrder=await page.locator('.detail-children-list [data-capability-type]').evaluateAll(items=>items.map(el=>el.dataset.capabilityType));
  const firstDecision=natureOrder.indexOf('decision');
  assert.ok(firstDecision>0); assert.ok(natureOrder.slice(firstDecision).every(type=>type==='decision'));
  checks.push('Capacités de décision en fin de domaine avec séparation légère.');
  await page.getByRole('button',{name:'Comprendre le méta modèle',exact:true}).click();
  await page.locator('.guide-lesson').waitFor();
  assert.equal(await page.locator('.guide-topics > button').count(),6);
  await page.getByRole('button',{name:'Glossaire métier',exact:true}).click();
  await page.locator('[data-glossary="model"]').waitFor();
  assert.equal(await page.locator('.glossary-index li').count(),100);
  await page.getByRole('button',{name:'Glossaire du méta modèle',exact:true}).click();
  await page.locator('[data-glossary="meta"]').waitFor();
  assert.equal(await page.locator('.glossary-index li').count(),21);
  assert.equal(await page.locator('.status-badge, .source-dialog, .validation-summary').count(),0);
  checks.push('Guide méthodologique conservé après publication : six repères, deux glossaires (100 et 21 termes), aucune métadonnée interne affichée.');
  await page.goto(base+'/#version=2026-09-19.2&view=sheet&node=BHV001');
  await page.locator('.business-sheet').waitFor();
  assert.match(await page.locator('#fa-version').innerText(), /v009.*2026-09-19\.2/);
  assert.equal(await page.locator('#fa-version .live-dot.fixed').count(),1);
  assert.equal(await page.locator('.page-heading [data-behavior-type]').count(),0);
  checks.push('v009 reste consultable en version fixe, sans récupération des nouveaux types depuis v010.');
  assert.deepEqual(errors,[]);
  const result={version,checks,errors};
  await writeFile(new URL('browser-verification.json',import.meta.url),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
} finally { await browser.close(); }
