from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from scripts.structured_io import read, dumps, write_text_if_changed

ROOT = Path(__file__).parent
INPUT = read(ROOT / 'foundations-input.yaml')
OLD = {x['id']: x for x in INPUT['terms']}
S = {}
OUT = {'source': 'U477', 'nodes': [], 'terms': []}
ACTIVE = None

def source(key, vendor, product, title, url, version, locator, finding, limits, method='Document primaire ouvert ; passages indiqués effectivement lus'):
    S[key] = dict(vendor=vendor, product=product, source_title=title, source_url=url, source_version=version, source_locator=locator, consulted_on='2026-09-19', finding=finding, evidence_limits=limits, consultation_method=method)

source('togaf','The Open Group','TOGAF Series Guide','Business Capabilities','https://governance.foundation/assets/frameworks/togaf/g189%20-%20Business%20Capbility.pdf','Guide G189, 2018','§2.1–2.3 ; §3.1.1 ; §3.2 ; §4.2.1','Le guide distingue aptitude, composants mobilisés, catégories de lecture et décomposition ; exemple Recruitment Management.','Publication originale The Open Group consultée dans une copie hébergée par Governance Foundation, couverture et copyright vérifiés. Guide de méthode de 2018 ; aucune adoption de toute sa hiérarchie par FLOW.')
source('nz','New Zealand Digital Government','GEA-NZ','Business capabilities','https://dns.govt.nz/standards-and-guidance/technology-and-architecture/government-enterprise-architecture/gea-nz-framework/business-capabilities','Page institutionnelle évolutive, édition non indiquée','Definition ; Principles 1–4 ; exemple Pay staff','GEA-NZ distingue le besoin, son pourquoi et les moyens ; classe les capacités pour éclairer lacunes et recouvrements.','Cadre propre aux administrations néo-zélandaises ; le vocabulaire organisationnel et les taxonomies ne sont pas transposés à FLOW.')
source('ddd','Eric Evans','Domain-Driven Design Reference','Domain-Driven Design Reference: Definitions and Pattern Summaries','https://www.domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf','Mars 2015','Definitions ; Entities p.11 ; Value Objects p.12 ; Domain Events p.13 ; Services p.14','Le domaine est un champ de connaissance ou d’activité ; les objets peuvent être reconnus par leur identité ou leurs valeurs ; un service peut porter une opération qui ne revient naturellement à aucun objet.','Résumé de patrons par leur auteur, orienté conception logicielle. Les concepts éclairent le sens métier sans imposer objets de code, services ni bounded contexts au modèle FLOW.')
source('fowler','Martin Fowler','Patterns of Enterprise Application Architecture','Domain Model','https://martinfowler.com/eaaCatalog/domainModel.html','5 mars 2003','Définition et paragraphe explicatif de la fiche','Le Domain Model associe informations et comportements dans des objets ayant un sens pour le domaine ; exemple de la ligne de commande.','Fiche courte du patron par son auteur, pas consultation du chapitre complet ni définition normative de tout objet métier.')
source('bpmn','OMG','Business Process Model and Notation','Business Process Model and Notation, Version 2.0.2','https://www.omg.org/spec/BPMN/2.0.2/PDF','BPMN 2.0.2, décembre 2013','§10.1 Process, p.143 ; §10.3.3 Tasks, p.154 ; Manual Task p.161–163','Un processus décrit des activités, événements et passages ; une tâche constitue un travail élémentaire à la maille retenue, humain ou automatisé.','Standard de notation et de déroulement ; ni carte de capacités ni règle d’équivalence entre une tâche et une opération FLOW.')
source('sbvr','OMG','Semantics of Business Vocabulary and Business Rules','Semantics of Business Vocabulary and Business Rules, Version 1.5','https://www.omg.org/spec/SBVR/1.5/PDF','SBVR 1.5, mai 2019','§16.1.2–16.1.3 p.98–100 ; §18.1.2 exemple EU-Rent p.118','Une règle praticable permet d’apprécier ce qui est acceptable ; l’exemple EU-Rent distingue obligation d’annulation et action qui l’exécute.','La juridiction métier et les catégories de SBVR sont plus précises que le terme générique FLOW ; pas d’importation de son métamodèle.')
source('rules','Microsoft','Dynamics 365 Commerce','DOM rules','https://learn.microsoft.com/en-us/dynamics365/commerce/dom-rules','Documentation évolutive, mise à jour du 22 janvier 2026','Common attributes ; Minimum inventory rule ; Partial orders rule','DOM utilise des contraintes de sourcing et distingue règles impératives ou relâchables ; du stock peut rester disponible pour les clients du magasin.','Comportements propres à DOM et à ses versions ; ils illustrent des règles, sans imposer ce solveur ni ses priorités à FLOW.')
source('abc','SAP','S/4HANA Sales','Using Advanced Available-To-Promise (aATP) in SAP S/4HANA','https://learning.sap.com/courses/functions-innovations-in-sap-s-4hana-sales/using-advanced-available-to-promise-aatp-in-sap-s-4hana_ef38afd2-4730-433f-854a-613b8e4afec5','Cours en ligne, édition non précisée','Alternative-Based Confirmation ; Backorder Processing ; Release for Delivery','Le cours décrit plusieurs fonctions aATP, dont la confirmation depuis un autre site et le réexamen des commandes.','Description de fonctions produit ; leur regroupement commercial ne définit pas une capacité FLOW ni une couverture installée.')
source('context','Martin Fowler','Domain-Driven Design','Bounded Context','https://martinfowler.com/bliki/BoundedContext.html','15 janvier 2014','Paragraphes sur le vocabulaire et l’exemple meter','Un même mot peut changer de sens selon le contexte ; le cas du compteur distingue équipement et relation au réseau ou au client.','Retour d’auteur sur les modèles logiciels dans l’approche DDD ; document distinct d’Evans mais même école de pensée, pas preuve de consensus entre cadres.')
source('receipt','Microsoft','Dynamics 365 Supply Chain Management','Record the receipt of goods on the purchase order','https://learn.microsoft.com/en-us/dynamics365/supply-chain/procurement/tasks/record-receipt-goods-purchase-order','Documentation évolutive, mise à jour du 1er juillet 2026','Record receipt of goods, étapes 4–7 ; Review the product receipt journal','Le parcours reçoit quatre pièces sur cinq commandées ; l’enregistrement produit un journal de réception avec une référence documentaire.','Exemple de réception de biens ; aucune universalité fait-document, immutabilité ou règle de correction n’en est déduite.')
source('ubl','OASIS','Universal Business Language','Universal Business Language Version 2.4','https://docs.oasis-open.org/ubl/UBL-2.4.html','OASIS Standard 2.4, 2024','§2.3.5.1.1–2.3.5.1.4 Fulfilment ; surtout Receipt Advice Business Rules','Receipt Advice rapporte la réception, ses quantités et les écarts ; Despatch Advice rapporte l’expédition.','Standard de documents d’échange ; les exemples ne définissent ni tous les documents ni la convention obligatoire fait-document de FLOW.')
source('cloud','CNCF','CloudEvents','CloudEvents Specification','https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md','Version 1.0.2','Terminology : Occurrence, Event, Producer, Consumer','Une occurrence peut donner lieu à plusieurs événements contenant son contexte ; la représentation peut être transmise à des consommateurs.','Spécification d’interopérabilité des messages ; ni contrat métier exhaustif ni protocole imposé pour FLOW.')
source('notification','Martin Fowler','Event-driven architecture','What do you mean by Event-Driven?','https://martinfowler.com/articles/201701-event-driven.html','7 février 2017','Event Notification','La notification signale un changement et peut fournir des références pour obtenir les détails ; elle se distingue d’une demande d’action déguisée.','Article de clarification par son auteur ; décrit plusieurs styles, sans faire de la notification un stockage du fait ni garantir sa livraison.')

def start(id):
    global ACTIVE
    ACTIVE=id

def c(key, name, scope, approach, common, diff, position, relation='Rapprochement de sens'):
    s=S[key]
    prior=next((x for x in OLD[ACTIVE].get('market_comparisons',[]) if x['source_url']==s['source_url']),None)
    return dict(vendor=s['vendor'],product=s['product'],element_name=name,concept_name=name,element_type='Notion ou usage documenté',relationship=relation,scope_summary=scope,approach_summary=approach,similarities=common,differences=diff,flow_position=position,**{k:s[k] for k in ('source_title','source_url','source_version','source_locator','consulted_on','evidence_limits')},status=prior['status'] if prior else 'proposed',source_refs=list(dict.fromkeys((prior['source_refs'] if prior else [])+['U477'])))

def ex(key,title,situation,outcome,lesson):
    return dict(title=title,situation=situation,outcome=outcome,lesson=lesson,source_title=S[key]['source_title'],source_url=S[key]['source_url'],source_refs=['U477'])

def emit(choice,scope,approach,synthesis,example,comparisons,notes=None):
    row=dict(id=ACTIVE,market_comparisons=comparisons,market_inspiration=dict(choice=choice,flow_scope=scope,flow_approach=approach,synthesis=synthesis,examples=[example]))
    if notes:row['editorial_notes']=notes
    OUT['terms'].append(row)

start('TER001')
emit('Décrire ce que l’entreprise sait faire permet de conserver un repère quand ses équipes ou ses outils changent. Capacité métier désigne cette aptitude durable.','Aptitude de l’entreprise à produire un résultat métier.','Définir le service attendu avant les moyens employés.',
'Le guide TOGAF sépare le « quoi » des rôles, processus et outils qui le rendent possible. GEA-NZ reprend cette distinction en rattachant plus explicitement chaque capacité à sa raison d’être. Les deux partent du besoin de l’entreprise.\n\nFLOW conserve cette indépendance : un changement d’application ne suffit pas à créer une nouvelle capacité. L’étape d’un parcours ou la fonction d’un produit n’en devient une que si elle correspond à une aptitude métier justifiée.',
ex('nz','GEA-NZ — payer les salariés','GEA-NZ compare un petit employeur qui paie directement son personnel à un employeur utilisant un logiciel de paie et des virements.','Les moyens changent ; le besoin de payer les salariés demeure.','La même distinction permet de parler de la capacité avant de choisir sa réalisation.'),[
c('togaf','Business capability','Aptitude de l’entreprise, actuelle ou nécessaire.','Séparer aptitude et moyens.','Le besoin survit aux changements d’organisation.','Le guide propose sa propre structuration de carte.','FLOW reprend le principe, avec sa décomposition propre.'),
c('nz','Business / organisational capability','Ce qui permet de réaliser stratégie et résultats.','Relier besoin et raison d’être.','La capacité ne prescrit pas le logiciel.','GEA-NZ vise des administrations et leur modèle de fonctionnement.','FLOW l’applique à ses responsabilités métier.')])

start('TER002')
emit('Nommer ce sur quoi l’entreprise raisonne permet de partager les mêmes faits et décisions. Objet métier désigne cette notion, indépendamment de son stockage ou de sa représentation.','Commandes, ressources et autres notions utiles au raisonnement métier.','Distinguer le sens métier des documents et outils qui le portent.',
'Fowler décrit un Domain Model composé d’objets qui portent des informations et des comportements. Evans distingue notamment les objets suivis par leur identité de ceux caractérisés par leur valeur. Ils cherchent tous deux à représenter le métier dans un logiciel.\n\nFLOW emploie Objet métier à une maille plus générale : reconnaître une commande ou une ressource ne choisit pas encore sa forme informatique. Ni une table ni un message ne deviennent un objet métier par leur seule existence.',
ex('fowler','Fowler — la ligne de commande','Fowler cite la ligne d’un bon de commande parmi les objets qui peuvent avoir un sens dans un modèle de domaine.','L’objet peut représenter une notion plus fine qu’une entreprise entière, également citée dans le texte.','Dans FLOW, la pertinence vient du raisonnement métier ; cet exemple ne fixe pas une structure de données.'),[
c('fowler','Domain Model object','Informations et comportements d’une notion du domaine.','Modéliser des objets significatifs pour le métier.','Les notions doivent avoir un sens partagé.','Le patron vise leur conception logicielle.','FLOW retient le sens avant toute mise en œuvre.'),
c('ddd','Entity / Value Object','Objets identifiés ou caractérisés par leur valeur.','Préciser ce qui fait reconnaître la même chose.','Identité et caractéristiques éclairent les faits suivis.','Ces patrons ne classent pas tous les objets FLOW.','La convention reste plus large qu’un type d’objet logiciel.')])

start('TER023')
emit('Dire ce qui est admissible et ce qui doit en découler rend les décisions explicables. Règle métier désigne la condition ou le principe appliqué, distinct du moyen qui l’exécute.','Conditions de validité, d’admissibilité et d’effet des décisions ou faits.','Expliciter la règle, son contexte et ses conséquences.',
'SBVR insiste sur une règle assez précise pour juger un comportement acceptable ; il distingue la prescription de l’action qui la fait respecter. Microsoft DOM montre des règles appliquées au choix de satisfaction, comme conserver du stock pour les visiteurs d’un magasin.\n\nLe standard explique le sens de la règle ; l’éditeur montre un usage concret, avec ses propres paramètres et possibilités de relâchement. FLOW garde la règle métier lisible sans reprendre automatiquement le fonctionnement du moteur.',
ex('rules','Microsoft — garder du stock pour les visiteurs','La règle Minimum inventory de DOM permet d’écarter une partie du stock magasin de la satisfaction des commandes.','Cette quantité reste destinée à d’autres usages, notamment les clients présents en magasin.','La règle exprime une priorité d’usage ; elle ne crée pas à elle seule une nouvelle capacité.'),[
c('sbvr','Business rule','Prescription métier applicable à une situation.','Rendre l’acceptabilité appréciable.','Une condition explicite encadre les effets permis.','SBVR précise aussi juridiction et catégories de règles.','FLOW conserve un terme général sans importer ces catégories.'),
c('rules','DOM rule','Contraintes du choix de site et de satisfaction.','Appliquer des règles impératives ou relâchables.','Les choix doivent respecter des conditions définies.','Les niveaux de contrainte sont propres à DOM.','FLOW indique les règles du cas, sans présumer ce moteur.')])

start('TER024')
emit('Expliquer comment un résultat est obtenu rend visibles les étapes et les passages entre acteurs. Processus désigne ce déroulement, qui peut mobiliser plusieurs capacités.','Activités, événements et décisions enchaînés dans un contexte.','Décrire le parcours vers un résultat.',
'BPMN représente l’enchaînement des activités et événements, avec leurs conditions de passage. Le guide TOGAF regarde le processus comme l’un des moyens qui permettent d’exercer une capacité. Le premier décrit le déroulement ; le second le situe par rapport à l’aptitude.\n\nFLOW conserve les deux lectures : la carte dit ce que l’entreprise sait faire, le processus raconte comment elle le fait dans un cas. Un parcours peut traverser plusieurs domaines sans leur imposer un nouveau découpage.',
ex('togaf','TOGAF — recruter une personne','L’exemple Recruitment Management cite notamment l’évaluation du besoin, la recherche de candidats et leur sélection.','Plusieurs processus concourent au recrutement.','Une étape ou un parcours de recrutement ne se confond pas avec l’aptitude durable à recruter.'),[
c('bpmn','Process','Déroulement d’activités et d’événements.','Montrer les passages et leurs conditions.','Le résultat dépend d’un déroulement contextualisé.','BPMN fournit une notation détaillée, y compris exécutable.','FLOW ne prescrit pas cette notation pour reconnaître un processus.'),
c('togaf','Processes enabling a capability','Moyens d’exercer une aptitude.','Relier déroulement et capacité.','Une capacité peut mobiliser plusieurs processus.','Le guide organise ces liens pour l’architecture d’entreprise.','FLOW garde des parcours transverses aux domaines.')])

start('TER025')
emit('Préciser l’action accomplie et ce qu’elle change rend son résultat vérifiable. Opération métier désigne une action sur des objets, avec des conditions et des effets définis.','Action telle qu’enregistrer une réception ou confirmer une promesse.','Décrire ce qui doit être vrai avant et après l’action.',
'BPMN appelle Task un travail élémentaire à la maille du processus décrit. Microsoft montre une opération concrète d’enregistrement de réception, qui produit un journal identifiable. Le standard fixe une place dans le déroulement ; l’éditeur expose l’action et sa trace.\n\nFLOW se concentre sur le sens de l’action et ses effets métier. Une opération peut contribuer à une capacité sans en constituer une à elle seule ; un bouton ou une opération informatique ne fixe pas cette maille.',
ex('receipt','Microsoft — enregistrer quatre pièces reçues','Le parcours Microsoft part d’une commande de cinq pièces et enregistre la réception de quatre.','Le journal conserve la réception effectivement enregistrée, avec sa référence.','L’opération change les faits tenus sur la commande ; elle reste distincte de la réception physique des pièces.'),[
c('bpmn','Task','Travail élémentaire au sein d’un processus.','Représenter une étape sans détail inférieur dans ce parcours.','Une action possède une place et un résultat attendus.','L’atomicité BPMN dépend du niveau de description.','FLOW définit l’opération par ses objets, conditions et effets.'),
c('receipt','Record receipt of goods','Enregistrement d’une réception d’achat.','Saisir les quantités puis produire leur trace.','L’action a un effet métier identifiable.','Le parcours correspond à un produit et un écran précis.','FLOW garde l’action indépendante de cet écran.')])

start('TER026')
emit('Montrer avec quels moyens une capacité est exercée permet de comprendre ce qui peut changer sans changer le besoin. Réalisation d’une capacité désigne ces moyens concrets.','Acteurs, pratiques, outils et échanges mobilisés.','Distinguer l’aptitude de sa mise en œuvre dans un contexte.',
'TOGAF décrit les rôles, processus, informations et ressources qui rendent une capacité possible. GEA-NZ donne une illustration simple : payer les salariés peut se faire avec des moyens très différents. Les deux relient le besoin à une combinaison de moyens.\n\nFLOW utilise Réalisation pour cette combinaison, sans réduire le mot au logiciel. La présente comparaison n’établit ni une solution choisie ni une réalisation installée chez Beaumanoir ; Atlas conserve sa présentation métier.',
ex('nz','GEA-NZ — changer le moyen de paiement des salaires','L’employeur de l’exemple peut payer son personnel directement ou utiliser un logiciel de paie.','Le moyen concret évolue sans supprimer le besoin de payer.','C’est le sens de réalisation retenu par FLOW ; chaque situation réelle demanderait ses propres preuves.'),[
c('togaf','Capability components','Moyens humains, pratiques, informations et ressources.','Relier la capacité à ce qui la rend possible.','La réalisation repose sur plusieurs moyens.','Le guide nomme des composants, pas un objet unique équivalent.','FLOW regroupe ces moyens sous Réalisation.'),
c('nz','Capability implementation','Manière concrète de satisfaire le besoin.','Comparer plusieurs mises en œuvre.','Changer le comment ne change pas nécessairement le quoi.','Le cadre gouvernemental ne décrit pas les moyens de FLOW.','Aucune réalisation locale n’est déduite de l’exemple.')])

start('TER027')
emit('Préciser ce que l’on entend par « fonction » évite de mélanger un rôle dans l’entreprise et une possibilité offerte par un outil. FLOW ne donne pas à ce mot un niveau unique dans la carte.','Mot à qualifier selon le contexte de son emploi.','Demander le sens et le périmètre avant de rapprocher les notions.',
'Le guide TOGAF emploie des noms de fonctions pour parler d’unités ou de périmètres d’organisation, en les distinguant des capacités. SAP présente des fonctions aATP comme des possibilités de son produit. Le même mot renvoie ainsi à des angles différents.\n\nFLOW garde cette ambiguïté visible : fonction métier, fonction d’organisation et fonctionnalité de produit doivent être précisées. Aucun de ces usages ne crée automatiquement un étage entre domaine et capacité.',
ex('togaf','TOGAF — une capacité dans plusieurs fonctions','Le guide rapproche Project Management et Learning Management de plusieurs unités, dont les ressources humaines et l’informatique.','Une même capacité peut être exercée dans plusieurs parties de l’organisation.','Le nom d’une fonction ou d’un service ne suffit donc pas à définir une capacité distincte.'),[
c('togaf','Organizational function','Partie ou rôle de l’organisation.','Examiner où les capacités sont exercées.','Le contexte donne son sens au mot fonction.','Ce sens organisationnel ne désigne pas une aptitude autonome.','FLOW exige le qualificatif utile avant toute équivalence.'),
c('abc','aATP functions','Possibilités offertes par S/4HANA.','Décrire confirmation, alternatives et réexamen.','Fonction peut aussi désigner ce que fait le produit.','Le périmètre dépend du produit et de son édition.','FLOW utilise Fonctionnalité de produit pour ce sens précis.')])

start('TER028')
emit('Décrire ce qu’un produit permet effectivement de faire aide à comparer son apport au besoin métier. Fonctionnalité de produit désigne un comportement offert dans une édition et une configuration données.','Possibilités documentées d’un produit.','Vérifier l’édition, les conditions et les effets avant de conclure sur la couverture.',
'SAP rassemble dans aATP des possibilités de confirmation, d’alternative et de réexamen du carnet. Microsoft détaille les règles DOM et précise les versions qui modifient le découpage des commandes. Les deux montrent qu’une fonctionnalité possède des conditions concrètes d’usage.\n\nLe nom commercial ne suffit donc pas à mesurer la couverture d’une capacité FLOW. Une fonction peut n’en couvrir qu’une partie ou contribuer à plusieurs responsabilités ; la documentation ne prouve pas son installation.',
ex('rules','Microsoft — le nombre de lieux de satisfaction','Microsoft explique que le réglage de satisfaction depuis un seul lieu a évolué vers un nombre maximal de lieux.','Les possibilités de découpage varient selon la version, la règle et les options activées.','Comparer une fonctionnalité exige ce contexte ; on ne peut conclure à partir de « DOM » seul.'),[
c('abc','Alternative-Based Confirmation','Confirmation possible depuis d’autres sites ou produits.','Proposer les variantes prises en charge par SAP.','Une fonctionnalité apporte un service concret.','Son regroupement aATP dépasse une seule responsabilité FLOW.','La correspondance se fait sur les effets documentés.'),
c('rules','Partial orders rule','Possibilités de découpage proposées par DOM.','Activer et paramétrer selon la version.','L’édition et la configuration conditionnent le comportement.','La règle ne décrit pas toute la capacité de satisfaction.','La couverture FLOW reste à examiner au bon périmètre.')])

start('TER029')
emit('Rapprocher les capacités selon un critère métier rend la carte plus facile à lire. Regroupement de capacités désigne cette organisation de lecture, sans présumer une capacité parente.','Ensemble de capacités réunies pour une raison explicite.','Indiquer le critère commun et distinguer regroupement et décomposition.',
'TOGAF distingue la classification des capacités pour lire une carte et leur décomposition pour détailler une aptitude. GEA-NZ recommande également de les classer afin de repérer lacunes et recouvrements. Les deux donnent un but à l’organisation de la carte.\n\nFLOW conserve cette distinction : partager un thème ne signifie pas être les parties d’une même capacité. Un domaine peut apporter ce cadre de lecture quand ses problèmes métier sont cohérents ; le regroupement ne crée pas un niveau « fonction ».',
ex('togaf','TOGAF — catégories et décomposition','Le guide présente des catégories Strategic, Core et Supporting puis, séparément, la décomposition de Human Resource Management.','Le premier classement facilite une lecture ; le second détaille une aptitude.','FLOW reprend la différence entre les deux opérations, sans adopter ces catégories comme niveaux du modèle.'),[
c('togaf','Stratification / leveling','Classement de lecture et détail d’une aptitude.','Distinguer les deux objectifs.','Regrouper n’est pas nécessairement décomposer.','Les catégories et niveaux du guide lui sont propres.','FLOW choisit des critères métier explicites.'),
c('nz','Categorised capabilities','Classement des capacités d’une organisation.','Repérer lacunes, chevauchements et doublons.','Le classement aide à comprendre la carte.','GEA-NZ renvoie à des taxonomies gouvernementales.','FLOW ne reprend pas une taxonomie externe par défaut.')])

start('TER030')
emit('Traiter ensemble des problèmes métier liés permet d’en comprendre la logique commune. Domaine désigne cet espace cohérent, sans imposer une organisation ni une frontière logicielle.','Problèmes, notions et responsabilités qui gagnent à être compris ensemble.','Justifier le regroupement par le métier et préciser ses relations avec les autres domaines.',
'Evans emploie domain pour le champ de connaissance ou d’activité auquel s’applique le modèle. Fowler explique ensuite pourquoi un même vocabulaire peut prendre des sens différents dans plusieurs contextes. Les deux invitent à regarder le sens des problèmes avant leur représentation.\n\nFLOW retient le domaine comme périmètre de cohérence métier. Il ne le confond pas avec le bounded context de DDD, qui délimite un modèle utilisé pour concevoir du logiciel ; les frontières applicatives ne sont pas arrêtées par ce terme.',
ex('context','Fowler — les différents sens du compteur','Dans son exemple d’un fournisseur d’électricité, « compteur » peut désigner l’équipement ou une relation du réseau avec un lieu ou un client.','Le vocabulaire doit être précisé pour éviter des modèles contradictoires.','L’illustration aide FLOW à expliciter les problèmes et notions de chaque domaine ; elle ne prescrit pas ses frontières.'),[
c('ddd','Domain','Champ de connaissance ou d’activité.','Construire un modèle utile à ses problèmes.','Le périmètre part d’un sens métier cohérent.','Evans l’aborde dans la conception de logiciel.','FLOW emploie cette cohérence pour sa carte métier.'),
c('context','Bounded Context','Périmètre où un modèle et son langage restent cohérents.','Expliciter les différences de sens et leurs relations.','La cohérence du vocabulaire aide à comprendre les frontières.','Un contexte DDD n’est pas un domaine FLOW par équivalence.','Aucune architecture applicative n’est déduite du regroupement.')],notes='TER030 garde sa définition métier courante. Les repères historiques MKT017 / ELM041 / CMP027 sont conservés dans l’entrée et la capture ; les deux documents sont des appuis nouveaux U477, pas une adoption des bounded contexts.')

start('TER036')
emit('Savoir ce qui s’est produit et sur quelle trace s’appuyer rend le suivi métier explicable. Dans le sens plateforme retenu par FLOW, un fait de gestion est toujours associé à un document identifié.','Événement métier et document qui en porte la trace.','Conserver le lien entre occurrence et représentation, même sans document PDF.',
'Microsoft illustre le couple réception enregistrée et journal de réception. UBL décrit un Receipt Advice qui rapporte au partenaire ce qui a été reçu et les écarts éventuels. Le premier montre une trace dans un produit ; le second un document d’échange.\n\nIls appuient concrètement le lien entre un événement et un document, sans établir que tout événement du marché suit cette règle. Son caractère obligatoire est le choix FLOW pour le sens plateforme du terme ; notification et fait restent distincts.',
ex('receipt','Microsoft — quatre pièces reçues sur cinq','Le scénario Microsoft enregistre quatre pièces reçues sur une commande de cinq.','Le journal de réception matérialise les quantités enregistrées avec une référence documentaire.','FLOW reconnaît le fait « quatre pièces reçues » et le document qui le porte ; leur rôle n’est pas celui du message qui avertit un tiers.'),[
c('receipt','Product receipt and receipt journal','Réception enregistrée et trace associée.','Enregistrer la quantité et sa référence.','Un événement peut être relié à un document identifiable.','Le cas ne généralise pas à tous les événements métier.','L’obligation fait-document reste une convention FLOW.'),
c('ubl','Receipt Advice','Compte rendu de réception entre partenaires.','Rapporter quantités reçues et écarts.','Le document donne une représentation du fait de réception.','UBL porte l’échange documentaire, pas le sens plateforme complet.','FLOW distingue le fait, sa trace et sa notification.')])

start('TER037')
emit('Conserver une représentation compréhensible d’un état ou d’un fait permet de s’y référer. Document, au sens plateforme, peut être un enregistrement structuré ; il ne suppose pas un fichier à lire ou à imprimer.','Représentation d’état ou objet non modifiable produit ou capté, selon le cas défini.','Identifier ce que le document représente et le distinguer de l’occurrence métier.',
'UBL donne des documents d’échange différents pour l’expédition et la réception. Microsoft produit un journal lors de l’enregistrement des marchandises reçues. UBL insiste sur ce qui est communiqué au partenaire ; Microsoft sur la trace tenue dans le produit.\n\nFLOW retient cette possibilité d’un document structuré, tout en gardant sa définition propre. Ces exemples ne suffisent pas à décider des règles de version, de correction ou d’immutabilité de tous les documents FLOW.',
ex('ubl','UBL — distinguer expédié et reçu','UBL sépare Despatch Advice, émis pour l’expédition, et Receipt Advice, émis à la réception.','Le réceptionnaire peut signaler des manquants, des dommages ou des refus.','Les documents représentent des faits différents ; recevoir un avis d’expédition ne prouve pas que les biens ont été reçus.'),[
c('ubl','Despatch Advice / Receipt Advice','Documents structurés d’expédition et de réception.','Communiquer un état ou un constat identifié.','Un document n’est pas nécessairement un PDF.','UBL définit des échanges particuliers, pas tout objet documentaire.','FLOW précise le fait ou l’état représenté.'),
c('receipt','Product receipt journal','Trace consultable d’une réception enregistrée.','Conserver les détails et leur référence.','L’enregistrement peut porter un document métier.','La page ne démontre pas une immutabilité générale.','Les règles de correction restent celles du type de document.')],notes='Les règles de correction/version restent à préciser selon l’historique courant ; cette rubrique n’en crée aucune et n’étend pas le catalogue Informations métier.')

start('TER039')
emit('Prévenir un destinataire de ce qui vient de se produire lui permet de réagir avec les bonnes références. Notification d’événement désigne ce message, distinct du fait lui-même.','Information d’une occurrence à un destinataire.','Transmettre le contexte utile sans confondre informer et demander une action.',
'Fowler distingue la notification d’événement d’une demande d’action déguisée ; le message peut ne contenir que les références utiles pour consulter les détails. CloudEvents distingue aussi l’occurrence de sa représentation transmise et admet plusieurs événements pour une même occurrence.\n\nLe premier explique l’intention du message ; le second facilite son échange entre systèmes. FLOW retient l’intention métier et les références nécessaires, sans prescrire de format, de protocole ou de mode de conservation.',
ex('notification','Illustration FLOW — signaler une réception','Une réception a été enregistrée avec son document ; un message avertit le responsable d’une commande concernée.','Le destinataire dispose des références pour consulter le fait et décider de la suite.','Le message informe : son émission ne constitue ni une nouvelle réception ni, à elle seule, un ordre de poursuivre.'),[
c('notification','Event Notification','Message signalant un changement.','Informer sans exiger implicitement une réponse précise.','La notification porte une intention d’information.','L’article décrit un style d’architecture, pas un processus FLOW.','La réaction du destinataire garde ses propres règles.'),
c('cloud','Event / Occurrence','Représentation échangeable d’un événement survenu.','Séparer occurrence, contexte et destinataires.','Plusieurs messages peuvent représenter un même fait.','CloudEvents spécifie surtout l’interopérabilité.','FLOW ne prescrit pas son format pour définir le terme.')])

def finish():
    assert {x['id'] for x in OUT['terms']} == set(OLD)
    assert len(OUT['terms']) == len(OLD) == 13
    required=('vendor','product','element_name','element_type','relationship','similarities','differences','flow_position','source_title','source_url','source_version','source_locator','consulted_on','status','source_refs','evidence_limits','concept_name','scope_summary','approach_summary')
    for row in OUT['terms']:
        assert len({r['source_url'] for r in row['market_comparisons']}) >= 2, row['id']
        for comparison in row['market_comparisons']:
            assert all(comparison.get(k) for k in required), row['id']
        ins=row['market_inspiration']
        assert all(ins.get(k) for k in ('choice','flow_scope','flow_approach','synthesis','examples'))
        assert len(ins['synthesis'].split('\n\n')) in (2,3)
        for example in ins['examples']:
            assert all(example.get(k) for k in ('title','situation','outcome','lesson','source_title','source_url','source_refs'))
    sources=[]
    for key,s in S.items():
        item=dict(local_key=key,**s)
        item['supported_ids']=[x['id'] for x in OUT['terms'] if any(c['source_url']==s['source_url'] for c in x['market_comparisons'])]
        item['examples']=[dict(fiche_id=x['id'],**e) for x in OUT['terms'] for e in x['market_inspiration']['examples'] if e['source_url']==s['source_url']]
        item['previous_provenance']=[dict(fiche_id=id,source_refs=r['source_refs']) for id,t in OLD.items() for r in t.get('market_comparisons',[]) if r['source_url']==s['source_url']]
        sources.append(item)
    write_text_if_changed(ROOT/'foundations-output.yaml',dumps(OUT))
    write_text_if_changed(ROOT/'foundations-sources.yaml',dumps(dict(source='U477',sources=sources,unavailable_documents=[dict(title='ArchiMate 3.2 — Strategy Layer / Business Layer',url='https://pubs.opengroup.org/architecture/archimate32-doc/ch-Strategy-Layer.html',result='Redirection vers une connexion ; contenu non lu et non utilisé comme preuve')],notes='Aucun déplacement des termes entre glossaires ; définitions et accords inchangés.')))
    print(f'FOUNDATIONS: {len(OUT["terms"])} terms, {len(sources)} sources reviewed; contracts OK')

if __name__ == '__main__':
    finish()
