from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from scripts.structured_io import read, dumps, write_text_if_changed
from scripts.market_comparison import validate_comparisons, validate_inspiration

ROOT = Path(__file__).parent
INPUT = read(ROOT / 'promising-input.yaml')
OLD = {n['id']: n.get('fields', n) for k in ('nodes','terms') for n in INPUT[k]}
S = {}

def source(key, vendor, product, title, url, version, locator, finding, limits='Passage primaire consulté ; périmètre du produit documenté, sans preuve d’installation chez Beaumanoir.', method='Texte de la page primaire ouvert et lu'):
    S[key] = dict(vendor=vendor, product=product, source_title=title, source_url=url, source_version=version, source_locator=locator, consulted_on='2026-09-19', finding=finding, evidence_limits=limits, consultation_method=method)

def oldsource(key, id, ix, locator, finding, version=None, limits=None, method=None):
    a=OLD[id]['market_comparisons'][ix]
    source(key,a['vendor'],a['product'],a['source_title'],a['source_url'],version or a['source_version'],locator,finding,limits or 'Documentation primaire consultée ; aucun choix de produit ni déploiement Beaumanoir déduit.',method or 'Texte de la page primaire ouvert et lu')

oldsource('atp','D03.i',0,'Order promising ; ATP calculations ; Example ; CTP calculations','ATP combine ressources présentes, réceptions et consommations dans le temps ; le délai de préparation fait l’objet d’une option distincte.','Documentation évolutive, mise à jour affichée le 21 avril 2026')
oldsource('ps','D03.i',1,'Understanding Inventory Reservations ; Understanding the Order Line Processing Sequence ; Calculating ATP','PeopleSoft distingue quantité promise et stock réservé, avec règles de priorité et calcul cumulatif ; le traitement peut regrouper plusieurs effets.','PeopleSoft Enterprise Inventory 9.0')
oldsource('ctp','D03.j',0,'How CTP compares to ATP ; exemple Item A composé de B et C ; View confirmed delivery dates','Le CTP de Microsoft évalue matières et capacité nécessaires à la fabrication ; le produit renseigne ensuite des dates confirmées.','Documentation évolutive, mise à jour affichée le 27 juillet 2026')
oldsource('abc','D03.j',1,'Advanced ATP Scenario: Alternative-Based Confirmation ; Release for Delivery','ABC examine des sites et produits de substitution ; RefDy compare des confirmations avant la livraison.','Cours SAP S/4HANA, édition non précisée dans le passage')
oldsource('bop','D03.j',2,'Backorder Processing — Introduction, Reprioritization & Reallocation, Order Confirmations','BOP réexamine les quantités confirmées après changement de disponibilité ou de priorité.','Cours SAP S/4HANA Cloud Public Edition ; édition non précisée')
oldsource('ptp','D03.k',0,'Prioritize ; Promise According to Arrival Date ; exemple Denver/Seattle','L’exemple départage deux lieux au même délai par le coût total ; la date reste prioritaire dans cette configuration.','Oracle Fusion Cloud SCM 26C')
oldsource('database','D03.k',1,'Back-to-Back ; Bill of Resources ; Profitable to Promise ; Consume Transfers at the Same Time','Prise en compte des délais après réception, des ressources critiques et des coûts en fonction du flux.','Oracle Fusion Cloud SCM 25C')
oldsource('schedule','D03.l',1,'Introduction ; Create delivery schedules ; Manage delivery lines','Un échéancier porte plusieurs dates et quantités pour une commande ; le produit le représente par des lignes de livraison.','Documentation évolutive ; édition non précisée')
oldsource('arun','D02.e',0,'Supply Assignment (ARun), introduction et accès','SAP nomme Supply Assignment le lien des ressources aux commandes, y compris en situation de pénurie.','SAP S/4HANA 2025 FPS01 (février 2026)',method='Page ouverte vide ; texte primaire SAP indexé recherché et lu')
oldsource('reassign','D02.e',1,'Reassignment ; Handling of BOP Confirmation Strategies','Sans Reassignment, l’exemple conserve 70 affectées et traite 30 ; avec Reassignment, il réexamine les 100.','SAP S/4HANA 2025 FPS01 (février 2026)',method='Page ouverte vide ; texte primaire SAP indexé recherché et lu')
oldsource('spread','D02.e',2,'Stock and Requirement Sorting ; Allocation ; Release Rules','ARun Fashion répartit selon FIFO ou prorata après regroupement et applique un contrôle de libération.','SAP ERP Fashion Management 6.0 EHP8 SP25',method='Page ouverte vide ; texte primaire SAP indexé recherché et lu')
oldsource('keep','D02.e',3,'What data is preserved ; Control how on-hand inventory is pegged ; Example scenario 1','La préservation des chaînes de demandes confirmées conserve notamment les liens de couverture ; le stock reçu dépend d’une règle complémentaire.','Prérequis documenté : 10.0.48 build 10.0.2645.33 ou ultérieur')
oldsource('assign','D02.e',4,'Supply Assignment Scenarios ; ARun Statuses ; Online Features ; Cross Settings','ARun associe demande et ressource ; ses effets de protection et libération dépassent le seul lien retenu dans FLOW.','Cours SAP S/4HANA for Fashion and Vertical Business ; édition non précisée')
oldsource('backlog','D03',0,'Introduction ; When to Use','Le plan du carnet redistribue l’offre collectée selon les priorités ; les demandes partageant une ressource doivent rester cohérentes.','Oracle Fusion Cloud SCM 26B')
oldsource('actions','D03',1,'Plan Run Actions ; Review Actions ; Attribute Data Simulation Actions ; Release Actions','Oracle distingue simulation, enregistrement des résultats et transmission des résultats retenus à la gestion des commandes.','Oracle Fusion Cloud SCM 25D')
oldsource('approved','D03',2,'View and edit the status of planned orders ; Approve planned orders','Approved conserve des ordres planifiés pour affermissement ; ce n’est pas un plan d’affectation du carnet.','Documentation évolutive, mise à jour affichée le 2 septembre 2026')
oldsource('dom','D03',4,'Introduction, objectifs et contraintes','DOM optimise la satisfaction d’une commande ou d’un lot selon sources, coûts et règles.','Documentation évolutive, mise à jour affichée le 3 juin 2026')
oldsource('confirm','D03.n',1,'Confirm a single sales order, étapes 5 à 15','La confirmation produit un statut documentaire et peut appliquer un contrôle de crédit ; elle ne définit pas seule la promesse de satisfaction.','Documentation évolutive, mise à jour affichée le 1er juillet 2026')
oldsource('ifo','D03.o',0,'Fulfillment sources ; Business constraints ; Fulfillment strategies ; Fulfillment optimization in order orchestration flows','IFO produit un plan de sources et quantités par ligne ; la stratégie documentée privilégie la proximité.','Documentation évolutive, mise à jour affichée le 30 janvier 2026')
oldsource('returns','D03.o',1,'Sources ; Respect warehouse timings ; Restrict partial fulfillment ; Limit number of warehouses','Le choix des sources tient compte des heures limites, quantités, nombre de sites et contraintes de service.','Documentation évolutive ; édition non précisée')
oldsource('gop','BHV075',1,'Introduction ; Principles of Promising ; Examples','Oracle distingue offre déjà existante et offre à créer, tout en combinant priorités, substitution et coût dans le même ensemble produit.','Oracle Fusion Cloud SCM 25C')
oldsource('simple','D03.p',2,'Introduction ; Planned orders simplified','Écran de revue, approbation et affermissement d’ordres planifiés ; comparaison indirecte avec le carnet.','Documentation évolutive ; édition non précisée')
source('alternatives','Microsoft','Dynamics 365 SCM','Delivery alternatives','https://learn.microsoft.com/en-us/dynamics365/supply-chain/sales-marketing/delivery-alternatives','Documentation évolutive ; édition non précisée','Delivery date control methods ; Delivery alternatives ; Availability information','Des options partielles, dates et transports peuvent être comparés en tenant compte des calendriers.')
source('check','Oracle','Global Order Promising','Check Availability','https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/25c/fascp/check-availability.html','Oracle Fusion Cloud SCM 25C','Examine the Attributes ; Schedule the Order Line','Les résultats restent exploratoires tant que la ligne n’est pas planifiée ; demandé, planifié et résultat sont séparés.')
source('sync','Oracle','Global Order Promising','Keep Global Order Promising and Inventory Management Synchronized','https://docs.oracle.com/en/cloud/saas/supply-chain-and-manufacturing/26a/fascp/keep-availability-in-global-order-promising-and-inventory-management-synchronized.html','Oracle Fusion Cloud SCM 26A','Back-to-Back Orders ; Set up Your Material Status and Subinventory','Une réception future peut soutenir la promesse alors que la réservation de stock présent échoue ; importance des statuts admissibles.')
source('sup','SAP','S/4HANA aATP','Integration into Other Processes','https://help.sap.com/docs/SAP_S4HANA_ON-PREMISE/f132c385e0234fe68ae9ff35b2da178c/e541e617043545a0bb60e5067d037046.html','SAP S/4HANA 2025 FPS01 (février 2026)','Product Availability Check ; Alternative-Based Confirmation','Le contrôle de disponibilité prend en compte les protections applicables au couple article/site.',method='Texte primaire SAP indexé recherché et lu')
source('workflow','SAP','S/4HANA aATP','Supply Assignment Run Workflow using Apps','https://help.sap.com/docs/SAP_S4HANA_ON-PREMISE/f132c385e0234fe68ae9ff35b2da178c/863bbfb47d384f6aafff5347fb7e3dba.html','SAP S/4HANA 2025 FPS01 (février 2026)','Monitor Supply Assignment Runs ; Compare Supply Assignment Simulated Runs','SAP distingue résultats simulés, exécutés et incomplets et permet de comparer des simulations.',method='Texte primaire SAP indexé recherché et lu')

OUT={'source':'U477','nodes':[],'terms':[]}
ACTIVE=None
def c(key,name,scope,approach,common,diff,position,relationship='Recouvrement partiel'):
    s=S[key]
    prior=next((r for r in OLD[ACTIVE].get('market_comparisons',[]) if r['source_url']==s['source_url']),None)
    return dict(vendor=s['vendor'],product=s['product'],element_name=name,concept_name=name,element_type='Concept ou mécanisme métier documenté dans un produit',relationship=relationship,scope_summary=scope,approach_summary=approach,similarities=common,differences=diff,flow_position=position,**{k:s[k] for k in ('source_title','source_url','source_version','source_locator','consulted_on','evidence_limits')},status=prior['status'] if prior else 'proposed',source_refs=list(dict.fromkeys((prior['source_refs'] if prior else [])+['U477'])))
def example(key,title,situation,outcome,lesson):
    return dict(title=title,situation=situation,outcome=outcome,lesson=lesson,source_title=S[key]['source_title'],source_url=S[key]['source_url'],source_refs=['U477'])
def start(id):
    global ACTIVE
    ACTIVE=id
def emit(choice,scope,approach,synthesis,ex,comparisons,notes=None):
    kept={x['source_url'] for x in comparisons}
    removed=[x for x in OLD[ACTIVE].get('market_comparisons',[]) if x['source_url'] not in kept]
    row=dict(id=ACTIVE,market_comparisons=comparisons,market_inspiration=dict(choice=choice,flow_scope=scope,flow_approach=approach,synthesis=synthesis.split('\n\n'),examples=[ex]))
    n=[]
    if notes:n.append(notes)
    if removed:n.append('Anciennes références réexaminées et retirées de la présentation pour privilégier les appuis directement utiles à cette fiche : '+ '; '.join(r['source_title'] for r in removed)+'. Provenance intégrale conservée dans promising-input.yaml et le relevé de sources.')
    if n:row['editorial_notes']=' '.join(n)
    OUT['terms' if ACTIVE in {x['id'] for x in INPUT['terms']} else 'nodes'].append(row)

start('D02.e')
emit('Relier les ressources retenues aux commandes permet de savoir avec quoi les satisfaire. Nous gardons Supply Assignment pour cette affectation, distincte du choix du plan, de la réservation et de la promesse.','Ressources présentes ou futures liées aux commandes identifiées.','Appliquer les choix retenus, conserver ou réviser les liens autorisés.',
'SAP emploie Supply Assignment pour un traitement qui combine choix, affectation et préparation de la livraison. Microsoft parle notamment de pegging pour les liens entre ressources et demandes. Les mots se rejoignent sur la relation à maintenir, mais les effets produits diffèrent.\n\nFLOW isole cette responsabilité : une [affectation](glossary:TER017) indique la ressource retenue ; seule la réservation empêche son usage concurrent. Le nom SAP est proche, sans importer tous les effets d’ARun.',
example('assign','SAP — un arrivage lié à une commande','Le cours SAP décrit une commande déjà affectée à un achat attendu.','Le lien est conservé lors de l’avis d’expédition puis de la réception.','FLOW retient la continuité du lien ; les effets de réservation documentés par SAP restent une responsabilité distincte.'),[
c('assign','Supply Assignment (ARun)','Stock présent et réceptions futures associés aux commandes.','Maintenir les liens jusqu’à la livraison.','Même question : quelle ressource sert quelle demande ?','Chez SAP, le lien protège aussi contre d’autres usages.','FLOW sépare affectation, réservation et libération.'),
c('keep','Pegging for confirmed demand','Liens couvrant une demande confirmée.','Préserver la couverture entre plans.','La relation à la demande doit rester explicite.','La fonction Microsoft protège une chaîne de planification plus large.','FLOW ne confond pas le lien avec un gel de tous ses moyens.')])

start('D03.i')
emit('Établir ce que l’on peut promettre avec les ressources déjà présentes ou attendues évite d’annoncer une quantité impossible à servir. ATP inclut les engagements et réservations existants ; son résultat explique les quantités et dates possibles sans les confirmer.','Ressources admissibles dans la situation de référence, pour une ou plusieurs demandes.','Croiser disponibilités, consommations, protections et délais sans changer les règles.',
'Microsoft et PeopleSoft calculent une disponibilité dans le temps, au-delà du stock présent. PeopleSoft rapproche ce calcul du traitement des promesses et réservations ; Microsoft distingue notamment le délai de préparation à l’expédition.\n\nFLOW nomme ATP la décision qui établit les possibilités et leur couverture. Calculer une [disponibilité](glossary:TER009) ne crée ni affectation ni réservation et ne confirme pas l’engagement.',
example('atp','Microsoft — deux arrivages pour honorer 150 pièces','L’exemple Microsoft présente 200 pièces attendues en retard, 75 déjà demandées et un autre arrivage de 100 à dix jours.','Les 125 pièces encore mobilisables du premier arrivage ne suffisent pas ; la demande de 150 attend le second.','Le stock futur contribue à ATP, après prise en compte des autres besoins.'),[
c('atp','Available-to-promise','Quantité promettable à une date.','Calculer ressources et consommations sur l’horizon.','Le futur déjà prévu et les besoins concurrents comptent.','Le document présente une méthode de calcul particulière.','FLOW ne prescrit pas cette formule.'),
c('ps','Cumulative ATP','Quantités promettables par échéance.','Rapprocher offre et demandes déjà promises.','Une même ressource ne peut couvrir des promesses incompatibles.','Le produit joint calcul et traitements de réservation.','FLOW distingue résultat de faisabilité et effet d’engagement.')])

start('D03.j')
emit('Établir à quelles conditions une commande deviendrait satisfaisable permet de proposer une solution quand la situation actuelle ne suffit pas. CTP couvre les adaptations de ressources, de solution ou d’engagements, avec leurs impacts et autorisations nécessaires.','Possibilités après adaptation de la situation de référence.','Mobiliser les décisions responsables puis expliciter les conditions de faisabilité.',
'Le CTP de Microsoft insiste sur les matières et capacités permettant de fabriquer. SAP traite d’autres leviers sous ABC, pour les alternatives, et BOP, pour les confirmations à réexaminer. Ces noms décrivent des fonctions différentes, pas une définition commune de CTP.\n\nFLOW rassemble la faisabilité sous adaptation, tout en laissant les priorités, les choix économiques et les autorisations à leurs responsables. Un autre site déjà admissible relève encore d’ATP ; envisager une adaptation ne l’applique pas.',
example('ctp','Microsoft — fabriquer ce qui manque','Microsoft prend un article A sans stock, composé de B et C.','CTP examine les composants et les moyens de fabrication pour établir combien de A peuvent être fournis.','C’est un exemple d’apport supplémentaire ; FLOW couvre aussi d’autres adaptations sans créer automatiquement un ordre de fabrication.'),[
c('ctp','Capable-to-promise','Matières et capacités de fabrication.','Calculer une date réalisable par production.','Rendre possible une fourniture absente de la référence.','Le sens Microsoft est davantage centré sur la capacité industrielle.','FLOW explicite aussi les adaptations d’engagements et de service.'),
c('abc','Alternative-Based Confirmation','Autres sites ou produits compatibles.','Chercher une confirmation alternative.','Une autre solution peut rendre la demande satisfaisable.','SAP classe ces fonctions dans aATP.','FLOW classe selon ce qui change dans la référence, pas selon le nom produit.'),
c('bop','Backorder Processing','Confirmations devenues inadéquates.','Réexaminer les commandes concernées.','Une révision peut ouvrir une possibilité à une autre demande.','BOP peut directement modifier les confirmations.','CTP établit seulement possibilités et conséquences.')])

start('D03.k')
emit('Choisir une promesse économiquement pertinente évite de gagner une livraison au prix d’un coût injustifié. PTP compare les conséquences économiques des solutions admissibles, avec des contraintes de service explicites et sans pondération universelle.','Scénarios réalisables et coûts ou conséquences économiques pertinents.','Expliquer le compromis économique sans confirmer la promesse.',
'Oracle nomme profitable to promise la recherche d’une solution à moindre coût dans son ordre de priorités de service. Microsoft DOM traite aussi coûts et contraintes, au niveau plus large de l’optimisation des commandes. Les deux rapprochent service rendu et moyens mobilisés.\n\nFLOW isole l’arbitrage économique. Le coût n’annule pas une obligation de délai ; les valeurs inconnues restent inconnues. Le compromis collectif de service, engagements, coûts et risques reste multidimensionnel, sans formule adoptée par cette comparaison.',
example('ptp','Oracle — Seattle plutôt que Denver','Dans l’exemple Oracle, dix unités peuvent arriver au même délai depuis Denver ou Seattle.','Le coût total est de 23 dollars depuis Denver et 22,50 depuis Seattle ; Oracle retient Seattle.','PTP éclaire l’écart économique entre possibilités compatibles ; cette politique chiffrée ne devient pas une règle générale FLOW.'),[
c('ptp','Profitable to promise','Coût de satisfaction d’une ligne.','Départager les possibilités selon coût et délai.','Comparer les conséquences économiques de la promesse.','Oracle décrit une hiérarchie précise : délai puis coût.','FLOW conserve les contraintes et préférences applicables au cas.'),
c('dom','Cost-based fulfillment optimization','Choix des sources pour commandes ou lots.','Optimiser selon objectifs et contraintes.','Les coûts participent au choix de satisfaction.','DOM couvre aussi composition du plan et sourcing.','PTP garde une responsabilité économique délimitée.')],notes='Database Promising a été relu : ses détails de coût sont pertinents mais moins pédagogiques que le contrepoint DOM ; remplacement documentaire sans modifier le périmètre adopté.')

start('D03.l')
emit('Retenir quelles quantités fournir à quelles dates rend la solution compréhensible pour le demandeur. Delivery Schedule Decision choisit un échéancier réalisable et acceptable, sans modifier à elle seule la demande ni confirmer l’engagement.','Une ou plusieurs échéances de satisfaction de la commande.','Choisir parmi les possibilités en respectant conditions et calendriers.',
'Microsoft Delivery schedules représente une commande livrée en plusieurs fois. Oracle Check Availability permet de travailler les dates d’expédition et d’arrivée avant leur application. Microsoft insiste sur la représentation des livraisons ; Oracle sur le choix des possibilités.\n\nFLOW nomme la décision qui retient l’échéancier. Deux dates de livraison n’imposent pas deux commandes ; la formalisation de la proposition puis sa confirmation gardent leur responsabilité.',
example('schedule','Illustration FLOW — une commande, deux dates','Pour 100 pièces demandées vendredi, les possibilités admissibles sont 60 vendredi et 40 lundi.','L’échéancier retient ces deux quantités si les conditions du client l’acceptent.','La représentation en plusieurs échéances, illustrée par Microsoft, ne décide pas du découpage en commandes.'),[
c('schedule','Delivery schedules','Dates et quantités de livraisons successives.','Représenter plusieurs échéances sous une commande.','La satisfaction peut être répartie dans le temps.','Le document gère également les lignes et documents de livraison.','FLOW isole le choix avant son enregistrement et sa confirmation.'),
c('check','Scheduled ship and arrival dates','Possibilités de dates d’une ligne.','Comparer puis retenir des dates.','Expédition et réception sont distinguées.','Oracle regroupe exploration et application dans un parcours.','FLOW laisse chaque effet à sa responsabilité.')])

start('D03.m')
emit('Déterminer quelles commandes passent avant les autres rend les pénuries arbitrables. Order Prioritization produit des priorités justifiées ; elle ne crée pas les ressources et ne lève pas une réservation.','Commandes concurrentes et critères applicables.','Distinguer obligations, préférences et conflits restant à résoudre.',
'SAP BOP utilise des règles pour réordonner les besoins lors d’une pénurie. PeopleSoft ordonne également les lignes avant de distribuer les quantités. Les deux montrent que l’ordre d’examen influence qui sera servi.\n\nFLOW sépare la priorité du plan qui en découle : être prioritaire ne détermine pas seul les quantités, les dates ou les ressources effectivement affectées. Aucun classement par client, chiffre d’affaires ou ancienneté n’est présumé universel.',
example('bop','SAP — une commande prioritaire arrive en pénurie','SAP décrit l’arrivée d’une commande d’un client prioritaire alors que le stock est limité.','BOP peut réexaminer les confirmations d’autres commandes selon les règles définies.','FLOW en tire la nécessité d’une priorité explicite, puis d’un examen séparé de la faisabilité et des engagements modifiables.'),[
c('bop','Reprioritization','Besoins de vente et de transfert.','Reclasser selon les règles de confirmation.','Réexaminer la priorité quand le contexte évolue.','BOP applique aussi des changements de confirmation.','FLOW ne confond pas classement et application.'),
c('ps','Inventory priority rank','Lignes à réserver ou promettre.','Trier avant distribution.','La priorité influence l’accès à une ressource limitée.','Le classement PeopleSoft sert un traitement précis.','FLOW porte une priorité métier exploitable par les décisions concernées.')])

start('D15')
emit('Dire ce qui pourra être fourni, quand et sous quelles conditions rend la réponse aux commandes fiable. Order Promising réunit l’étude des possibilités, les choix de promesse et le maintien des propositions et engagements.','Possibilités, coûts, échéancier et engagement de satisfaction.','Séparer ce qui est possible, proposé puis confirmé.',
'Microsoft utilise Order promising pour les dates de livraison calculées. Oracle Global Order Promising ajoute une recherche de sources, des alternatives et des règles de coût. Le même vocabulaire recouvre donc des périmètres produits différents.\n\nFLOW retient un domaine métier centré sur la réponse faite à la demande. Le plan global d’affectation reste coordonné avec Fulfillment Optimization, et la [promesse](glossary:TER014) n’est ni un mouvement physique ni une réservation automatique.',
example('check','Oracle — examiner avant d’engager','Dans Check Availability, une ligne dispose d’un résultat de disponibilité que l’utilisateur peut faire évoluer.','Oracle indique que les changements ne sont appliqués qu’au moment de Schedule.','Cette séparation illustre le passage d’une possibilité à une réponse retenue ; FLOW garde ses propres conditions de confirmation.'),[
c('atp','Order promising','Dates de départ et d’arrivée.','Calculer selon la méthode choisie.','Répondre à la demande avec une date réalisable.','Le document est centré sur le calcul des dates.','FLOW couvre aussi proposition, confirmation et révision.'),
c('gop','Global Order Promising','Choix d’une solution de satisfaction.','Combiner disponibilité, alternatives et coût.','Relier promesse et ressources mobilisables.','Oracle intègre des choix répartis dans plusieurs responsabilités FLOW.','Le domaine FLOW reste indépendant du produit.')])

start('D03')
emit('Construire un plan de satisfaction cohérent évite que plusieurs commandes comptent sur les mêmes ressources. Fulfillment Optimization rapproche priorités, scénarios et affectations pour rechercher le meilleur compromis métier.','Arbitrage des commandes et mise en place des affectations retenues.','Composer service, engagements, coûts et risques sans pondération implicite.',
'Microsoft DOM présente l’optimisation de satisfaction par commande ou par lot. Oracle Backlog Management travaille le carnet et les priorités ; son plan utilise les ressources connues sur le périmètre considéré. Tous deux dépassent une réponse isolée de disponibilité.\n\nFLOW regroupe les responsabilités de priorité, plan, travail des scénarios et affectation. Les promesses restent coordonnées avec Order Promising : leur distinction repose sur l’effet métier, sans frontière artificielle entre individuel et collectif.',
example('backlog','Illustration FLOW — deux commandes pour le même stock','Deux commandes demandent chacune 60 pièces alors que 80 sont admissibles.','Un plan commun rend les parts compatibles et explicite les 40 pièces non couvertes.','Oracle souligne le besoin de considérer ensemble les demandes partageant une offre ; les quantités illustrées et la politique restent propres au cas FLOW.'),[
c('dom','Fulfillment optimization','Satisfaction d’une commande ou d’un lot.','Combiner sources, règles et objectifs.','Rechercher un compromis entre besoins concurrents.','Le produit fournit un solveur et des stratégies déterminées.','FLOW ne prescrit ni algorithme ni objectif unique.'),
c('backlog','Backlog Management','Carnet à replanifier avec l’offre récente.','Répartir selon des priorités explicites.','Préserver la cohérence des demandes partageant une ressource.','La fonction Oracle associe calcul et tenue de résultats planifiés.','FLOW distingue décision, travail des scénarios et affectation.')],notes='Les écrans d’ordres planifiés et les détails ATP/BOP ne justifient pas le domaine à sa propre maille ; ils restent documentés dans les capacités concernées.')

start('BHV001')
emit('Calculer ce qui reste mobilisable exige de tenir compte de ce qui est déjà engagé ou protégé. Existing Commitment Consideration rend ce décompte explicite pour la demande considérée, sans compter deux fois le même engagement.','Réservations, protections et allocations applicables au calcul ATP.','Déterminer les quantités admissibles sans changer les droits existants.',
'SAP montre comment une protection limite la quantité accessible à une demande. PeopleSoft montre comment les demandes promises participent au calcul de disponibilité. Protection et promesse sont deux prises en compte différentes : les soustraire indistinctement peut masquer leurs bénéficiaires ou compter deux fois le même besoin.\n\nFLOW regroupe leur examen dans ATP. Une quantité protégée pour un groupe peut rester disponible pour ses membres ; la règle précise de décompte dépend du contexte et reste à expliciter.',
example('sup','Illustration FLOW — protéger sans retrancher deux fois','Sur 100 pièces, 30 sont protégées pour un groupe ; une commande de ce groupe en mobilise déjà 20.','Le calcul distingue la protection restante de l’engagement de la commande, au lieu de déduire mécaniquement 30 puis 20.','SAP illustre la prise en compte des protections ; les nombres sont un cas FLOW, pas une formule SAP.'),[
c('sup','Supply Protection in Product Availability Check','Quantités protégées par groupe et période.','Limiter la disponibilité selon les bénéficiaires.','Le stock visible n’est pas admissible pour toute demande.','La source traite les protections SAP, pas toutes les formes d’engagement.','FLOW rapproche les droits applicables avant de conclure.'),
c('ps','Cumulative ATP demand','Demandes déjà promises.','Les inclure dans la disponibilité restante.','Éviter de promettre une quantité déjà engagée ailleurs.','La procédure PeopleSoft possède ses propres règles de consommation.','FLOW explicite le décompte, sans importer une formule universelle.')])

start('BHV002')
emit('Chercher le stock dans tous les lieux admissibles élargit les possibilités de réponse à une commande. Network Stock Availability décrit cette recherche dans le réseau, sans supposer que tout magasin ou entrepôt peut servir toute demande.','Lieux de stockage déjà admissibles dans la référence.','Appliquer les conditions de service et d’éligibilité existantes.',
'Microsoft IFO présente entrepôts, magasins et autres sources dans une même recherche. Oracle Global Order Promising décrit aussi un réseau de sites mobilisables. Les deux ouvrent la recherche au-delà d’un stock local, avec des règles de sélection.\n\nFLOW garde ici l’information de faisabilité sur les lieux déjà admissibles. Choisir la meilleure source relève des décisions appropriées ; rendre admissible une autre solution peut demander un examen CTP.',
example('ifo','Microsoft — des sources différentes selon les commandes','Microsoft illustre une stratégie B2B limitée aux centres de distribution et une stratégie B2C ouverte aussi aux magasins.','Une quantité située en magasin ne fait donc pas partie des mêmes possibilités pour les deux stratégies.','FLOW retient que le type de lieu ne suffit pas : son admissibilité dépend du contexte de la demande.'),[
c('ifo','Fulfillment sources','Entrepôts, magasins et autres sources.','Chercher dans une liste de lieux autorisés.','La disponibilité se lit à l’échelle du réseau.','IFO détermine aussi une source optimale.','Ce comportement ATP établit les possibilités, sans refaire le choix du plan.'),
c('gop','Fulfillment locations','Sites et circuits de fourniture.','Appliquer les règles de recherche de sources.','Des lieux différents peuvent contribuer à une même demande.','GOP couvre aussi apport nouveau et substitution.','FLOW limite ce comportement aux lieux déjà admissibles.')])

start('BHV003')
emit('Savoir quand un stock peut réellement être mobilisé évite de promettre un départ impossible. Operational Availability Timing intègre préparation, ouvertures et heures limites connues au calcul des dates possibles.','Délai réel entre ressource disponible et possibilité de satisfaction.','Utiliser les informations des exécutants et signaler les incertitudes.',
'Microsoft distingue le délai de préparation dans ATP + Issue margin et, dans Fulfillment and Returns Optimization, les heures limites d’entrepôt. Oracle Database Promising tient compte du délai après réception. Les sources regardent le même problème depuis des étapes différentes.\n\nFLOW rassemble les contraintes de temps utiles au calcul ATP. Il ne gère pas les calendriers maîtres, ne pilote pas le prélèvement et ne retient pas à lui seul la date qui sera engagée.',
example('returns','Microsoft — le camion du jour est déjà parti','Le document Microsoft décrit des entrepôts dont les camions partent à des heures limites différentes.','La recherche peut écarter un entrepôt trop tardif et examiner un autre lieu encore ouvert.','La présence du stock ne suffit pas à rendre un départ possible ; FLOW consomme cette contrainte opérationnelle.'),[
c('returns','Respect warehouse timings','Heures limites des entrepôts.','Vérifier si le traitement peut encore démarrer.','Une ressource présente peut être trop tardive.','La fonction effectue aussi un choix de source.','FLOW utilise la contrainte sans absorber le choix de service.'),
c('database','Postprocessing lead time','Délai entre réception et expédition possible.','Décaler la date selon la mobilisation nécessaire.','Arrivée physique et utilisabilité immédiate diffèrent.','Le calcul Oracle dépend du flux configuré.','FLOW conserve origine et validité du délai.')])

start('BHV004')
emit('Intégrer les arrivages attendus permet d’annoncer une fourniture future réaliste. Future Supply Projection rapproche ces ressources des consommations déjà prévues, sans créer d’approvisionnement par le calcul.','Ressources futures déjà prévues et admissibles sur l’horizon.','Examiner quantité, échéance et besoins concurrents ensemble.',
'Microsoft ATP calcule les réceptions et consommations au fil des dates. Oracle distingue également offre future promettable et stock déjà reçu : l’une peut exister sans l’autre. Ces lectures éclairent le même horizon avec des effets différents.\n\nFLOW conserve la projection dans ATP tant que l’apport appartient à la référence. Une possibilité d’approvisionnement supplémentaire relève de CTP ; une projection n’est pas une preuve de réception.',
example('sync','Oracle — promettable au jour 30, absent au jour 1','Oracle décrit 10 unités demandées au jour 30 et un achat de 20 unités attendu au jour 28.','La promesse peut s’appuyer sur l’achat futur alors qu’une réservation de stock présent échoue au jour 1.','FLOW distingue disponibilité future, promesse et réservation ; l’exemple ne prescrit pas son mécanisme de réservation.'),[
c('atp','Planned receipts in ATP','Réceptions et sorties prévues.','Calculer la quantité disponible à chaque échéance.','Un arrivage peut soutenir une date future.','Microsoft fixe une méthode et un horizon de calcul.','FLOW ne suppose pas tous les arrivages admissibles.'),
c('sync','Future available-to-promise supply','Offre attendue avant la demande.','Distinguer cette offre du stock présent.','Une possibilité future n’est pas une réception réalisée.','Le document porte sur la synchronisation de produits Oracle.','FLOW garde la distinction métier, indépendamment des échanges techniques.')])

start('D03.n')
emit('Tenir ce qui est proposé puis réellement promis évite de confondre une option avec un engagement pris. Fulfillment Commitment porte les quantités, dates et conditions de satisfaction ainsi que leurs révisions autorisées.','Propositions, confirmations et révisions de satisfaction.','Conserver distincts demande, réponse envisagée et engagement confirmé.',
'Oracle Check Availability sépare le résultat exploré de son application. SAP BOP décrit le réexamen de confirmations déjà données. Ces documents éclairent deux moments de la vie d’une réponse : sa préparation et son évolution.\n\nFLOW les réunit sous Fulfillment Commitment, sans refaire les décisions de faisabilité ni d’échéancier. La confirmation documentaire d’une commande chez Microsoft est un usage plus large du mot confirmation ; elle ne suffit pas à définir cette responsabilité.',
example('check','Illustration FLOW — confirmer une part de la proposition','Une solution propose 60 pièces vendredi et 40 lundi pour une demande de 100.','Seules les 60 du vendredi sont confirmées ; les 40 restent proposées.','Le passage de l’exploration à l’application est documenté par Oracle ; FLOW précise ici la part engagée sans réservation implicite.'),[
c('check','Schedule an availability result','Résultat retenu après exploration.','Appliquer la réponse choisie.','Un résultat affiché n’est pas encore appliqué.','Schedule transmet des données de commande dans Oracle.','FLOW isole l’engagement de satisfaction des autres changements d’Order.'),
c('bop','Order confirmations','Quantités déjà confirmées.','Réexaminer les confirmations après changement.','Les engagements doivent rester lisibles quand la situation évolue.','BOP rassemble contrôle, arbitrage et modification.','FLOW réserve la révision à une modification autorisée.')],notes='Confirm sales orders relu : confirme un document de commande, avec contrôle de crédit, sans décrire à lui seul le contrat de promesse. Remplacé par Check Availability, plus précis sur proposition/application.')

start('BHV021')
emit('Présenter une quantité et une date envisageables permet d’échanger avec le demandeur avant de s’engager. Promise Proposal formalise le résultat des décisions utiles sans confirmer la promesse.','Solution proposée et conditions de satisfaction.','Rendre l’option lisible sans refaire la faisabilité ni l’échéancier.',
'Oracle Check Availability conserve des résultats exploratoires tant que la ligne n’est pas planifiée. Microsoft Delivery alternatives rend comparables plusieurs possibilités. Les deux rendent une option visible avant sa sélection, avec des parcours produits différents.\n\nFLOW retient ce bénéfice de dialogue : la proposition présentée doit rester explicitement non confirmée. Elle n’est ni une affectation de ressource ni une réservation.',
example('check','Oracle — comparer avant de planifier','L’exemple Oracle oppose l’article demandé, disponible le 10 mars, à un substitut autorisé disponible le 1er mars.','La modification reste exploratoire tant que l’utilisateur ne planifie pas la ligne.','FLOW formalise la solution proposée et ses conditions ; il ne déduit pas un accord du seul résultat affiché.'),[
c('check','Availability result','Article, quantité et date envisageables.','Explorer sans appliquer avant Schedule.','La possibilité reste distincte du résultat engagé.','Le parcours Oracle inclut calcul et application.','Promise Proposal présente un résultat déjà établi par les décisions.'),
c('alternatives','Delivery alternatives','Options de livraison comparables.','Présenter dates, quantités et transport.','Rendre plusieurs réponses compréhensibles.','L’écran comprend aussi recherche et sélection.','FLOW nomme le moment de formalisation, sans en faire un écran.')])

start('BHV022')
emit('Établir clairement la part promise permet à chacun de savoir sur quoi il peut compter. Promise Confirmation fait passer les quantités et dates autorisées du statut de proposition à celui d’engagement.','Part confirmée et part restant non confirmée.','Confirmer selon les conditions applicables, sans déduire une réservation.',
'SAP BOP distingue les quantités confirmées de celles qui ne le sont pas. Oracle Check Availability distingue les résultats explorés de ceux transmis après planification. Les deux donnent un effet différent à une simple possibilité et à une réponse appliquée.\n\nFLOW précise cet effet comme un [engagement](glossary:TER013) de satisfaction. Il ne suppose ni réception du stock, ni départ physique, ni blocage automatique de la ressource.',
example('bop','Illustration FLOW — 60 confirmées sur 100','Une commande demande 100 pièces, mais les conditions permettent de confirmer seulement 60 vendredi.','Les 60 sont promises ; les 40 restantes restent visibles comme non confirmées.','SAP illustre l’existence de parts confirmées et non confirmées ; la règle autorisant cette confirmation relève du cas FLOW.'),[
c('bop','Order confirmations','Quantités confirmées ou non.','Établir un résultat de confirmation.','Distinguer une part servie de la demande encore sans confirmation.','Le traitement SAP choisit et applique en un même parcours.','FLOW ne redécide pas la priorité dans ce comportement.'),
c('check','Schedule the order line','Résultat choisi pour application.','Passer de l’exploration à la ligne planifiée.','Le résultat n’a pas le même effet avant et après application.','Schedule n’est pas une définition universelle de confirmation.','La confirmation FLOW conserve un contrat métier propre.')])

start('BHV023')
emit('Réexaminer une promesse quand la situation change permet de traiter l’écart avant qu’il devienne une mauvaise surprise. Promise Revision établit les modifications autorisées et conserve leur effet sur les quantités et dates engagées.','Engagements affectés par les ressources, demandes ou priorités.','Mobiliser les décisions utiles puis tenir la révision autorisée.',
'SAP BOP peut redistribuer des confirmations après une pénurie ou un nouvel arrivage. Microsoft Order promising décrit un recalcul lorsque l’ancienne date ne peut plus être tenue, mais pas automatiquement lorsqu’une date meilleure devient possible. Les déclencheurs diffèrent.\n\nFLOW ne choisit pas une règle automatique universelle : le changement appelle un réexamen et l’application des autorisations. Changer la ressource affectée peut laisser la promesse inchangée, et l’inverse est possible.',
example('atp','Microsoft — une date devenue intenable','Dans l’exemple Microsoft, une hausse de quantité rend impossible le 20 juillet et reporte la possibilité au 25.','Le calcul est relancé ; à l’inverse, une baisse de quantité permettant le 15 ne remplace pas automatiquement le 20.','FLOW sépare évolution des possibilités et décision de réviser l’engagement.'),[
c('bop','Reconfirmation','Confirmations après changement d’offre.','Réexaminer selon les règles.','Un engagement peut devenir inadéquat.','BOP peut aussi déconfirmer et redistribuer.','FLOW rend explicite le périmètre révisable.'),
c('atp','Order promising update','Date devenue irréalisable.','Relancer le calcul dans les cas décrits.','La modification d’une demande peut affecter sa promesse.','Le produit impose un déclencheur particulier.','FLOW conserve une règle de révision à préciser selon le contexte.')])

start('BHV045')
emit('Mettre en place les liens prévus dans un plan permet de concrétiser le choix retenu. Supply Assignment Plan Application contrôle ce qui reste applicable et rend visibles les écarts, sans remplacer silencieusement le plan.','Affectations d’un plan retenu aux commandes concernées.','Appliquer les liens et signaler les impossibilités aux décisions responsables.',
'SAP Supply Assignment matérialise des liens de ressources aux commandes. Son parcours distingue aussi résultats simulés et exécutés. Ces deux documents montrent un passage du scénario à l’action, mais ne prouvent pas l’importation de tout plan externe.\n\nFLOW explicite ce passage comme une responsabilité. Préserver des liens ou en réviser certains peut faire partie de l’application ; le plan n’autorise ni réservation implicite ni modification d’Order par défaut.',
example('arun','Illustration FLOW — un plan partiellement applicable','Le plan retient 60 pièces présentes et 40 sur un arrivage ; au moment de l’application, 10 de cet arrivage ne sont plus admissibles.','Les liens applicables et l’écart de 10 sont rendus visibles pour un nouvel arbitrage.','SAP documente l’affectation et ses résultats ; le traitement exact de cet écart est une illustration FLOW.'),[
c('arun','Supply Assignment','Liens entre ressources et commandes.','Matérialiser les affectations dans le traitement.','Le choix doit devenir un lien exploitable.','ARun peut aussi déterminer le choix et contrôler la libération.','FLOW isole l’application du plan retenu.'),
c('workflow','Executed and simulated assignment runs','Résultats simulés, exécutés ou incomplets.','Distinguer scénario et résultat appliqué.','Une simulation ne prouve pas une affectation effective.','La page ne démontre pas l’import d’un plan arbitraire.','FLOW exige la traçabilité de l’application et de ses écarts.')])

start('BHV046')
emit('Compléter le manque sans défaire ce qui est déjà affecté stabilise la préparation des commandes. Incremental Supply Assignment préserve les liens existants et traite le reliquat, sans créer un gel durable.','Besoins restant sans affectation.','Compléter les liens en conservant ceux du périmètre préservé.',
'SAP fournit un exemple direct : sans réaffectation, 70 pièces déjà affectées sont conservées et les 30 manquantes sont examinées. Microsoft préserve également des liens pour les demandes confirmées, mais dans une chaîne de planification plus large.\n\nFLOW nomme le bénéfice métier de stabilité. Incremental ne prescrit pas un algorithme ; si un lien conservé devient irréalisable, l’exception appelle un arbitrage plutôt qu’une révision silencieuse.',
example('reassign','SAP — conserver 70 et compléter 30','Une ligne demande 100 pièces ; 70 sont déjà affectées.','Sans option Reassignment, SAP conserve les 70 et recherche les 30 supplémentaires.','FLOW retient la politique de conservation pendant ce traitement, sans en déduire un gel permanent.'),[
c('reassign','Assignment without Reassignment','Part non encore affectée.','Conserver l’existant et examiner le reliquat.','Même mécanisme de complément.','La source décrit un paramètre d’un traitement SAP.','FLOW décrit le comportement métier indépendamment de ce paramètre.'),
c('keep','Keep supply for confirmed demand','Couverture des demandes confirmées.','Conserver des liens entre passages de planification.','Limiter les changements inutiles.','Microsoft conserve aussi ordres, routes et capacités selon configuration.','FLOW limite ce comportement à la préservation des affectations.')])

start('BHV047')
emit('Changer les ressources liées aux commandes permet d’appliquer un nouvel arbitrage sans réécrire leur demande. Supply Reassignment révise seulement les affectations modifiables et respecte les engagements, réservations et gels.','Liens de ressources dont la révision est autorisée.','Appliquer les nouveaux liens en préservant les restrictions.',
'SAP Reassignment peut remettre en jeu toutes les quantités d’une ligne. Microsoft Keep supply for confirmed demand montre le choix inverse : préserver la couverture de demandes confirmées, avec des règles particulières au stock reçu. Les sources éclairent la frontière entre révisable et protégé.\n\nFLOW reprend Reassignment sans imposer une suppression et reconstruction complète. La [réaffectation](glossary:VER018) applique le choix ; elle ne donne pas à elle seule le droit de dégrader une promesse.',
example('reassign','SAP — réexaminer les 100 pièces','Une ligne de 100 pièces possède déjà 70 pièces affectées.','Avec Reassignment, SAP remet en jeu l’affectation de la ligne entière.','FLOW peut réviser seulement les liens utiles ; le périmètre révisable doit rester explicite.'),[
c('reassign','Reassignment','Affectations déjà présentes.','Réexaminer les liens d’une ligne.','Une nouvelle répartition remplace des liens existants.','Le mécanisme SAP décrit une remise en jeu complète.','FLOW n’impose pas ce mode d’application.'),
c('keep','Preservation of pegged supply','Couverture de demandes confirmées.','Restreindre la replanification des liens.','Une révision doit respecter les protections applicables.','La préservation Microsoft dépend de règles de planification.','FLOW distingue préservation, gel, réservation et promesse.')])

start('D03.o')
emit('Choisir ensemble les ressources destinées aux commandes produit un plan dont les engagements sont compatibles. Fulfillment Plan Decision construit ce scénario avec les décisions spécialisées, en explicitant les besoins non satisfaits.','Scénario cohérent de ressources, quantités et dates pour le périmètre examiné.','Rechercher une valeur multidimensionnelle sans formule ni optimum garanti.',
'Microsoft IFO produit un fulfillment plan indiquant les sources et quantités retenues. Oracle Backlog Planning répartit l’offre sur le carnet selon des priorités. Microsoft met en avant les sources et contraintes ; Oracle, la replanification des demandes concurrentes.\n\nFLOW reprend l’exigence de cohérence du [plan d’affectation](glossary:TER078), sans confondre stratégie et résultat. Décider le plan ne l’applique pas, ne confirme pas la promesse et ne réserve pas les ressources.',
example('ifo','Illustration FLOW — éviter deux réponses incompatibles','Deux commandes de 80 pièces pourraient chacune sembler couvertes par un stock commun de 100.','Le plan retient une combinaison compatible et montre les 60 pièces encore sans ressource.','Le plan de fulfillment Microsoft inspire la représentation d’un résultat commun ; les nombres ne prescrivent aucune répartition FLOW.'),[
c('ifo','Fulfillment plan','Sources et quantités par ligne.','Choisir une combinaison sous contraintes.','Le résultat explicite ce qui est couvert ou non.','IFO documente une stratégie de proximité.','FLOW conserve plusieurs dimensions de valeur sans priorité implicite.'),
c('backlog','Backlog plan','Demandes partageant les ressources collectées.','Replanifier la satisfaction selon les priorités.','Le périmètre doit préserver la cohérence des ressources communes.','Le traitement Oracle comprend sa propre tenue de résultats.','La décision FLOW produit un scénario, distinct de son application.')],notes='Le second document Microsoft était très proche du premier ; remplacé par le contrepoint Oracle pour comparer deux approches du résultat collectif.')

start('BHV075')
emit('Évaluer un apport supplémentaire permet de savoir si la quantité manquante peut être obtenue à temps. Additional Supply Feasibility établit quantités, dates et conditions sans créer automatiquement l’achat ou la fabrication.','Ressources supplémentaires envisagées hors de la référence.','Interroger leurs possibilités et expliciter les conditions d’obtention.',
'Microsoft CTP vérifie les matières et moyens de fabrication. Oracle Global Order Promising distingue l’offre existante de celle qu’il faut produire, acheter ou transférer. Les deux examinent un moyen de combler un manque, avec des périmètres produits différents.\n\nFLOW retient ici l’hypothèse d’apport supplémentaire. Un arrivage déjà prévu appartient à ATP ; obtenir un apport pour une commande ne se confond pas avec décider un stock cible.',
example('ctp','Microsoft — un produit sans stock, des composants disponibles','L’article A n’a aucun stock ; Microsoft examine les composants B et C et les moyens de les assembler.','La disponibilité de A peut devenir positive si les moyens nécessaires sont disponibles à temps.','FLOW retient une possibilité conditionnelle, sans ordre de fabrication créé par ce seul constat.'),[
c('ctp','CTP material and capacity check','Produit à fabriquer et ressources nécessaires.','Évaluer la quantité réalisable.','Un manque peut être comblé par un apport nouveau.','Le cas Microsoft est industriel.','FLOW couvre les apports pertinents à la commande.'),
c('gop','Create new supply with CTP','Apport à produire, acheter ou transférer.','Établir une solution de fourniture supplémentaire.','Distinguer offre déjà prévue et offre à obtenir.','GOP peut ensuite alimenter d’autres applications.','FLOW sépare faisabilité, autorisation et création de l’Order.')])

start('BHV076')
emit('Examiner une autre façon de servir la commande ouvre des solutions quand la référence ne suffit plus. Fulfillment Alternative Feasibility décrit leurs conditions et conséquences, avec les décisions responsables des services et équivalences.','Modalités de satisfaction qui nécessitent une adaptation.','Vérifier leur admissibilité et leur faisabilité sans les appliquer.',
'SAP ABC explore des sites et produits alternatifs. Microsoft Delivery alternatives compare aussi transports, dates et quantités. Tous deux rendent visibles plusieurs réponses, mais leur qualification ATP ou CTP dépend du produit.\n\nFLOW utilise un critère explicite : ce qui était déjà admissible dans la référence reste ATP. Un produit ressemblant ne devient pas un substitut autorisé ; le choix du service garde son responsable.',
example('alternatives','Illustration FLOW — envisager une livraison express','Le service standard ne permet pas de respecter la date ; un service express pourrait l’atteindre.','La possibilité reste conditionnée à la capacité et à l’autorisation de ce service.','Microsoft montre la comparaison de modes de transport ; FLOW qualifie séparément l’adaptation et son choix.'),[
c('abc','Alternative-Based Confirmation','Sites ou articles alternatifs.','Chercher une réponse compatible.','L’option initiale n’est pas toujours la seule.','ABC relève d’aATP chez SAP.','FLOW ne classe pas toute alternative en CTP.'),
c('alternatives','Delivery alternatives','Transport, lieu, quantité et date.','Comparer les options présentées.','Un changement de modalité peut améliorer la satisfaction.','La page mêle des possibilités déjà admises et des adaptations.','FLOW précise ce qui doit changer pour rendre l’option possible.')])

start('BHV077')
emit('Mesurer l’effet d’un rééquilibrage d’engagements permet de discuter une urgence sans déplacer le problème à l’aveugle. Commitment Rebalancing Feasibility expose quelles possibilités s’ouvrent et quelles commandes seraient affectées.','Engagements dont une révision pourrait être autorisée.','Établir impacts et conditions avant arbitrage et application.',
'SAP BOP peut modifier les confirmations selon les priorités. Oracle Backlog Management permet de simuler des changements sans modifier immédiatement les dates visibles des clients. SAP décrit un traitement de redistribution ; Oracle rend particulièrement visible l’étape de simulation.\n\nFLOW isole l’examen conditionnel : une urgence ne prouve pas la modifiabilité d’une promesse. Le choix collectif, la révision de promesse et la réaffectation des ressources restent distincts.',
example('actions','Illustration FLOW — décaler une commande pour en servir une autre','Une commande urgente serait satisfaisable si une autre acceptait deux jours de décalage.','Le scénario explicite ce décalage et reste hypothétique jusqu’à l’autorisation correspondante.','Oracle étaye la séparation simulation/application ; aucune priorité ni autorisation client n’est présumée dans le cas FLOW.'),[
c('bop','Redistribution of confirmations','Confirmations de demandes concurrentes.','Réexaminer selon disponibilité et priorité.','Un changement pour l’une peut affecter l’autre.','BOP peut appliquer la nouvelle répartition.','FLOW s’arrête ici aux possibilités et conséquences.'),
c('actions','Enforce Current Commit simulation','Engagements existants dans un scénario.','Tester sans changer la planification visible au client.','Évaluer un compromis avant sa mise en action.','Le paramètre Oracle ne vaut pas autorisation métier universelle.','FLOW exige que les engagements réellement modifiables soient établis.')])

start('D03.p')
emit('Travailler les scénarios du carnet permet de préparer une satisfaction cohérente des commandes. Order Backlog Planning organise les hypothèses, leurs comparaisons et la préparation du scénario retenu en mobilisant les décisions utiles.','Scénarios du carnet et préparation de leur prise en charge.','Comparer les conséquences puis préparer les actions autorisées.',
'Oracle Backlog Management permet de simuler, comparer et préparer les résultats à transmettre. SAP propose aussi la comparaison de traitements d’affectation simulés. Les deux séparent l’examen d’un scénario de son exécution effective.\n\nFLOW nomme le travail de préparation, humain, automatisé ou mixte. Les décisions établissent les scénarios ; la libération des Orders, les affectations et les promesses gardent leurs responsabilités respectives.',
example('actions','Oracle — comparer avant de transmettre','Dans Backlog Analysis, l’utilisateur peut changer une règle de priorité et relancer le plan.','Il examine les résultats, les enregistre puis sélectionne ceux à transmettre à la gestion des commandes.','FLOW retient ce travail de scénario sans attribuer à Planning toute l’autorité d’engagement.'),[
c('actions','Interactive backlog planning','Hypothèses et résultats du carnet.','Simuler, comparer et préparer la transmission.','Préparer un scénario avant sa prise en charge.','Le parcours Oracle possède ses propres actions de release.','FLOW mobilise Order Release sans l’absorber.'),
c('workflow','Compare simulated assignment runs','Plusieurs simulations d’affectation.','Comparer les résultats pour retenir une option.','Un scénario peut être examiné avant son application.','Le document SAP reste centré sur ARun.','FLOW prépare le carnet au-delà d’un seul traitement produit.')],notes='Planned orders simplified et Start Backlog Planning relus : l’un porte l’affermissement de ressources, l’autre un calcul planifié. La comparaison SAP/Oracle retenue explicite mieux le travail de scénarios à cette maille.')

start('TER009')
emit('La disponibilité indique quelle quantité peut servir un usage à une date donnée. Nous gardons ce sens contextualisé : un stock présent n’est pas nécessairement mobilisable pour toute demande.','Quantité admissible pour un usage et un horizon.','Lire ressources, engagements et règles ensemble.',
'Microsoft distingue le stock physique disponible et la disponibilité future calculée. Oracle distingue aussi ce qui est promettable de ce qui est déjà présent pour réservation. Le mot disponibilité dépend donc de la question posée.\n\nFLOW exige d’indiquer l’usage, la date et les conditions. Une réponse positive n’engage pas automatiquement la quantité et ne prouve pas sa réception.',
example('sync','Oracle — disponible pour plus tard','Une réception attendue au jour 28 peut couvrir une demande du jour 30.','Elle ne constitue pourtant pas du stock présent réservable au jour 1.','Toujours qualifier de quelle disponibilité on parle.'),[
c('alternatives','Available today / Future availability','Disponibilité présente ou future.','Afficher les quantités dans leur contexte.','L’horizon change la réponse.','Microsoft distingue plusieurs mesures produit.','FLOW conserve le sens sans imposer ces écrans.','Appui sémantique'),
c('sync','Item availability / on-hand availability','Promettable et physiquement présent.','Rapprocher deux vues de disponibilité.','La même quantité peut avoir des usages différents.','La source traite une synchronisation Oracle.','Le terme FLOW n’est pas une mesure unique.','Appui sémantique')])

start('TER013')
emit('Un engagement précise ce qui est tenu envers une demande ou un usage, pour quel bénéficiaire et sous quelles conditions. Ce mot doit être qualifié : engagement de fourniture, de ressource et d’exécution n’ont pas automatiquement les mêmes effets.','Décision tenue et conditions qui l’accompagnent.','Identifier l’objet engagé, sa fermeté et ses possibilités de révision.',
'Microsoft parle de customer commitments liés aux dates confirmées et à leur couverture. Oracle sépare les résultats simulés des engagements de planification effectivement modifiés. Les deux distinguent une hypothèse de ce sur quoi l’on doit compter.\n\nFLOW utilise engagement comme notion plus générale. Une réservation protège un usage ; une promesse porte sur une fourniture. Leur association éventuelle doit être explicite.',
example('keep','Illustration FLOW — conserver ce qui soutient la date promise','Une date a été confirmée et un arrivage lui est lié.','Un nouveau plan doit rendre visible ce qu’il préserve ou remet en question.','Microsoft documente une politique de préservation ; FLOW ne la transforme pas en fermeté universelle de tout engagement.'),[
c('keep','Customer commitments','Dates confirmées et chaîne de couverture.','Préserver les éléments qui les soutiennent.','Un engagement produit des attentes à respecter.','Microsoft définit un cas de demande confirmée.','FLOW qualifie plusieurs natures d’engagement.','Appui sémantique'),
c('actions','Current commit','Dates actuelles à préserver ou simuler.','Distinguer plan envisagé et données appliquées.','Un scénario ne modifie pas encore l’engagement.','Le terme Oracle est propre au carnet planifié.','FLOW précise l’effet avant d’employer le mot.','Appui sémantique')])

start('TER014')
emit('Une promesse engage sur la fourniture attendue d’une demande, notamment une quantité et une date. Nous réservons ce mot à la réponse engagée ; une solution calculée ou présentée peut encore n’être qu’une proposition.','Engagement de satisfaction et conditions explicites.','Distinguer demande, possibilité, proposition et promesse prise.',
'Microsoft Order promising travaille les dates auxquelles les produits pourront être livrés. Oracle Check Availability emploie promising jusque dans l’exploration de résultats non appliqués. Le vocabulaire produit peut donc couvrir davantage que l’engagement déjà pris.\n\nFLOW précise ce niveau de fermeté pour éviter l’ambiguïté. Une promesse peut exister sans affectation à une ressource précise ; elle ne signifie pas que la livraison est réalisée.',
example('check','Illustration FLOW — proposer n’est pas encore promettre','Un résultat indique 60 pièces vendredi et 40 lundi.','Tant que cette réponse n’est pas confirmée selon les conditions applicables, elle reste une proposition.','Oracle distingue exploration et application ; FLOW explicite le mot correspondant à l’engagement.'),[
c('atp','Order promising','Dates possibles de fourniture.','Calculer une réponse à la demande.','Quantité et date expliquent la satisfaction attendue.','Promising désigne aussi une fonction de calcul.','Le nom commun promesse désigne ici l’engagement.','Appui sémantique'),
c('check','Promising result','Réponse explorée puis appliquée.','Séparer résultat et Schedule.','La possibilité et l’effet appliqué diffèrent.','Le mot promising couvre les deux étapes dans Oracle.','FLOW qualifie explicitement la proposition non confirmée.','Appui sémantique')])

start('TER015')
emit('La confirmation de promesse établit les quantités et dates sur lesquelles le demandeur peut compter. Elle doit être distinguée d’un simple accusé de réception ou d’une confirmation documentaire de commande.','Acte ou résultat qui établit l’engagement de satisfaction.','Identifier ce qui est confirmé et la part qui ne l’est pas.',
'SAP parle de confirmations de quantités dans BOP. Microsoft Confirm sales orders désigne un parcours documentaire de commande, avec statut et contrôle de crédit. Le même mot confirmation ne porte donc pas toujours le même effet.\n\nFLOW ajoute « de promesse » pour nommer précisément l’engagement de satisfaction. Confirmer ne prouve ni réservation, ni expédition, ni réalisation physique.',
example('confirm','Microsoft — un document confirmé','Le parcours Microsoft confirme une commande et lui donne le statut documentaire Confirmation.','Ce statut atteste l’action documentaire décrite.','Pour FLOW, il faut encore préciser les quantités et dates engagées ; le mot confirmation seul ne suffit pas.'),[
c('bop','Order confirmations','Quantités de demandes confirmées.','Réexaminer ce qui est confirmé.','Une confirmation porte une réponse de satisfaction.','BOP ajoute disponibilité et redistribution.','FLOW qualifie l’acte d’engagement.','Appui sémantique'),
c('confirm','Sales order confirmation','Document de commande.','Confirmer et éditer un document.','Le terme marque un changement de statut.','Ce statut ne définit pas à lui seul une promesse de fourniture.','Éviter l’équivalence fondée sur le seul mot confirmation.','Appui sémantique')])

start('TER017')
emit('Une affectation de ressource indique quelle ressource est retenue pour quelle demande. Nous utilisons Assignment pour ce lien, qui peut porter sur une ressource future et ne constitue pas à lui seul une réservation.','Lien identifié au degré de précision utile.','Conserver la ressource, le bénéficiaire et la quantité liée.',
'SAP Supply Assignment relie ressource et besoin ; Microsoft utilise pegging dans les chaînes de couverture. Les deux éclairent le lien, avec des mécanismes et effets différents. SAP associe notamment une protection contre d’autres usages à son affectation.\n\nFLOW sépare ces effets : l’affectation désigne le lien, la réservation bloque les usages concurrents. Allocation seul reste ambigu, car son sens dépend de la source.',
example('assign','Illustration FLOW — 40 pièces sur un arrivage','Une commande est liée à 40 pièces d’un achat attendu.','Le lien peut être maintenu quand l’arrivage devient stock reçu.','SAP fournit ce mécanisme de continuité ; FLOW conserve séparément réservation et promesse.'),[
c('assign','Supply-demand assignment','Besoin lié à une ressource.','Maintenir le lien au fil de la réception.','Même relation descriptive fondamentale.','Le lien SAP comporte aussi un effet de protection.','FLOW distingue ce lien de la réservation.','Appui sémantique'),
c('keep','Pegging information','Couverture reliant offre et demande.','Conserver les liens utiles à la demande.','Une ressource peut être future.','Le pegging décrit une chaîne de planification plus large.','FLOW ne suppose pas cette chaîne à chaque affectation.','Appui sémantique')])

start('TER044')
emit('ATP indique ce qu’une demande peut recevoir avec les ressources admissibles déjà présentes ou attendues. Dans FLOW, le terme nomme la décision qui établit les quantités, dates et couverture possibles, sans confirmer la promesse.','Possibilités dans la situation de référence.','Compter les consommations et engagements sur l’horizon.',
'Microsoft et PeopleSoft utilisent ATP pour une quantité disponible à promettre, calculée dans le temps. FLOW emploie aussi le sigle pour la capacité qui établit ces possibilités. Ce passage de la mesure à la responsabilité est explicite.\n\nLe stock futur n’est pas réservé à CTP : s’il est déjà prévu et admissible, il appartient à ATP. Protections et réservations existantes limitent la réponse ; le calcul n’en crée pas de nouvelles.',
example('atp','Illustration FLOW — l’arrivage compte dans ATP','Un arrivage attendu à sept jours peut couvrir une demande à soixante jours si les besoins concurrents le permettent.','ATP explicite la quantité utilisable à cette date.','Le calcul temporel Microsoft soutient le mécanisme ; les horizons sont une illustration FLOW.'),[
c('atp','Available-to-promise quantity','Quantité promettable à une date.','Calculer réceptions et consommations.','Ressources futures déjà prévues incluses.','ATP désigne ici principalement une mesure et son calcul.','FLOW nomme également la responsabilité de décision.','Appui sémantique'),
c('ps','Cumulative ATP','Solde promettable sur l’horizon.','Confronter ressources et demandes.','Les engagements concurrents réduisent les possibilités.','Le calcul est intégré à des traitements de promesse.','FLOW distingue la décision de son application.','Appui sémantique')])

start('TER045')
emit('CTP exprime ce qui pourrait être promis après une adaptation nécessaire de la situation. Dans FLOW, il couvre les possibilités d’apport, de solution alternative ou de rééquilibrage, avec leurs conditions et conséquences.','Faisabilité sous adaptation, sans application automatique.','Mobiliser les décisions responsables de chaque levier.',
'Microsoft CTP insiste sur matières et capacité de fabrication. SAP ABC traite les alternatives sous un autre nom. Ces usages prouvent des mécanismes voisins, pas une définition universelle de CTP.\n\nFLOW conserve un sens plus large de faisabilité sous adaptation. Une autre source déjà admissible reste ATP ; la révision d’une règle ou d’un engagement ne découle jamais du sigle seul.',
example('ctp','Microsoft — composants et capacité pour un article absent','Un article A n’est pas en stock, mais ses composants B et C peuvent être disponibles.','CTP examine aussi la capacité nécessaire pour produire A.','L’exemple illustre un des leviers couverts par le sens FLOW, sans épuiser son périmètre.'),[
c('ctp','Capable-to-promise','Fourniture réalisable par production.','Vérifier matières et capacité.','Tester comment rendre une demande satisfaisable.','Le sens Microsoft est centré sur la production.','FLOW couvre d’autres adaptations explicites.','Appui sémantique'),
c('abc','Alternative-Based Confirmation','Site ou produit alternatif.','Explorer une autre solution.','Une adaptation peut améliorer la réponse.','SAP ne nomme pas ce mécanisme CTP.','Le rapprochement est fonctionnel, pas lexical.','Appui sémantique')])

start('TER068')
emit('PTP désigne l’examen économique des promesses possibles. Nous conservons Profitable-to-Promise pour comparer coûts et conséquences économiques dans les conditions de service applicables, sans en faire une maximisation automatique du profit.','Arbitrage économique entre possibilités admissibles.','Exposer critères, hypothèses et informations manquantes.',
'Oracle emploie Profitable to Promise pour départager des solutions par leur coût selon ses priorités de délai. Microsoft DOM traite les objectifs économiques dans une optimisation plus large. Le vocabulaire Oracle est proche ; le découpage de responsabilité diffère.\n\nFLOW ne déduit du mot profitable ni une formule de marge ni une pondération générale. Le compromis collectif reste multidimensionnel et les coûts inconnus ne deviennent pas nuls.',
example('ptp','Illustration FLOW — économie sous condition de service','Deux solutions respectent le délai : une livraison accélérée à 120 et deux livraisons à 80.','L’écart économique peut éclairer le choix si les livraisons partielles sont acceptables.','Oracle étaye la comparaison coût/service ; les montants et conditions sont un cas FLOW.'),[
c('ptp','Profitable to Promise','Coûts de satisfaction.','Comparer les alternatives sous contrainte de délai.','Même question économique.','La politique Oracle ordonne précisément ses critères.','FLOW conserve les règles pertinentes au cas.','Appui sémantique'),
c('dom','Fulfillment cost objectives','Coûts dans l’optimisation des commandes.','Associer objectifs et contraintes.','Le coût est une dimension du choix.','DOM ne sépare pas une capacité PTP autonome.','Le terme FLOW nomme une responsabilité plus ciblée.','Appui sémantique')])

start('TER078')
emit('Un Supply Assignment Plan décrit les ressources, quantités et dates proposées ou retenues pour les commandes. Son statut doit dire s’il est seulement envisagé, choisi ou déjà appliqué.','Ensemble cohérent d’affectations avec hypothèses et contraintes.','Rendre visibles les liens proposés et le reste sans couverture.',
'Microsoft IFO produit un fulfillment plan détaillant les lignes couvertes ou non. Oracle Backlog Management distingue résultats planifiés et résultats transmis. Les deux aident à séparer contenu d’un plan et effet de son application.\n\nFLOW précise « Assignment » pour nommer un plan de liens aux ressources. Cet objet n’est pas un comportement supplémentaire et ne réserve pas par sa seule existence.',
example('ifo','Illustration FLOW — un plan avant application','Un stock de 100 pièces est proposé pour deux commandes à hauteur de 60 et 40.','Le plan expose ces liens, sa version et ses hypothèses ; leur mise en place reste identifiable séparément.','Le fulfillment plan Microsoft éclaire la représentation du résultat, sans imposer son mécanisme d’application.'),[
c('ifo','Fulfillment plan','Sources et quantités de chaque ligne.','Afficher couverture complète, partielle ou absente.','Le plan décrit un résultat cohérent.','Le produit retient ses propres sources et catégories.','FLOW précise les hypothèses et le statut du plan.','Appui sémantique'),
c('actions','Planned values','Résultats du scénario de carnet.','Enregistrer puis préparer la transmission.','Un résultat planifié n’est pas encore appliqué.','Les valeurs Oracle ne sont pas uniquement des liens d’affectation.','FLOW garde un objet centré sur ces liens.','Appui sémantique')])

start('VER005')
emit('Vérifier consiste à établir si des conditions sont respectées et à en donner le constat. Ce verbe ne signifie pas, à lui seul, autoriser ou exécuter l’action envisagée.','Conditions, éléments examinés et constat produit.','Rendre lisible la conclusion et ses limites.',
'Oracle Check Availability recherche une réponse possible avant application. SAP Release Check contrôle si les quantités affectées remplissent les conditions de départ. Les deux font un contrôle, mais pas sur la même question.\n\nFLOW garde un verbe général à qualifier par son objet : vérifier une disponibilité ou vérifier un seuil de livraison. L’effet d’autorisation éventuel doit être nommé séparément.',
example('assign','SAP — vérifier avant de rendre livrable','Une affectation existe, mais un contrôle de libération reste requis.','SAP compare les quantités aux règles et distingue notamment les situations nécessitant une libération manuelle.','Le constat favorable et l’autorisation peuvent être séparés ; le mot vérifier ne les confond pas.'),[
c('check','Check Availability','Possibilités de fourniture.','Produire un résultat exploratoire.','Établir un constat avant application.','Le contrôle inclut des calculs spécialisés.','Usage voisin ; pas définition normative du verbe.','Appui sémantique'),
c('assign','Release check','Conditions de quantité avant livraison.','Comparer résultat et règle applicable.','Qualifier une situation par rapport à une condition.','Le contrôle SAP s’inscrit dans un parcours de libération.','FLOW explicite séparément l’effet d’autorisation.','Appui sémantique')])

start('VER006')
emit('Autoriser rend une action admissible pour un périmètre et sous des conditions donnés. Cela ne signifie pas que l’action est déjà exécutée ou que sa ressource est réservée.','Droit de poursuivre une action identifiée.','Préciser les conditions et la portée de l’autorisation.',
'Microsoft distingue un ordre planifié approuvé de son affermissement. SAP distingue aussi une affectation qui attend une libération manuelle d’un état permettant de créer la livraison. Les deux montrent une possibilité de passage soumise à une décision.\n\nFLOW utilise autoriser comme convention de sens, sans assimiler les statuts éditeurs entre eux. L’action autorisée doit être nommée : affermir, libérer ou prendre en charge ne sont pas interchangeables.',
example('approved','Microsoft — approuvé pour affermissement','Un ordre planifié reçoit le statut Approved.','Il est conservé pour un éventuel affermissement ; l’approbation n’est pas l’affermissement lui-même.','Cet usage illustre la séparation entre rendre une action admissible et l’exécuter.'),[
c('approved','Approved for firming','Ordre planifié prêt à être affermi.','Marquer une décision préalable.','L’admissibilité précède l’action suivante.','Approved conserve aussi le plan dans Microsoft.','FLOW ne généralise pas tous les effets de ce statut.','Appui sémantique'),
c('assign','Manual release','Affectation nécessitant une libération.','Permettre l’étape de livraison.','Un résultat peut attendre une autorisation.','Le statut SAP est propre à ARun.','FLOW demande toujours de préciser l’action autorisée.','Appui sémantique')])

start('VER012')
emit('Affecter établit un lien entre une ressource et une demande ou un bénéficiaire précis. Dans le cas Supply, le verbe décrit ce lien et ne suffit pas à promettre la fourniture ou à bloquer la ressource.','Action créant une affectation identifiée.','Nommer ressource, bénéficiaire et quantité concernée.',
'SAP nomme Assign l’association de ressources physiques ou futures à des besoins. Microsoft emploie pegging pour la couverture liée à des demandes. Les mots diffèrent, mais rendent visible une association déterminée.\n\nFLOW garde affecter pour l’acte de création du lien. L’affectation d’une tâche est un autre objet ; elle doit être qualifiée pour ne pas être confondue avec celle d’un stock.',
example('assign','SAP — choisir une ressource future','Dans ITA, SAP permet de choisir le type de ressource, présente ou future, à associer au besoin.','Le traitement crée une affectation sur le périmètre sélectionné.','FLOW retient l’effet de lien ; réservation et confirmation conservent leur propre acte.'),[
c('assign','Assign','Ressource présente ou future et besoin.','Créer leur association.','Même acte de liaison dans le cas Supply.','L’acte SAP peut produire des effets protecteurs supplémentaires.','FLOW distingue l’acte de réserver.','Appui sémantique'),
c('keep','Peg demand to supply','Demande couverte par une ressource.','Établir ou conserver un rattachement.','La ressource sert un besoin identifié.','Pegging renvoie à la logique de planification Microsoft.','Usage voisin, sans imposer l’organisation du plan.','Appui sémantique')])

start('VER013')
emit('Promettre prend un engagement sur ce qui sera fourni à une demande. Il faut préciser le résultat, notamment quantité et date, ainsi que les conditions qui permettent de compter dessus.','Acte d’engager une réponse de satisfaction.','Passer d’une proposition à une réponse tenue.',
'Oracle distingue le résultat exploré de son application. PeopleSoft emploie promise pour les quantités attribuées à des demandes dans ses traitements de stock. Ces usages rapprochent calcul et engagement à des degrés différents.\n\nFLOW emploie le verbe pour l’effet d’engagement, et non pour tout calcul préparatoire. Promettre ne signifie ni affecter une ressource précise ni constater une livraison.',
example('check','Illustration FLOW — engager vendredi','Après examen des possibilités, 60 pièces vendredi sont proposées puis confirmées.','Le demandeur dispose désormais d’un engagement sur ces 60 pièces, selon les conditions convenues.','La séparation Oracle entre exploration et application éclaire le passage, sans définir la procédure d’accord FLOW.'),[
c('check','Commit a promising result','Résultat après exploration.','Appliquer la réponse retenue.','Une possibilité n’a pas encore l’effet d’un engagement.','Oracle parle de scheduling d’une ligne.','FLOW qualifie explicitement l’engagement de satisfaction.','Appui sémantique'),
c('ps','Promise stock','Quantité promise à une demande.','Tenir une réponse de quantité.','Le bénéficiaire et la quantité sont identifiés.','La fonction est regroupée avec réservation et libération.','Le verbe FLOW n’emporte pas automatiquement ces autres effets.','Appui sémantique')])

start('VER015')
emit('Prioriser établit un ordre relatif entre des demandes concurrentes. Le résultat doit indiquer lesquelles passent avant les autres et pour quelles raisons, sans prétendre les avoir déjà satisfaites.','Classement de traitement ou de satisfaction.','Appliquer des critères explicites et rendre les conflits visibles.',
'SAP BOP peut réordonner des besoins ; PeopleSoft utilise des rangs de priorité avant la distribution. Le premier décrit un traitement de réexamen, le second explicite la séquence d’examen.\n\nFLOW retient le sens commun de classement, sans imposer leurs critères. Un rang prioritaire n’affecte pas une ressource à lui seul et n’autorise pas la levée d’une protection.',
example('ps','PeopleSoft — plusieurs règles, un rang','L’exemple PeopleSoft fait correspondre une ligne aux rangs 10, 30 et 50.','Le produit retient le rang 10 selon sa convention.','FLOW exige un ordre explicite, mais n’adopte ni cette numérotation ni ce mode de résolution.'),[
c('bop','Reprioritize requirements','Besoins déjà créés.','Revoir leur ordre selon les règles.','Le classement peut évoluer.','BOP effectue aussi réallocation et confirmation.','FLOW isole l’effet de priorité.','Appui sémantique'),
c('ps','Priority rank','Lignes en concurrence.','Déterminer leur ordre d’examen.','Les règles doivent produire un ordre utilisable.','Le rang est propre au traitement PeopleSoft.','Le verbe FLOW ne prescrit pas cette convention.','Appui sémantique')])

start('VER016')
emit('Arbitrer choisit entre des possibilités ou demandes qui ne peuvent pas toutes être retenues ensemble. Le choix doit rendre explicites ses règles, contraintes et conséquences.','Possibilités concurrentes et résultat décidé.','Expliquer ce qui est retenu, écarté ou laissé sans solution.',
'Oracle Profitable to Promise départage des sources selon délai et coût. Microsoft DOM associe plusieurs objectifs et contraintes de satisfaction. Les deux illustrent des choix sous contraintes, avec des règles particulières à leurs fonctions.\n\nFLOW garde arbitrer comme verbe à qualifier : arbitrer une priorité, un coût ou un plan ne donne pas la même responsabilité. Il ne nomme ni un comité ni un outil et n’impose aucune pondération.',
example('ptp','Illustration FLOW — une économie ne lève pas une obligation','Une solution coûte moins cher mais manque un délai impératif ; une autre respecte l’engagement.','Le choix explique pourquoi l’économie seule ne suffit pas à retenir la première.','Le rapprochement coût/service d’Oracle illustre le conflit ; les contraintes réelles sont celles du cas métier.'),[
c('ptp','Select an alternative fulfillment scenario','Solutions de fourniture et coûts.','Départager les options admissibles.','Le choix dépend de contraintes et critères.','Oracle définit sa hiérarchie de priorité.','FLOW rend le cadre d’arbitrage explicite.','Appui sémantique'),
c('dom','Balance conflicting fulfillment needs','Besoins concurrents du réseau.','Choisir selon règles et objectifs.','Toutes les possibilités ne peuvent être retenues ensemble.','DOM fournit une optimisation produit.','Le verbe FLOW n’exige pas un solveur.','Appui sémantique')])

start('VER018')
emit('Réaffecter modifie un lien de ressource déjà établi. Ce verbe décrit le changement de ressource ou de bénéficiaire, sans supposer qu’une promesse change en même temps.','Affectations existantes dans un périmètre révisable.','Appliquer les nouveaux liens autorisés.',
'SAP Reassignment remet en jeu les liens d’une ligne. Microsoft montre qu’une ressource reçue peut aussi être rattachée à une demande plus précoce selon les règles de préservation. Ces usages rendent visible le changement de couverture.\n\nFLOW exige de qualifier ce qui devient différent et ce qui reste protégé. Réaffecter ne donne pas un droit général de casser réservations, gels ou engagements.',
example('reassign','Illustration FLOW — autre arrivage, même promesse','Les 40 pièces d’une commande étaient liées à l’arrivage A ; B offre les mêmes quantités et dates admissibles.','Le lien peut passer de A à B sans modifier la promesse.','SAP étaye la révision de liens ; FLOW précise que son effet sur l’engagement doit être examiné séparément.'),[
c('reassign','Reassignment','Liens déjà affectés.','Les remettre en jeu selon les règles.','Le rattachement aux ressources change.','SAP décrit une remise en jeu complète de la ligne.','FLOW permet une révision ciblée des liens.','Appui sémantique'),
c('keep','Reallocate received inventory','Stock reçu lié à une demande future.','Permettre ou empêcher son nouveau rattachement.','La réaffectation dépend de conditions de préservation.','La règle Microsoft est liée à un horizon de planification.','FLOW qualifie le périmètre révisable sans importer ce paramètre.','Appui sémantique')])

def finish():
    for kind in ('nodes','terms'):
        by={r['id']:r for r in OUT[kind]}
        expected=[r['id'] for r in INPUT[kind]]
        assert set(by)==set(expected),(kind,set(expected)-set(by),set(by)-set(expected))
        assert len(by)==len(OUT[kind])
        OUT[kind]=[by[i] for i in expected]
    required={'vendor','product','element_name','element_type','relationship','similarities','differences','flow_position','source_title','source_url','source_version','source_locator','consulted_on','status','source_refs','evidence_limits','concept_name','scope_summary','approach_summary'}
    allrows=OUT['nodes']+OUT['terms']
    for row in allrows:
        assert len({c['source_url'] for c in row['market_comparisons']})>=2,row['id']
        for comp in row['market_comparisons']:
            assert required<=comp.keys(),row['id']
            assert all(comp[k] for k in required),row['id']
        assert len(row['market_inspiration']['synthesis'])>=2,row['id']
        assert row['market_inspiration']['examples']
        errors=validate_comparisons(row['market_comparisons'],row['id'])+validate_inspiration(row['market_inspiration'],row['market_comparisons'],row['id'])
        assert not errors, errors
    records=[]
    for key,s in S.items():
        ids=[r['id'] for r in allrows if any(c['source_url']==s['source_url'] for c in r['market_comparisons']) or any(e['source_url']==s['source_url'] for e in r['market_inspiration']['examples'])]
        previous=[dict(id=i,source_refs=c.get('source_refs',[]),status=c.get('status')) for i,f in OLD.items() for c in f.get('market_comparisons',[]) if c['source_url']==s['source_url']]
        examples=[dict(id=r['id'],title=e['title'],kind='Illustration FLOW' if 'Illustration FLOW' in e['title'] else 'Exemple effectivement présent dans la source') for r in allrows for e in r['market_inspiration']['examples'] if e['source_url']==s['source_url']]
        records.append(dict(local_key=key,**s,supported_ids=ids,previous_correspondences=previous,examples=examples,presentation_status='retained' if ids else 'reviewed_not_retained'))
    write_text_if_changed(ROOT/'promising-output.yaml',dumps(OUT))
    write_text_if_changed(ROOT/'promising-sources.yaml',dumps({'source':'U477','batch':'promising','sources':records,'limits':'Synthèses ciblées et reformulées ; pas de reproduction intégrale des documents, pas de consensus ni réalisation installée déduits.'}))
    print(f"PROMISING: {len(OUT['nodes'])} nodes, {len(OUT['terms'])} terms, {len(records)} sources reviewed; contracts OK")

if __name__=='__main__':
    finish()
