// Read-only checks against the actual publication, no data fixture.
import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/laure/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});
const version='2026-09-19.5',checks=[],errors=[],base='http://127.0.0.1:8765';
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
 const go=async hash=>{await page.goto(`${base}/#version=${version}&${hash}`);await page.locator('#page-title').waitFor();};
 await go('node=universe-supply&view=map');
 assert.equal(await page.locator('#page-title').innerText(),'Supply Chain Orchestration');
 await page.screenshot({path:fileURLToPath(new URL('v012-base.png',import.meta.url)),fullPage:false});
 checks.push('Vue univers Supply accessible dans v012.');
 await go('node=D04.j&view=sheet');await page.locator('.business-sheet').waitFor();
 assert.match(await page.locator('.business-sheet').innerText(),/Exemples concrets/);
 assert.equal(await page.locator('.sheet-information-list a').count(),6);
 await page.getByRole('tab',{name:'Marché & choix',exact:true}).click();await page.locator('.market-source a').first().waitFor();
 checks.push('Purchase Order : fiche, exemples et références marché publiés.');
 await go('view=glossary&glossary=model&term=TER086');await page.locator('[data-glossary="model"] #term-TER086').waitFor();
 await go('view=glossary&glossary=meta&term=MOD012');await page.locator('[data-glossary="meta"] #term-MOD012').waitFor();
 checks.push('Les deux glossaires sont séparés et disponibles dans la même publication.');
 await go('view=principles');await page.locator('.guide-lesson').waitFor();
 assert.equal(await page.locator('.guide-topics > button').count(),6);
 checks.push('Guide du méta modèle associé : six repères disponibles.');
 await go('view=information&information=PINFO-011');await page.locator('[data-information-id="PINFO-011"]').waitFor();
 assert.equal(await page.locator('.information-index li').count(),14);
 await page.locator('.information-links a').filter({hasText:'Fulfillment Commitment'}).first().click();
 await page.locator('[data-information-id="PINFO-012"]').waitFor();
 assert.equal(await page.locator('.status-badge,.lifecycle-badge,.source-link').count(),0);
 checks.push('Travaux U468 existants : 14 fiches accessibles et lien proposition/engagement fonctionnel.');
 await page.goto(`${base}/#version=2026-09-19.4&view=information`);
 await page.getByRole('heading',{name:'Informations non publiées dans cette version',exact:true}).waitFor();
 checks.push('v011 reste inchangée, sans récupération du catalogue récent.');
 assert.deepEqual(errors,[]);
 const result={version,checks,errors};
 await writeFile(new URL('browser-verification.json',import.meta.url),JSON.stringify(result,null,2));
 console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
