"""Integrate the three explicitly accepted Replenishment Decision behaviors."""
from copy import deepcopy
from datetime import datetime, timezone
from hashlib import sha256
from scripts.apply_supplier_return_U387 import ROOT, save, append
from scripts.structured_io import read
from scripts.lifecycle import value_hash

OUT=ROOT/'modeles/backlog/history/replenishment-behaviors-U427'
REFS=['U427','ELM253','CMP164']
DATA=[
 dict(id='BHV083',candidate='P01',name='Requirement-based Replenishment',definition='Déterminer les apports pour satisfaire des besoins datés, après déduction des ressources utilisables et des apports attendus.',benefit='Répondre aux besoins identifiés à leurs échéances en tenant compte des ressources admissibles, sans créer des apports déjà couverts.',scope='''Déterminer les quantités et dates d’apport à partir des besoins identifiés sur l’horizon considéré. Examiner stock utilisable, entrées attendues à temps, apports déjà engagés, délais, conditionnements et contraintes ; expliciter les besoins qui restent non satisfaits. Un besoin daté n’est pas nécessairement une commande client unitaire : il peut provenir de besoins prévus ou agrégés du réseau.

Traiter les besoins individuellement ou les regrouper dans une période selon la politique applicable. La cadence et la taille de lot restent des paramètres ou modalités ; elles ne créent pas de sous-comportement. Ne pas compter deux fois une demande déjà incluse dans un besoin agrégé ou une cible.

Exemple fictif : 120 pièces sont nécessaires à J+7 ; 70 sont utilisables et 20 supplémentaires attendues à temps. Déterminer un apport complémentaire de 30 avant prise en compte des contraintes de lot et de délai. Si ces contraintes empêchent l’apport à temps, rendre le manque explicite plutôt que présumer sa satisfaction.

Le résultat décrit les apports nécessaires et leurs dates. Il ne crée pas l’Order d’achat ou de transfert, ne réserve pas les ressources et ne constitue pas une promesse. Initial Stocking Decision conserve les apports d’implantation. Le mécanisme peut être mobilisé avec Replenishment Adjustment pour réviser les apports existants plutôt que les recréer.''',native='Per requirement / Per period',common='Microsoft distingue apports par besoin et agrégation des besoins nets sur une période.',difference='FLOW retient une seule politique métier orientée besoins datés. La période est une modalité et les objets créés par le produit ne deviennent pas une obligation de création d’Order par la décision.'),
 dict(id='BHV084',candidate='P02',name='Target-based Replenishment',definition='Déterminer les apports pour retrouver une cible de stock selon les seuils applicables, sans nécessiter une commande identifiée pour chaque apport.',benefit='Maintenir la disponibilité à un niveau souhaité par lieu et période, en utilisant une position projetée et les paramètres pertinents.',scope='''Déterminer les apports nécessaires pour rétablir une cible selon les seuils et conditions de déclenchement applicables. Utiliser les objectifs et seuils fournis par Inventory Target Decision et leurs versions opérationnelles gérées par Supply Protection. Ces paramètres peuvent évoluer avec les besoins, la période, les délais et les risques ; ils ne sont pas présumés fixes.

Prendre en compte le stock admissible, les apports déjà attendus et les besoins déjà inclus dans la position projetée. Distinguer seuil de déclenchement, cible à atteindre, minimum de sécurité, conditionnement et capacité physique. Le comportement utilise les paramètres ; il ne les recalcule pas à la place d’Inventory Target Decision.

Exemple fictif : une position projetée de 50 pièces passe sous le seuil de 60, pour une cible de 100. Déterminer un apport de 50 en l’absence d’autres contraintes. Si les apports sont des multiples de 12, examiner 60 et l’excédent résultant ; la cible et les contraintes ne sont pas silencieusement réécrites pour masquer cet écart.

Le résultat recommande quantités et dates d’apport ; la création ou modification des Orders relève de D04. Cette politique ne réserve pas le stock, ne protège pas une enveloppe de canal et ne décide pas implicitement de déplacer du stock entre lieux. Replenishment Adjustment peut réviser les apports existants pour retrouver la cible. Les deux politiques de réassort peuvent contribuer au même scénario sans décompter deux fois le même besoin.''',native='Min/Max',common='Microsoft documente un réassort vers un niveau cible lorsque la quantité projetée passe sous un seuil.',difference='FLOW distingue la détermination des objectifs de leur utilisation pour les apports. Aucun seuil permanent, formule unique, comportement par paramètre ou couverture de toutes les méthodes Microsoft n’est déduit.'),
 dict(id='BHV085',candidate='P03',name='Replenishment Adjustment',definition='Déterminer comment modifier les apports déjà prévus pour éviter pénuries, excédents ou décalages, en respectant les engagements.',benefit='Adapter les ressources futures au besoin actualisé sans créer systématiquement des apports supplémentaires ni ignorer les engagements existants.',scope='''Réexaminer les quantités et dates des apports déjà prévus ou engagés lorsque besoins, cibles, disponibilité ou contraintes évoluent. Déterminer l’avance, le report, l’augmentation, la réduction ou l’annulation admissible à recommander ; ces actions sont des résultats possibles d’un mécanisme, pas cinq comportements.

Tenir compte du degré de fermeté, des éléments gelés, des accords fournisseurs, des réalisations acquises et des possibilités réelles de modification. Refuser un report annoncé par un fournisseur ne rétablit pas sa capacité. Lorsque l’ajustement souhaité est impossible, exposer le manque ou l’excédent résiduel et les alternatives à examiner avec les décisions responsables.

Exemple fictif : une cible passe de 100 à 80 pièces ; 30 sont présentes et 70 attendues. Examiner une réduction ou un report de 20. Si seules 10 peuvent être réduites, conserver explicitement les 10 restantes dans le bilan et examiner leur devenir. Aucun changement d’engagement ne résulte du seul calcul.

Le résultat est une recommandation d’ajustement, pas une mise à jour transactionnelle. D04 et Order Lifecycle Management vérifient et appliquent les changements autorisés, Purchase Order traite la confirmation fournisseur applicable, et D06 adapte les prestations en cours. Promise Management conserve les conséquences sur les promesses. Le mécanisme se combine avec Requirement-based Replenishment ou Target-based Replenishment ; il ne constitue pas une troisième politique mutuellement exclusive.''',native='Action messages — Advance / Postpone / Increase / Decrease',common='Microsoft produit des suggestions de modification d’ordres existants en réponse aux changements de besoins.',difference='Les recommandations et leur application restent séparées dans FLOW. La liste Microsoft consultée ne justifie pas un code Cancel natif ; l’annulation admissible est une possibilité FLOW soumise aux conditions métier. Pas de garantie d’arrêt des services par le calcul.')
]


def main():
    assert not OUT.exists()
    mp=ROOT/'modeles/backlog/model.yaml';before=read(mp);model=deepcopy(before)
    assert not ({d['id'] for d in DATA}&{n['id'] for n in model['nodes']})
    retired=read(ROOT/'modeles/backlog/refactoring-implementation.yaml')['retired_ids_never_reuse'];assert not set(retired)&{d['id'] for d in DATA}
    assert '## U427\n' not in (ROOT/'connaissance/01-contributions-utilisateur.md').read_text(encoding='utf-8')
    append('connaissance/01-contributions-utilisateur.md','## U427\n\n**id**\n\nU427\n\n**date**\n\n2026-09-19\n\n**titre**\n\nAdopter les trois comportements de Replenishment Decision\n\n**texte**\n\nok pour le réassort\n\n**contexte et portée**\n\nAccord sur les trois comportements présentés après U426 : Requirement-based Replenishment, Target-based Replenishment et Replenishment Adjustment, avec leurs responsabilités formulées dans le tableau et leur rattachement sous Replenishment Decision. Deux politiques et un mécanisme d’ajustement combinable ; cibles/seuils restent dans Inventory Target Decision, changements autorisés dans D04, orchestration dans D06. Noms, définitions présentées et parents adoptés ; descriptions développées, exemples, comparaisons et justifications éditoriales gardent leur portée propre. Cet accord remplace la non-décomposition U425 et clôt seulement le point réassort de l’audit ; les retours et autres points restent distincts.')
    OUT.mkdir()
    for p,n in [('modeles/backlog/model.yaml','model-before.yaml'),('modeles/backlog/behavior-gap-audit.yaml','audit-before.yaml'),('modeles/backlog/d05-refactoring.yaml','d05-before.yaml'),('AGENTS.md','AGENTS-before.md')]: (OUT/n).write_bytes((ROOT/p).read_bytes())
    stamp=datetime.now(timezone.utc).isoformat().replace('+00:00','Z')
    def life(fields,approved):
        return dict(state='urbanist_validated',recorded_at=stamp,recorded_by='Codex',source_refs=['U427'],validated_fields=approved,value_sha256={f:value_hash(fields[f]) for f in approved},note='U427 : noms, définitions présentées et parents adoptés ; scope, exemples et comparaisons développés restent éditoriaux.')
    parent=next(n for n in model['nodes'] if n['id']=='D05.e');f=parent['fields']
    old='U425 clôt P01, P02 et P03 comme couverts par cette responsabilité. Besoins datés et seuil/cible sont des politiques descriptives ; l’ajustement des apports est une faculté transverse. Leur existence dans les produits ne démontre pas un bénéfice justifiant trois comportements supplémentaires. Aucun nouveau comportement créé ; cette clôture ciblée ne prétend pas couvrir toutes les méthodes du marché.'
    assert old in f['scope']
    f['scope']=f['scope'].replace(old,'U427 adopte trois comportements : Requirement-based Replenishment, Target-based Replenishment et Replenishment Adjustment. Les deux premiers rendent explicites des politiques distinctes de détermination des apports ; le troisième révise les apports existants et se combine avec les deux. Cette décomposition remplace la conclusion de non-décomposition U425 ; les codes, paramètres et formules produits ne créent pas de sous-comportement. Le point réassort de l’audit est traité, sans présumer une couverture exhaustive du marché.')
    f['decomposition_rationale']='Deux politiques produisent des apports selon des logiques métier distinctes : satisfaire des besoins datés ou rétablir une cible de stock. L’ajustement des apports existants ajoute un mécanisme combinable qui évite de répondre à tout changement par une commande supplémentaire et traite pénuries, excédents ou décalages sous engagements. Cette différence et ce bénéfice justifient les trois comportements ; seuils, périodes et tailles de lot restent des paramètres. Détermination des cibles, décision d’apports, application aux Orders et réalisation restent distinctes.'
    for c in f.get('market_comparisons',[]):
        c['flow_position']='U427 : deux politiques de réassort et un mécanisme d’ajustement combinable sous D05.e. La décomposition métier n’impose pas celle du produit ; Inventory Target Decision détermine les cibles, D04 applique les changements autorisés et D06 orchestre.'
        c['source_refs']=list(dict.fromkeys(c['source_refs']+['U427']))
    parent['revision']+=1;parent['source_refs']=list(dict.fromkeys(parent['source_refs']+REFS));parent['review']['note']='U427 intègre les trois comportements adoptés ; définition du parent conservée et détails développés éditoriaux.'
    adopted=[]
    for d in DATA:
        adjust=d['candidate']=='P03'
        url='https://learn.microsoft.com/en-us/dynamics365/supply-chain/master-planning/'+('action-messages' if adjust else 'coverage-settings')
        comparison=dict(vendor='Microsoft',product='Dynamics 365 Supply Chain Management',element_name=d['native'],element_type='Recommandations produit' if adjust else 'Méthodes de réapprovisionnement et lotissement',relationship='Recouvrement partiel',similarities=d['common'],differences=d['difference'],flow_position='U427 : comportement métier adopté sous Replenishment Decision. Comparaison descriptive, sans alignement taxonomique exact ni preuve de déploiement Beaumanoir.',source_title='Action messages' if adjust else 'Coverage settings',source_url=url,source_version='2026-03-26' if adjust else '2026-03-25',source_locator='Introduction ; Select action messages' if adjust else 'Coverage codes',consulted_on='2026-09-19',evidence_limits='Page primaire ouverte avant intégration. Les noms FLOW ne sont pas présentés comme un catalogue de capacités Microsoft.',status='proposed',source_refs=REFS)
        fields=dict(name=d['name'],definition=d['definition'],finality=d['benefit'],scope=d['scope'],market_comparisons=[comparison])
        model['nodes'].append(dict(id=d['id'],revision=1,kind='behavior',layer=parent['layer'],fields=fields,source_refs=REFS,source_locator=dict(path='connaissance/01-contributions-utilisateur.md',anchor='u427'),adoption_ids=[],review=dict(state='partial',note='Nom, définition présentée et parent adoptés ; description développée et rapprochement éditoriaux.'),lifecycle=life(fields,['name','definition'])))
        relation=dict(id='REL-BEHAVIOR-'+d['id'],revision=1,type='contains',source_id='D05.e',target_id=d['id'],source_refs=['U427'],review=dict(state='accepted',note='Parent explicite adopté U427.'))
        relation['lifecycle']=life(relation,['type','source_id','target_id']);model['relations'].append(relation)
        adopted.append(dict(node_id=d['id'],candidate_id=d['candidate'],parent_id='D05.e',name=d['name'],definition=d['definition'],validated_fields=['name','definition'],value_sha256={k:value_hash(fields[k]) for k in ['name','definition']}))
    save('modeles/backlog/model.yaml',model)
    migration=dict(source_refs=REFS,model_before=(OUT/'model-before.yaml').relative_to(ROOT).as_posix(),model_before_sha256=sha256((OUT/'model-before.yaml').read_bytes()).hexdigest(),behaviors=adopted,delta={})
    for key in ['nodes','relations']:
        old={x['id']:x for x in before[key]};new={x['id']:x for x in model[key]}
        migration['delta'][key]=dict(added={i:value_hash(new[i]) for i in sorted(new.keys()-old.keys())},removed=sorted(old.keys()-new.keys()),changed={i:value_hash(new[i]) for i in sorted(new.keys()&old.keys()) if new[i]!=old[i]})
    save((OUT/'implementation.yaml').relative_to(ROOT),migration)
    audit=read(ROOT/'modeles/backlog/behavior-gap-audit.yaml');audit['implementation_U427']=migration;audit['baseline']['sha256']=sha256(mp.read_bytes()).hexdigest();audit['source_refs']=list(dict.fromkeys(audit['source_refs']+REFS))
    mapping={d['candidate']:d['id'] for d in DATA}
    for p in audit['candidates']:
        if p['id'] in mapping:
            p['status']='implemented_U427';p['implemented_as']=mapping[p['id']];p['source_refs']=list(dict.fromkeys(p['source_refs']+REFS));p['review_note']='U427 : intégré sous Replenishment Decision avec nom et définition présentés après U426. Les formulations et questions initiales restent historiques ; la clôture sans comportement U425 est remplacée.'
    a=next(x for x in audit['assessments'] if x['capability_id']=='D05.e');a.update(existing_behaviors=[d['id'] for d in DATA],verdict='trois comportements intégrés U427',diagnosis=f['decomposition_rationale'],recommendation='Point réassort traité : deux politiques et un mécanisme d’ajustement combinable ; paramètres, cibles et mise en action gardent leurs frontières.')
    for d in DATA:audit['existing_behavior_review'].append(dict(behavior_id=d['id'],status='integrated_U427',recommendation='Nom, définition et parent adoptés. Exemples et comparaisons éditoriaux ; ni calcul des cibles ni mise à jour des Orders absorbés.',market_sources=['S09'] if d['candidate']=='P03' else ['S08']))
    s=audit['current_synthesis_U298'];s['reassess_candidate_ids']=[i for i in s['reassess_candidate_ids'] if i not in mapping];s['implemented_candidate_ids']=list(dict.fromkeys(s['implemented_candidate_ids']+list(mapping)));s['source_refs']=list(dict.fromkeys(s['source_refs']+['U427']));s['retained_scope']='U427 intègre P01–P03 comme comportements sous D05.e. P12 reste conditionnel ; P04/P10 restent à réexaminer. Intégrations antérieures conservées.';s['next_step']='Réassort traité U427. Terminer les autres points de l’audit existant : frontière commerciale des retours et disposition de P04/P10/P12.'
    audit['replenishment_reassessment_U426']['status']='integrated_U427';audit['replenishment_reassessment_U426']['limits']='Proposition adoptée U427 avec les formulations présentées à Laurent ; descriptions développées éditoriales. Voir implementation_U427 pour les valeurs et empreintes exactes.'
    save('modeles/backlog/behavior-gap-audit.yaml',audit)
    ann=read(ROOT/'modeles/backlog/d05-refactoring.yaml');ann['replenishment_reassessment_U426']['status']='integrated_U427';ann['replenishment_behaviors_U427']=dict(status='integrated',source_refs=REFS,behaviors=adopted,scope='Noms, définitions présentées et rattachements adoptés ; justification développée, descriptions et comparaisons éditoriales.',evidence=(OUT/'implementation.yaml').relative_to(ROOT).as_posix());save('modeles/backlog/d05-refactoring.yaml',ann)
    agents=ROOT/'AGENTS.md';text=agents.read_text(encoding='utf-8');start=text.index('- **Replenishment Decision (U425/U426)**');end=text.index('\n',start)
    text=text[:start]+'- **Replenishment Decision (U427)** : trois comportements adoptés sous D05.e : Requirement-based Replenishment BHV083, Target-based Replenishment BHV084 et Replenishment Adjustment BHV085. Deux politiques et un mécanisme d’ajustement combinable, sans comportement par seuil, période ou taille de lot. Inventory Target Decision détermine les cibles ; D04/Lifecycle applique les changements autorisés ; D06 orchestre. P01–P03 sont intégrés, la non-décomposition U425 est remplacée. Les descriptions développées et correspondances gardent leur portée éditoriale ; annexe `d05-refactoring.yaml`, `replenishment_behaviors_U427`.'+text[end:];agents.write_text(text,encoding='utf-8')
    append('marche/elements.md','### ELM253\n\nMicrosoft Dynamics 365 SCM — Coverage settings (25 mars 2026, Coverage codes) et Action messages (26 mars 2026, Introduction et Select action messages). Sources primaires reconsultées le 19 septembre 2026 pour U427. URLs et synthèses dans les fiches BHV083–085. Deux méthodes de détermination des apports et recommandations d’ajustement ; pas de preuve de réalisation Beaumanoir.')
    append('marche/comparaisons.md','### CMP164\n\nU427 adopte Requirement-based Replenishment, Target-based Replenishment et Replenishment Adjustment sous D05.e. Appui ELM253 : Per requirement/Per period, Min/Max et Action messages. Le bénéfice métier différencie deux politiques et un mécanisme combinable ; la cadence et les paramètres ne justifient pas des nœuds supplémentaires. FLOW conserve calcul des cibles dans D05.a, modifications autorisées dans D04 et orchestration dans D06. Noms/definitions présentés et parent adoptés ; comparaisons détaillées éditoriales. Aucun code Cancel Microsoft déduit de la liste consultée.')
    append('JOURNAL.md','## 2026-09-19 — U427 : réassort décomposé et point d’audit traité\n\nBHV083–085 intégrés sous Replenishment Decision : deux politiques et un mécanisme d’ajustement combinable. P01–P03 marqués intégrés. Justification, exemples, comparaisons Microsoft et instructions actualisés. 139 nœuds, 47 capacités, 74 comportements ; parents et anciennes validations préservés. Aucun autre arbitrage ni release implicite.')
    print('U427 integrated: BHV083-085 under D05.e; P01-P03 implemented.')


if __name__=='__main__':main()
