"""Apply the six Lifecycle dimensions; states are explanatory model content."""
from copy import deepcopy
from datetime import datetime, timezone
from hashlib import sha256
from scripts.apply_supplier_return_U387 import ROOT, save, append
from scripts.structured_io import read
from scripts.lifecycle import value_hash

OUT=ROOT/'modeles/backlog/history/lifecycle-dimensions-U424'
REFS=['U424','ELM251','CMP162']
MERGES={'BHV041':'BHV038','BHV042':'BHV043'}
IDS=['BHV038','BHV036','BHV037','BHV039','BHV040','BHV043']
DEFINITION='Gouverner les évolutions autorisées des Orders selon leurs différentes dimensions métier, en préservant la cohérence entre engagements, modifications en préparation et réalisations acquises.'
DATA={
 'BHV038':dict(name='Order Preparation & Revision',dimension='Préparation et révision',definition='Gouverner la préparation et la prise d’effet du contenu initial ou révisé d’un Order, en distinguant le contenu applicable des modifications en préparation et en préservant les engagements et réalisations acquis.',states=[
 ('Draft — Brouillon','Contenu initial ou modification en préparation, modifiable dans les limites applicables ; il ne remplace pas le contenu en vigueur.'),
 ('In Review — En validation','Version soumise à examen humain ou automatisé ; les changements supplémentaires suivent les règles de retrait et de resoumission.'),
 ('Approved — Approuvé','Version autorisée, dont la prise d’effet peut être immédiate ou différée selon ses conditions.'),
 ('Effective — Applicable','Version actuellement en vigueur pour la portée et la période désignées.'),
 ('Rejected — Rejeté','Proposition non acceptée ; ce rejet n’annule pas automatiquement la demande déjà applicable.'),
 ('Withdrawn — Retiré','Brouillon ou proposition abandonné avant sa prise d’effet ; distinct du retrait du besoin applicable.'),
 ('Superseded — Remplacé','Version auparavant applicable, conservée pour expliquer les engagements et réalisations passés.')],
 scope='Version de contenu initial ou révisé, éventuellement pour une ligne ou une quantité. Ces états concernent la version, pas un statut unique de toute la commande.',
 rules='Brouillon ne signifie ni intention planifiée ni absence automatique de calcul de disponibilité. Une version applicable peut coexister avec une modification en brouillon. Une approbation et sa prise d’effet peuvent coïncider ; le modèle n’impose pas deux étapes ni un contrôle humain. Une version rejetée ou retirée ne modifie pas silencieusement le contenu applicable. La poursuite du traitement pendant révision dépend de la portée et du risque : un Hold explicite peut être nécessaire. Ne pas réécrire les réalisations acquises.',
 example='Une commande de 100 pièces est ferme et 60 pièces sont libérées. Une révision prépare le report de la date demandée des 40 autres pièces. Tant que cette révision n’est pas applicable, la version en vigueur demeure la référence ; aucune suspension des 60 pièces n’est implicite.',
 preserved='Order Rescheduling (BHV041) est intégré ici : avancer ou reporter l’échéance DU BESOIN est une modification du contenu demandé. Delivery Schedule Decision détermine les possibilités de satisfaction ; Promise Management gère les dates promises. La saisie, le clonage sans reprise implicite d’engagement, la soumission et les versions sont des opérations de ce mécanisme. Les capacités par type d’Order conservent leurs parcours métier et conditions spécifiques.'),
 'BHV036':dict(dimension='Engagement',states=[('Planned — Planifié','Intention susceptible d’être révisée selon les règles de planification, non encore affermie.'),('Firm — Ferme','Intention transformée en ordre ferme avec ses engagements propres au type d’Order.'),('Partially Firm — Partiellement ferme','Lecture agrégée lorsque seules certaines lignes ou quantités désignées sont affermies.')],scope='Order, ligne ou quantité selon le type et le mécanisme de firming. Le statut partiel résume des portées distinctes ; il n’est pas obligatoire sur chaque type.',rules='Une demande déjà ferme peut faire l’objet d’une révision en préparation. Affermir n’approuve pas automatiquement une nouvelle version, ne gèle pas toutes les données, ne réserve pas implicitement le stock et n’autorise pas à lui seul la prise en charge. Une dérogation ou un retour au planifié exige des règles métier explicites ; aucune réversibilité universelle.',example='Sur un besoin de transfert planifié de 100 pièces, engager 60 pièces dans un transfert ferme et maintenir 40 pièces à l’état planifié, si ce type d’Order permet cette portée.'),
 'BHV037':dict(dimension='Protection contre la réoptimisation',states=[('Unfrozen — Non gelé','Aucune protection spécifique de ce mécanisme contre la réoptimisation ; les autres engagements et restrictions restent applicables.'),('Frozen — Gelé','Les éléments explicitement désignés sont protégés contre les modifications par la réoptimisation.'),('Partially Frozen — Partiellement gelé','Lecture agrégée : certaines dates, quantités, lignes ou affectations sont protégées et d’autres restent ajustables.')],scope='Éléments désignés d’un Order : date demandée ou promise identifiée, quantité, ligne, engagement ou affectation explicitement incluse.',rules='La portée du gel est obligatoire pour comprendre le statut. Geler ne suspend pas le traitement et ne garantit pas la présence physique d’une ressource. Dégeler rétablit la latitude autorisée sans effacer les autres restrictions. Une révision hors gel peut être simulée comme dérogation sans être appliquée. Un gel devenu irréalisable doit produire une exception visible, pas une levée silencieuse.',example='Protéger la quantité et la date promises vendredi tout en laissant le choix de l’entrepôt ajustable, sauf si cette source fait elle-même partie du gel.'),
 'BHV039':dict(dimension='Autorisation de prise en charge',states=[('Not Released — Non libéré','Aucune autorisation de prise en charge pour la portée considérée.'),('Partially Released — Partiellement libéré','Seule une partie explicitement identifiée des lignes ou quantités est autorisée.'),('Released — Libéré','La prise en charge est autorisée sur toute la portée considérée.'),('Release Withdrawn — Autorisation retirée','Une autorisation précédemment donnée est retirée sur la portée admissible ; son historique est conservé.')],scope='Order, ligne, quantité ou ensemble d’Orders liés. Une libération collective n’impose ni démarrage simultané ni transaction technique atomique.',rules='Released signifie autorisé, pas démarré, expédié ou livré. Un Order libéré peut être suspendu par un Hold sans effacer l’autorisation. Retirer une autorisation ne défait pas les réalisations déjà acquises et ne garantit pas l’arrêt immédiat d’un service en cours : les conséquences sont traitées avec D06. Une quantité encore à satisfaire reste lisible dans le carnet même si une autre partie est libérée.',example='Libérer 60 pièces disponibles et conserver les 40 restantes non libérées ; vérifier également les conditions collectives de complétude et de traitement partiel.'),
 'BHV040':dict(dimension='Suspension de la progression',states=[('Clear — Sans suspension active','Aucun Hold actif pour la progression et la portée considérées ; d’autres prérequis peuvent encore empêcher le traitement.'),('On Hold — Suspendu','Au moins un motif actif interdit la progression désignée.'),('Partially On Hold — Partiellement suspendu','Lecture agrégée lorsque seules certaines lignes, quantités ou progressions sont suspendues.')],scope='Progression explicitement désignée et portée Order, ligne ou quantité ; plusieurs motifs peuvent coexister.',rules='Un motif peut être Active ou Cleared ; ce sont les états du motif, pas de nouveaux états de l’Order. Lever un motif ne lève pas les autres. Clear ne signifie pas Released ni redémarrage effectif. Hold ne gèle pas automatiquement le contenu et n’annule pas le besoin. La suspension décidée et l’arrêt effectivement réalisé des services sont distincts ; D06 gère adaptation et compensation nécessaires.',example='Suspendre l’expédition parce que le magasin ne peut pas réceptionner. Lever ce motif lorsque le magasin est prêt, tout en conservant un éventuel autre blocage.'),
 'BHV043':dict(name='Order Termination',dimension='Fin de la demande',definition='Gouverner le retrait autorisé de tout ou partie du besoin et la clôture de son suivi opérationnel, en préservant les réalisations acquises et en explicitant le devenir du reliquat.',states=[('Open — Ouvert','Un reste à satisfaire ou des effets de fin de traitement restent à résoudre.'),('Closing — Clôture en cours','La fin du suivi est engagée ; des vérifications, confirmations ou effets aval restent attendus.'),('Closed — Clôturé','La fin du suivi opérationnel est établie sur la portée considérée et le devenir du reliquat est explicite.')],scope='Demande opérationnelle ou portée désignée. Les lignes peuvent avoir des situations différentes ; la clôture de l’ensemble dépend des reliquats et effets encore ouverts.',rules='La dimension distingue le statut de clôture et l’étendue de l’annulation : Not Cancelled (aucune quantité retirée), Partially Cancelled (une partie du besoin retirée), Cancelled (tout le besoin de la portée retiré). Une demande peut être partiellement annulée et encore Open, puis Closed après traitement du reste. La raison de clôture précise satisfaction, annulation ou écart accepté ; elle n’est pas une nouvelle étape. Une demande d’annulation refusée ne change pas les quantités applicables. Aucune annulation de quantités déjà réalisées, aucun retour physique ni compensation informatique implicite. Closing peut être immédiat sans attente humaine. Réouverture selon règles du type, sans effacement de la clôture passée.',example='Sur 100 pièces, 60 reçues restent acquises ; annuler les 40 encore attendues si autorisé. La commande demeure ouverte tant que les effets nécessaires ne sont pas résolus, puis est clôturée avec 60 satisfaites et 40 annulées.',preserved='Order Cancellation (BHV042) est intégré ici avec ses restrictions et ses effets propres. Annuler retire le besoin ; clôturer constate la fin de son suivi : ces actes ne deviennent pas synonymes. Retirer une affectation, modifier un scénario ou arrêter un service ne suffit pas à annuler la demande. Clôture opérationnelle distincte de clôture financière et d’archivage ; Order Archiving reste en D03.')
}


def main():
    assert not OUT.exists()
    assert '## U424\n' not in (ROOT/'connaissance/01-contributions-utilisateur.md').read_text(encoding='utf-8')
    append('connaissance/01-contributions-utilisateur.md','## U424\n\n**id**\n\nU424\n\n**date**\n\n2026-09-19\n\n**titre**\n\nAdopter Lifecycle par dimensions et expliciter les états\n\n**texte**\n\nIl faut bien lister les états possibles dans les comportements.\n\nGo pour la mise à jour\n\n**contexte et portée**\n\nAccord sur la capacité Lifecycle unique en D04, sa définition présentée et les six dimensions de décomposition : préparation/révision, engagement, protection, autorisation, suspension, fin de la demande. D03 mobilise Lifecycle ; D06 orchestre et rapporte les réalisations. Demande explicite de documenter les états possibles. Les regroupements intègrent Rescheduling dans préparation/révision et Cancellation avec Closure dans fin de la demande, sans perte des distinctions. Libellés anglais nouveaux, listes détaillées d’états, contraintes et exemples ajoutés sont éditoriaux : leur production est autorisée, pas leur validation métier valeur par valeur. Structuring et Archiving restent distincts en D03.')
    OUT.mkdir()
    for path,name in [('modeles/backlog/model.yaml','model-before.yaml'),('modeles/backlog/behavior-gap-audit.yaml','audit-before.yaml'),('modeles/backlog/order-backlog-review.yaml','review-before.yaml'),('modeles/backlog/order-lifecycle-behaviors.yaml','lifecycle-before.yaml'),('modeles/backlog/refactoring-implementation.yaml','registry-before.yaml'),('AGENTS.md','AGENTS-before.md')]:
        (OUT/name).write_bytes((ROOT/path).read_bytes())
    mp=ROOT/'modeles/backlog/model.yaml';before=read(mp);model=deepcopy(before);nodes={n['id']:n for n in model['nodes']};stamp=datetime.now(timezone.utc).isoformat().replace('+00:00','Z')
    cap=nodes['D04.o'];cap['fields']['definition']=DEFINITION
    cap['fields']['scope']='''Gouverner six dimensions combinables : préparation et révision du contenu, engagement ferme, protection contre la réoptimisation, autorisation de prise en charge, suspension de progression et fin de la demande. Les comportements gouvernent les transitions ; les statuts décrivent la situation à une portée explicite. Aucun statut global ni séquence unique ne résume ces dimensions.

Une version applicable peut rester engagée et partiellement libérée pendant qu’une modification se prépare. Cela n’autorise pas toutes les modifications ni la poursuite systématique des traitements : les impacts et contraintes doivent être examinés, et une suspension peut être requise. Les réalisations acquises ne sont jamais réécrites par une révision.

Pour chaque comportement, les états possibles et leurs significations sont listés dans sa fiche. Ce vocabulaire de référence éditorial ne prescrit pas un enum logiciel universel, une étape manuelle ni la présence de chaque état pour chaque type d’Order. Distinguer valeur d’état, motif, portée, version et quantités ; les états partiels sont des lectures agrégées et non un niveau supplémentaire du modèle.

D04 conserve cette capacité transverse aux intentions des Orders. D03 mobilise ses mécanismes pour engager, protéger ou libérer les commandes du carnet ; les décisions et Planning restent distincts. D06 orchestre les services et rapporte démarrages, réalisations et échecs. Lifecycle applique les transitions selon les faits et autorisations ; il ne prend pas la place de Process Orchestration ou de Process Adaptation.

U424 : six comportements remplacent les huit mécanismes antérieurs. Le changement d’échéance du besoin est intégré à Order Preparation & Revision ; annulation et clôture restent distinguées dans Order Termination. Identifiants des comportements conservés ou retirés avec succession explicite. Order Structuring et Order Archiving restent dans D03 ; aucune décomposition inférieure aux comportements.'''
    cap['fields']['decomposition_rationale']='Une commande peut être ferme, partiellement libérée, gelée sur certains éléments et suspendue sur une progression, tandis qu’une modification reste en brouillon. Ces effets distincts et leurs contraintes de combinaison justifient six mécanismes métier, sans comportement par état ni cycle linéaire universel. Préparation/révision distingue contenu applicable et proposé ; fin de la demande préserve la différence entre retrait du besoin et clôture.'
    life=cap['lifecycle'];life['validated_fields']=list(dict.fromkeys(life['validated_fields']+['definition']));life['value_sha256']['definition']=value_hash(DEFINITION);life['source_refs']=list(dict.fromkeys(life['source_refs']+['U424']));life['recorded_at']=stamp;life['note']+=' U424 : définition présentée adoptée ; six dimensions et listing des états demandés. Détails rédigés éditoriaux.'
    for ident,data in DATA.items():
        n=nodes[ident];f=n['fields']
        if 'name' in data:
            f['name']=data['name'];f['definition']=data['definition']
            life=n['lifecycle']
            for field in ['name','definition']:
                if field in life['validated_fields']:life['validated_fields'].remove(field)
                life['value_sha256'].pop(field,None)
            life['state']='under_instruction' if not life['validated_fields'] else life['state']
            life['note']+=' U424 : périmètre regroupé adopté ; nouveaux nom et définition développée éditoriaux. Anciennes valeurs et accords conservés dans la capture.'
            f['finality']='Préserver la cohérence des engagements pendant les changements du besoin.' if ident=='BHV038' else 'Mettre fin à la demande de façon explicable, sans perdre les réalisations ni laisser de reliquat ambigu.'
        state_lines='\n'.join('- **'+name+'** : '+meaning for name,meaning in data['states'])
        old_scope=f['scope'] if ident not in ['BHV038','BHV043'] else ''
        f['scope']=f"**Dimension gouvernée : {data['dimension']}.**\n\n**Portée des statuts.** {data['scope']}\n\n**États possibles — vocabulaire de référence FLOW.**\n\n{state_lines}\n\n**Combinaisons et transitions.** {data['rules']}\n\n**Exemple métier fictif.** {data['example']}"
        if data.get('preserved'):f['scope']+='\n\n'+data['preserved']
        if old_scope:f['scope']+='\n\n**Précisions métier conservées.**\n\n'+old_scope
        f['scope']+='\n\nU424 : les états listés explicitent la dimension ; les valeurs, règles détaillées et libellés sont des précisions éditoriales à adapter au type d’Order. Aucun nouveau comportement par état et aucune séquence imposée.'
    # Keep the source comparisons of the merged mechanisms without duplicating identical evidence.
    for old_id,new_id in MERGES.items():
        comps=nodes[new_id]['fields'].setdefault('market_comparisons',[])
        for c in nodes[old_id]['fields'].get('market_comparisons',[]):
            if not any(x['source_url']==c['source_url'] and x['element_name']==c['element_name'] for x in comps):comps.append(deepcopy(c))
    for ident in ['D04.o']+IDS:
        for c in nodes[ident]['fields'].get('market_comparisons',[]):
            c['flow_position']='U424 : Lifecycle unique en D04, mobilisé par D03 ; comportements par dimensions métier et états explicites. Les états FLOW ne sont pas tous des codes natifs de cette source. '+('Regroupement de préparation/révision, incluant la date du besoin.' if ident=='BHV038' else 'Annulation et clôture distinguées au sein de la fin de demande.' if ident=='BHV043' else 'Autorisation, protection, suspension, engagement et réalisation restent distincts.')
            c['source_refs']=list(dict.fromkeys(c['source_refs']+['U424']))
    # Primary references directly consulted for the new explanatory state lists.
    for ident,title,url,locator,common,diff in [
        ('D04.o','Purchase order overview','https://learn.microsoft.com/en-us/dynamics365/supply-chain/procurement/purchase-order-overview','Purchase order statuses','Plusieurs statuts coexistent sur une commande : approbation, quantités et documents.','Cette page ne propose pas nos six comportements ni une liste universelle de statuts.'),
        ('BHV038','Approve and confirm purchase orders','https://learn.microsoft.com/en-us/dynamics365/supply-chain/procurement/purchase-order-approval-confirmation','Approval of purchase orders ; Changing purchase orders','Draft, In review, Approved, Rejected ; révision et réapprobation des commandes engagées.','Effective, Withdrawn et Superseded explicitent ici la portée des versions ; pas une transcription des enums Microsoft. Pas de poursuite inconditionnelle de l’exécution.'),
        ('BHV043','Approve and confirm purchase orders','https://learn.microsoft.com/en-us/dynamics365/supply-chain/procurement/purchase-order-approval-confirmation','Canceling purchase orders ; Changing purchase orders','Retrait encadré des quantités restantes et fin du traitement.','FLOW distingue annulation quantitative, clôture opérationnelle et archivage ; ne reprend pas la finalisation financière Microsoft.')]:
        nodes[ident]['fields'].setdefault('market_comparisons',[]).append(dict(vendor='Microsoft',product='Dynamics 365 Supply Chain Management',element_name=title,element_type='Statuts et processus produit',relationship='Recouvrement partiel',similarities=common,differences=diff,flow_position='U424 : dimension métier et états FLOW explicités ; correspondance proposée et portée distincte de l’accord sur le modèle.',source_title=title,source_url=url,source_version='Documentation évolutive consultée le 19 septembre 2026',source_locator=locator,consulted_on='2026-09-19',evidence_limits='Source primaire ouverte ; aucune preuve de déploiement Beaumanoir. Les libellés FLOW détaillés restent éditoriaux.',status='proposed',source_refs=REFS))
    model['nodes']=[n for n in model['nodes'] if n['id'] not in MERGES]
    removed_relations=[r['id'] for r in model['relations'] if r['source_id'] in MERGES or r['target_id'] in MERGES]
    assert set(removed_relations)=={'REL-BEHAVIOR-BHV041','REL-BEHAVIOR-BHV042'}
    model['relations']=[r for r in model['relations'] if r['id'] not in removed_relations]
    link=dict(id='REL-NEEDS-U424-D03.p-D04.o',revision=1,type='relates-to',source_id='D03.p',target_id='D04.o',source_refs=REFS,qualification=dict(role='needs',meaning='Mobilise les transitions autorisées des Orders pour mettre en action le scénario retenu.',conditions=['Selon les engagements, protections et conditions de prise en charge du scénario ; aucun appel systématique.'],effects=['Obtenir l’engagement, la protection, l’autorisation ou la suspension applicable ; la réalisation demeure pilotée et observée en D06.'],scope='D03 prépare et mobilise ; Lifecycle gouverne les transitions en D04. Relation métier, sans composant logiciel partagé imposé.'),review=dict(state='proposed',note='Principe de mobilisation adopté U424 ; contrat détaillé éditorial.'),lifecycle=dict(state='under_instruction',recorded_at=stamp,recorded_by='Codex',source_refs=['U424'],validated_fields=[],value_sha256={},note='Qualification détaillée proposée.'))
    model['relations'].append(link)
    oldnodes={n['id']:n for n in before['nodes']}
    for n in model['nodes']:
        if n!=oldnodes[n['id']]:n['revision']+=1;n['source_refs']=list(dict.fromkeys(n['source_refs']+REFS))
    save('modeles/backlog/model.yaml',model)
    migration=dict(source_refs=REFS,model_before=(OUT/'model-before.yaml').relative_to(ROOT).as_posix(),model_before_sha256=sha256((OUT/'model-before.yaml').read_bytes()).hexdigest(),behaviors=[],dimension_ids=IDS,merges=MERGES,adopted_definition=DEFINITION,editorial_state_lists={i:[x[0] for x in d['states']] for i,d in DATA.items()},delta={})
    for key in ['nodes','relations']:
        old={x['id']:x for x in before[key]};new={x['id']:x for x in model[key]}
        migration['delta'][key]=dict(added={i:value_hash(new[i]) for i in sorted(new.keys()-old.keys())},removed=sorted(old.keys()-new.keys()),changed={i:value_hash(new[i]) for i in sorted(new.keys()&old.keys()) if new[i]!=old[i]})
    save((OUT/'implementation.yaml').relative_to(ROOT),migration)
    registry=read(ROOT/'modeles/backlog/refactoring-implementation.yaml')
    registry['retired_ids_never_reuse']=list(dict.fromkeys(registry['retired_ids_never_reuse']+list(MERGES)))
    assert isinstance(registry['retired_node_redirects'],dict)
    registry['retired_node_redirects'].update(MERGES)
    registry['lifecycle_dimensions_U424']=dict(source_refs=REFS,retired_ids=list(MERGES),successors=MERGES,retired_relation_ids=removed_relations,evidence=(OUT/'implementation.yaml').relative_to(ROOT).as_posix())
    save('modeles/backlog/refactoring-implementation.yaml',registry)
    audit=read(ROOT/'modeles/backlog/behavior-gap-audit.yaml');audit['implementation_U424']=migration;audit['baseline']['sha256']=sha256(mp.read_bytes()).hexdigest();audit['source_refs']=list(dict.fromkeys(audit['source_refs']+REFS))
    a=next(x for x in audit['assessments'] if x['capability_id']=='D04.o');a.update(existing_behaviors=IDS,verdict='six dimensions intégrées U424',diagnosis=cap['fields']['decomposition_rationale'],recommendation='Lire les états dans chaque comportement ; détails éditoriaux, sans statut global ni niveau supplémentaire.')
    audit['existing_behavior_review']=[x for x in audit['existing_behavior_review'] if x['behavior_id'] not in MERGES]
    for x in audit['existing_behavior_review']:
        if x['behavior_id'] in IDS:x.update(status='dimensions_integrated_U424',recommendation='U424 : dimension et états explicites ; mécanismes regroupés avec succession et preuves conservées. Listes détaillées éditoriales.')
    audit['order_backlog_U413'].update(status='lifecycle_dimensions_integrated_U424',note='Lifecycle unique en D04, six dimensions et états documentés ; D03 le mobilise. Archiving et Structuring restent en D03.')
    save('modeles/backlog/behavior-gap-audit.yaml',audit)
    review=read(ROOT/'modeles/backlog/order-backlog-review.yaml');review['source_refs']=list(dict.fromkeys(review['source_refs']+REFS));review['status']='lifecycle_dimensions_integrated_U424'
    review['lifecycle_dimensions_U423']['status']='principle_and_dimensions_adopted_U424'
    review['implementation_U424']=dict(status='integrated',source_refs=REFS,definition=DEFINITION,behavior_ids=IDS,merged_behaviors=MERGES,scope='Principe, définition présentée, six dimensions et documentation des états adoptés ; nouveaux libellés, définitions développées, états et contraintes restent éditoriaux.',evidence=(OUT/'implementation.yaml').relative_to(ROOT).as_posix())
    review['model_state']='136 nœuds, 47 capacités, 71 comportements. Lifecycle unique en D04 avec six dimensions ; D03 le mobilise. Structuring et Archiving restent en D03.'
    review['next_arbitration']='Poursuivre les autres points de l’audit existant ; les codes d’état détaillés et règles par type restent des précisions éditoriales, pas des blocages de catalogue.'
    save('modeles/backlog/order-backlog-review.yaml',review)
    ann=read(ROOT/'modeles/backlog/order-lifecycle-behaviors.yaml');ann['dimensions_U424']=review['implementation_U424'];save('modeles/backlog/order-lifecycle-behaviors.yaml',ann)
    typ=read(ROOT/'modeles/backlog/behavior-typology.yaml');typ['evolution_U424']=dict(source_refs=['U424'],note='Les observations U389 restent datées. U424 remplace les comportements BHV041 et BHV042 par leurs successeurs ; aucune lecture comme sous-comportements.',successors=MERGES);save('modeles/backlog/behavior-typology.yaml',typ)
    agents=ROOT/'AGENTS.md';text=agents.read_text(encoding='utf-8')
    start=text.index('- **Dimensions d’état des Orders');end=text.index('\n',start)
    text=text[:start]+'- **Dimensions d’état des Orders (U421/U424)** : Lifecycle unique en D04, mobilisé par D03. Six dimensions : préparation/révision, engagement, protection contre réoptimisation, autorisation de prise en charge, suspension, fin de la demande. Chaque comportement liste ses états possibles, leur sens et leur portée ; conserver contraintes de combinaison, versions, lignes et quantités. Aucun statut global, sous-comportement ou comportement par valeur. BHV041 intégré à BHV038 ; BHV042 à BHV043, identifiants retirés non réutilisables. Annulation et clôture restent distinctes. U424 adopte définition présentée et dimensions ; nouvelles formulations, listes d’états et règles détaillées restent éditoriales. D06 porte réalisation/adaptation ; Archiving et Structuring restent distincts en D03. Annexe : `order-lifecycle-behaviors.yaml`, `dimensions_U424`.'+text[end:]
    text=text.replace('huit comportements Lifecycle combinables','six dimensions Lifecycle combinables (U424)').replace('avec ses huit comportements dont Release','avec ses six comportements par dimension, dont Release (U424)')
    agents.write_text(text,encoding='utf-8')
    append('marche/elements.md','### ELM251\n\nMicrosoft Dynamics 365 SCM — Purchase order overview (Purchase order statuses), Approve and confirm purchase orders (Approval, Changing, Canceling), Firm planned orders (Introduction), Manage order holds (motifs et levée). Pages primaires ouvertes le 19 septembre 2026. URL et rapprochements sur D04.o et comportements, complétés par ELM249/250. Plusieurs statuts métier coexistants ; mécanismes produit, pas catalogue normatif FLOW. Les listes FLOW n’affirment pas une équivalence exacte avec les codes Microsoft.')
    append('marche/comparaisons.md','### CMP162\n\nU424 — Lifecycle unique en D04, six dimensions documentées par des états à portée explicite. Appui Microsoft ELM249–251 ; séparation états d’approbation, réalisation et documents, affermissement et suspension. FLOW regroupe préparation/révision et fin de la demande, sans assimiler annulation à clôture ni autorisation à réalisation. BHV041 intégré à BHV038, BHV042 à BHV043. Les nouveaux noms anglais, valeurs d’état et règles détaillées sont éditoriaux ; l’accord porte sur principe, définition présentée et dimensions. Aucune preuve installée Beaumanoir. Relation D03 Planning → Lifecycle explicite la mobilisation sans mutualisation logicielle présumée.')
    append('JOURNAL.md','## 2026-09-19 — U424 : Lifecycle par dimensions et états\n\nSix comportements sous D04.o ; états, portées, contraintes et exemples décrits dans les fiches. Rescheduling intégré à préparation/révision ; Cancellation et Closure réunis dans fin de demande en conservant leurs effets distincts. Définition Lifecycle présentée adoptée ; listes détaillées éditoriales. D03 mobilise Lifecycle ; historique et identifiants retirés conservés. Audit existant actualisé ; aucune release.')
    (OUT/'README.md').write_text('# U424 — Lifecycle par dimensions\n\nSix comportements, états possibles dans les scopes ; deux identifiants retirés avec succession. Captures et empreintes préservent les validations précédentes. Aucune release.\n',encoding='utf-8')
    print('U424 integrated: six dimensions, explicit states; 136 nodes and 71 behaviors.')


if __name__=='__main__':main()
